# TCL File Generated by Component Editor 21.1
# Tue Feb 08 15:01:03 GMT 2022
# DO NOT MODIFY


# 
# CoreFlute "Core" v1.0
#  2022.02.08.15:01:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module CoreFlute
# 
set_module_property DESCRIPTION ""
set_module_property NAME CoreFlute
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkP2_Core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkP2_Core.v VERILOG PATH C:/Users/nudy1/Desktop/Verilog_RTL/mkP2_Core.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RST_N reset_n Input 1


# 
# connection point master0
# 
add_interface master0 axi4 start
set_interface_property master0 associatedClock clock
set_interface_property master0 associatedReset reset_sink
set_interface_property master0 readIssuingCapability 1
set_interface_property master0 writeIssuingCapability 1
set_interface_property master0 combinedIssuingCapability 1
set_interface_property master0 ENABLED true
set_interface_property master0 EXPORT_OF ""
set_interface_property master0 PORT_NAME_MAP ""
set_interface_property master0 CMSIS_SVD_VARIABLES ""
set_interface_property master0 SVD_ADDRESS_GROUP ""

add_interface_port master0 master0_araddr araddr Output 64
add_interface_port master0 master0_arburst arburst Output 2
add_interface_port master0 master0_arcache arcache Output 4
add_interface_port master0 master0_arid arid Output 5
add_interface_port master0 master0_arlen arlen Output 8
add_interface_port master0 master0_arlock arlock Output 1
add_interface_port master0 master0_arprot arprot Output 3
add_interface_port master0 master0_arqos arqos Output 4
add_interface_port master0 master0_arready arready Input 1
add_interface_port master0 master0_arregion arregion Output 4
add_interface_port master0 master0_arsize arsize Output 3
add_interface_port master0 master0_arvalid arvalid Output 1
add_interface_port master0 master0_awaddr awaddr Output 64
add_interface_port master0 master0_awburst awburst Output 2
add_interface_port master0 master0_awcache awcache Output 4
add_interface_port master0 master0_awid awid Output 5
add_interface_port master0 master0_awlen awlen Output 8
add_interface_port master0 master0_awlock awlock Output 1
add_interface_port master0 master0_awprot awprot Output 3
add_interface_port master0 master0_awqos awqos Output 4
add_interface_port master0 master0_awready awready Input 1
add_interface_port master0 master0_awregion awregion Output 4
add_interface_port master0 master0_awsize awsize Output 3
add_interface_port master0 master0_awvalid awvalid Output 1
add_interface_port master0 master0_bid bid Input 5
add_interface_port master0 master0_bready bready Output 1
add_interface_port master0 master0_bresp bresp Input 2
add_interface_port master0 master0_bvalid bvalid Input 1
add_interface_port master0 master0_rdata rdata Input 64
add_interface_port master0 master0_rid rid Input 5
add_interface_port master0 master0_rlast rlast Input 1
add_interface_port master0 master0_rready rready Output 1
add_interface_port master0 master0_rresp rresp Input 2
add_interface_port master0 master0_rvalid rvalid Input 1
add_interface_port master0 master0_wdata wdata Output 64
add_interface_port master0 master0_wlast wlast Output 1
add_interface_port master0 master0_wready wready Input 1
add_interface_port master0 master0_wstrb wstrb Output 8
add_interface_port master0 master0_wvalid wvalid Output 1


# 
# connection point master1
# 
add_interface master1 axi4 start
set_interface_property master1 associatedClock clock
set_interface_property master1 associatedReset reset_sink
set_interface_property master1 readIssuingCapability 1
set_interface_property master1 writeIssuingCapability 1
set_interface_property master1 combinedIssuingCapability 1
set_interface_property master1 ENABLED true
set_interface_property master1 EXPORT_OF ""
set_interface_property master1 PORT_NAME_MAP ""
set_interface_property master1 CMSIS_SVD_VARIABLES ""
set_interface_property master1 SVD_ADDRESS_GROUP ""

add_interface_port master1 master1_araddr araddr Output 64
add_interface_port master1 master1_arburst arburst Output 2
add_interface_port master1 master1_arcache arcache Output 4
add_interface_port master1 master1_arid arid Output 6
add_interface_port master1 master1_arlen arlen Output 8
add_interface_port master1 master1_arlock arlock Output 1
add_interface_port master1 master1_arprot arprot Output 3
add_interface_port master1 master1_arqos arqos Output 4
add_interface_port master1 master1_arready arready Input 1
add_interface_port master1 master1_arregion arregion Output 4
add_interface_port master1 master1_arsize arsize Output 3
add_interface_port master1 master1_arvalid awvalid Output 1
add_interface_port master1 master1_awaddr awaddr Output 64
add_interface_port master1 master1_awburst awburst Output 2
add_interface_port master1 master1_awcache awcache Output 4
add_interface_port master1 master1_awid awid Output 6
add_interface_port master1 master1_awlen awlen Output 8
add_interface_port master1 master1_awlock awlock Output 1
add_interface_port master1 master1_awprot awprot Output 3
add_interface_port master1 master1_awqos awqos Output 4
add_interface_port master1 master1_awready awready Input 1
add_interface_port master1 master1_awregion awregion Output 4
add_interface_port master1 master1_awsize awsize Output 3
add_interface_port master1 master1_awvalid arvalid Output 1
add_interface_port master1 master1_bid bid Input 6
add_interface_port master1 master1_bready bready Output 1
add_interface_port master1 master1_bresp bresp Input 2
add_interface_port master1 master1_bvalid bvalid Input 1
add_interface_port master1 master1_rdata rdata Input 64
add_interface_port master1 master1_rid rid Input 6
add_interface_port master1 master1_rlast rlast Input 1
add_interface_port master1 master1_rready rready Output 1
add_interface_port master1 master1_rresp rresp Input 2
add_interface_port master1 master1_rvalid rvalid Input 1
add_interface_port master1 master1_wdata wdata Output 64
add_interface_port master1 master1_wlast wlast Output 1
add_interface_port master1 master1_wready wready Input 1
add_interface_port master1 master1_wstrb wstrb Output 8
add_interface_port master1 master1_wvalid wvalid Output 1

