/*
 * Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
 * 
 * On Tue Mar  8 15:41:57 GMT 2022
 * 
 */
#include "bluesim_primitives.h"
#include "mkDebug_Module.h"


/* Literal declarations */
static unsigned int const UWide_literal_77_haaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
									  2863311530u,
									  2730u };
static tUWide const UWide_literal_77_haaaaaaaaaaaaaaaaaaa(77u,
							  UWide_literal_77_haaaaaaaaaaaaaaaaaaa_arr);
static unsigned int const UWide_literal_70_h2aaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
									 2863311530u,
									 42u };
static tUWide const UWide_literal_70_h2aaaaaaaaaaaaaaaaa(70u,
							 UWide_literal_70_h2aaaaaaaaaaaaaaaaa_arr);


/* String declarations */
static std::string const __str_literal_1("%0d: Debug_Module reset", 23u);


/* Constructor */
MOD_mkDebug_Module::MOD_mkDebug_Module(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_dm_abstract_commands(simHdl, "dm_abstract_commands", this),
    INST_dm_run_control(simHdl, "dm_run_control", this),
    INST_dm_system_bus(simHdl, "dm_system_bus", this),
    INST_f_read_addr(simHdl, "f_read_addr", this, 7u, 1u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h502(2863311530u)
{
  PORT_hart0_gpr_mem_client_response_put.setSize(65u);
  PORT_hart0_gpr_mem_client_response_put.clear();
  PORT_hart0_fpr_mem_client_response_put.setSize(65u);
  PORT_hart0_fpr_mem_client_response_put.clear();
  PORT_hart0_csr_mem_client_response_put.setSize(65u);
  PORT_hart0_csr_mem_client_response_put.clear();
  PORT_master_r_put_val.setSize(72u);
  PORT_master_r_put_val.clear();
  PORT_hart0_gpr_mem_client_request_get.setSize(70u);
  PORT_hart0_gpr_mem_client_request_get.clear();
  PORT_hart0_fpr_mem_client_request_get.setSize(70u);
  PORT_hart0_fpr_mem_client_request_get.clear();
  PORT_hart0_csr_mem_client_request_get.setSize(77u);
  PORT_hart0_csr_mem_client_request_get.clear();
  PORT_master_aw_peek.setSize(97u);
  PORT_master_aw_peek.clear();
  PORT_master_w_peek.setSize(74u);
  PORT_master_w_peek.clear();
  PORT_master_ar_peek.setSize(97u);
  PORT_master_ar_peek.clear();
  symbol_count = 16u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkDebug_Module::init_symbols_0()
{
  init_symbol(&symbols[0u], "dm_abstract_commands", SYM_MODULE, &INST_dm_abstract_commands);
  init_symbol(&symbols[1u], "dm_addr__h701", SYM_DEF, &DEF_dm_addr__h701, 7u);
  init_symbol(&symbols[2u], "dm_run_control", SYM_MODULE, &INST_dm_run_control);
  init_symbol(&symbols[3u], "dm_system_bus", SYM_MODULE, &INST_dm_system_bus);
  init_symbol(&symbols[4u], "f_read_addr", SYM_MODULE, &INST_f_read_addr);
  init_symbol(&symbols[5u],
	      "hart0_csr_mem_client_request_get",
	      SYM_PORT,
	      &PORT_hart0_csr_mem_client_request_get,
	      77u);
  init_symbol(&symbols[6u],
	      "hart0_csr_mem_client_response_put",
	      SYM_PORT,
	      &PORT_hart0_csr_mem_client_response_put,
	      65u);
  init_symbol(&symbols[7u],
	      "hart0_fpr_mem_client_request_get",
	      SYM_PORT,
	      &PORT_hart0_fpr_mem_client_request_get,
	      70u);
  init_symbol(&symbols[8u],
	      "hart0_fpr_mem_client_response_put",
	      SYM_PORT,
	      &PORT_hart0_fpr_mem_client_response_put,
	      65u);
  init_symbol(&symbols[9u],
	      "hart0_gpr_mem_client_request_get",
	      SYM_PORT,
	      &PORT_hart0_gpr_mem_client_request_get,
	      70u);
  init_symbol(&symbols[10u],
	      "hart0_gpr_mem_client_response_put",
	      SYM_PORT,
	      &PORT_hart0_gpr_mem_client_response_put,
	      65u);
  init_symbol(&symbols[11u], "master_ar_peek", SYM_PORT, &PORT_master_ar_peek, 97u);
  init_symbol(&symbols[12u], "master_aw_peek", SYM_PORT, &PORT_master_aw_peek, 97u);
  init_symbol(&symbols[13u], "master_r_put_val", SYM_PORT, &PORT_master_r_put_val, 72u);
  init_symbol(&symbols[14u], "master_w_peek", SYM_PORT, &PORT_master_w_peek, 74u);
  init_symbol(&symbols[15u], "RL_rl_reset", SYM_RULE);
}


/* Rule actions */

void MOD_mkDebug_Module::RL_rl_reset()
{
  tUInt32 DEF_v__h496;
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h502 = dollar_stime(sim_hdl);
  DEF_v__h496 = DEF_v__h502 / 10u;
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,32", &__str_literal_1, DEF_v__h496);
  INST_dm_run_control.METH_reset();
  INST_dm_system_bus.METH_reset();
  INST_dm_abstract_commands.METH_reset();
}


/* Methods */

void MOD_mkDebug_Module::METH_dmi_read_addr(tUInt8 ARG_dmi_read_addr_dm_addr)
{
  INST_f_read_addr.METH_enq(ARG_dmi_read_addr_dm_addr);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_dmi_read_addr()
{
  tUInt8 DEF_CAN_FIRE_dmi_read_addr;
  tUInt8 PORT_RDY_dmi_read_addr;
  DEF_dm_run_control_dmactive____d1 = INST_dm_run_control.METH_dmactive();
  DEF_CAN_FIRE_dmi_read_addr = DEF_dm_run_control_dmactive____d1 && INST_f_read_addr.METH_i_notFull();
  PORT_RDY_dmi_read_addr = DEF_CAN_FIRE_dmi_read_addr;
  return PORT_RDY_dmi_read_addr;
}

tUInt32 MOD_mkDebug_Module::METH_dmi_read_data()
{
  tUInt8 DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d124;
  tUInt8 DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d48;
  tUInt8 DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d78;
  tUInt32 DEF_v__h793;
  tUInt32 DEF_v__h899;
  tUInt32 DEF_v__h965;
  tUInt32 PORT_dmi_read_data;
  tUInt32 DEF_AVMeth_dm_system_bus_av_read;
  tUInt32 DEF_AVMeth_dm_abstract_commands_av_read;
  tUInt32 DEF_AVMeth_dm_run_control_av_read;
  DEF_dm_addr__h701 = INST_f_read_addr.METH_first();
  DEF_f_read_addr_first_EQ_0x60___d26 = DEF_dm_addr__h701 == (tUInt8)96u;
  DEF_f_read_addr_first_EQ_0x5F___d24 = DEF_dm_addr__h701 == (tUInt8)95u;
  DEF_f_read_addr_first_EQ_0x40___d22 = DEF_dm_addr__h701 == (tUInt8)64u;
  DEF_f_read_addr_first_EQ_0x3F___d121 = DEF_dm_addr__h701 == (tUInt8)63u;
  DEF_f_read_addr_first_EQ_0x3D___d117 = DEF_dm_addr__h701 == (tUInt8)61u;
  DEF_f_read_addr_first_EQ_0x3E___d119 = DEF_dm_addr__h701 == (tUInt8)62u;
  DEF_f_read_addr_first_EQ_0x3C___d115 = DEF_dm_addr__h701 == (tUInt8)60u;
  DEF_f_read_addr_first_EQ_0x3B___d113 = DEF_dm_addr__h701 == (tUInt8)59u;
  DEF_f_read_addr_first_EQ_0x3A___d111 = DEF_dm_addr__h701 == (tUInt8)58u;
  DEF_f_read_addr_first_EQ_0x20___d76 = DEF_dm_addr__h701 == (tUInt8)32u;
  DEF_f_read_addr_first_EQ_0x39___d109 = DEF_dm_addr__h701 == (tUInt8)57u;
  DEF_f_read_addr_first_EQ_0x38___d108 = DEF_dm_addr__h701 == (tUInt8)56u;
  DEF_f_read_addr_first_EQ_0x30___d20 = DEF_dm_addr__h701 == (tUInt8)48u;
  DEF_f_read_addr_first_EQ_0x19___d18 = DEF_dm_addr__h701 == (tUInt8)25u;
  DEF_f_read_addr_first_EQ_0x18___d74 = DEF_dm_addr__h701 == (tUInt8)24u;
  DEF_f_read_addr_first_EQ_0x17___d50 = DEF_dm_addr__h701 == (tUInt8)23u;
  DEF_f_read_addr_first_EQ_0x15___d16 = DEF_dm_addr__h701 == (tUInt8)21u;
  DEF_f_read_addr_first_EQ_0x16___d49 = DEF_dm_addr__h701 == (tUInt8)22u;
  DEF_f_read_addr_first_EQ_0x14___d14 = DEF_dm_addr__h701 == (tUInt8)20u;
  DEF_f_read_addr_first_EQ_0x13___d12 = DEF_dm_addr__h701 == (tUInt8)19u;
  DEF_f_read_addr_first_EQ_0x12___d10 = DEF_dm_addr__h701 == (tUInt8)18u;
  DEF_f_read_addr_first_EQ_0x11___d8 = DEF_dm_addr__h701 == (tUInt8)17u;
  DEF_f_read_addr_first_EQ_0xF___d72 = DEF_dm_addr__h701 == (tUInt8)15u;
  DEF_f_read_addr_first_EQ_0x10___d7 = DEF_dm_addr__h701 == (tUInt8)16u;
  DEF_f_read_addr_first_EQ_0xD___d70 = DEF_dm_addr__h701 == (tUInt8)13u;
  DEF_f_read_addr_first_EQ_0xC___d68 = DEF_dm_addr__h701 == (tUInt8)12u;
  DEF_f_read_addr_first_EQ_0xB___d66 = DEF_dm_addr__h701 == (tUInt8)11u;
  DEF_f_read_addr_first_EQ_0xA___d64 = DEF_dm_addr__h701 == (tUInt8)10u;
  DEF_f_read_addr_first_EQ_0x8___d60 = DEF_dm_addr__h701 == (tUInt8)8u;
  DEF_f_read_addr_first_EQ_0x9___d62 = DEF_dm_addr__h701 == (tUInt8)9u;
  DEF_f_read_addr_first_EQ_0x7___d58 = DEF_dm_addr__h701 == (tUInt8)7u;
  DEF_f_read_addr_first_EQ_0x6___d56 = DEF_dm_addr__h701 == (tUInt8)6u;
  DEF_f_read_addr_first_EQ_0x5___d54 = DEF_dm_addr__h701 == (tUInt8)5u;
  DEF_f_read_addr_first_EQ_0x4___d52 = DEF_dm_addr__h701 == (tUInt8)4u;
  DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77 = (((((((((((((DEF_f_read_addr_first_EQ_0x16___d49 || DEF_f_read_addr_first_EQ_0x17___d50) || DEF_f_read_addr_first_EQ_0x4___d52) || DEF_f_read_addr_first_EQ_0x5___d54) || DEF_f_read_addr_first_EQ_0x6___d56) || DEF_f_read_addr_first_EQ_0x7___d58) || DEF_f_read_addr_first_EQ_0x8___d60) || DEF_f_read_addr_first_EQ_0x9___d62) || DEF_f_read_addr_first_EQ_0xA___d64) || DEF_f_read_addr_first_EQ_0xB___d66) || DEF_f_read_addr_first_EQ_0xC___d68) || DEF_f_read_addr_first_EQ_0xD___d70) || DEF_f_read_addr_first_EQ_0xF___d72) || DEF_f_read_addr_first_EQ_0x18___d74) || DEF_f_read_addr_first_EQ_0x20___d76;
  DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27 = (((((((((DEF_f_read_addr_first_EQ_0x10___d7 || DEF_f_read_addr_first_EQ_0x11___d8) || DEF_f_read_addr_first_EQ_0x12___d10) || DEF_f_read_addr_first_EQ_0x13___d12) || DEF_f_read_addr_first_EQ_0x14___d14) || DEF_f_read_addr_first_EQ_0x15___d16) || DEF_f_read_addr_first_EQ_0x19___d18) || DEF_f_read_addr_first_EQ_0x30___d20) || DEF_f_read_addr_first_EQ_0x40___d22) || DEF_f_read_addr_first_EQ_0x5F___d24) || DEF_f_read_addr_first_EQ_0x60___d26;
  DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d48 = (((((((((!DEF_f_read_addr_first_EQ_0x10___d7 && !DEF_f_read_addr_first_EQ_0x11___d8) && !DEF_f_read_addr_first_EQ_0x12___d10) && !DEF_f_read_addr_first_EQ_0x13___d12) && !DEF_f_read_addr_first_EQ_0x14___d14) && !DEF_f_read_addr_first_EQ_0x15___d16) && !DEF_f_read_addr_first_EQ_0x19___d18) && !DEF_f_read_addr_first_EQ_0x30___d20) && !DEF_f_read_addr_first_EQ_0x40___d22) && !DEF_f_read_addr_first_EQ_0x5F___d24) && !DEF_f_read_addr_first_EQ_0x60___d26;
  DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d78 = DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d48 && DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77;
  DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d124 = DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d48 && (((((((((((((((!DEF_f_read_addr_first_EQ_0x16___d49 && !DEF_f_read_addr_first_EQ_0x17___d50) && !DEF_f_read_addr_first_EQ_0x4___d52) && !DEF_f_read_addr_first_EQ_0x5___d54) && !DEF_f_read_addr_first_EQ_0x6___d56) && !DEF_f_read_addr_first_EQ_0x7___d58) && !DEF_f_read_addr_first_EQ_0x8___d60) && !DEF_f_read_addr_first_EQ_0x9___d62) && !DEF_f_read_addr_first_EQ_0xA___d64) && !DEF_f_read_addr_first_EQ_0xB___d66) && !DEF_f_read_addr_first_EQ_0xC___d68) && !DEF_f_read_addr_first_EQ_0xD___d70) && !DEF_f_read_addr_first_EQ_0xF___d72) && !DEF_f_read_addr_first_EQ_0x18___d74) && !DEF_f_read_addr_first_EQ_0x20___d76) && (((((((DEF_f_read_addr_first_EQ_0x38___d108 || DEF_f_read_addr_first_EQ_0x39___d109) || DEF_f_read_addr_first_EQ_0x3A___d111) || DEF_f_read_addr_first_EQ_0x3B___d113) || DEF_f_read_addr_first_EQ_0x3C___d115) || DEF_f_read_addr_first_EQ_0x3D___d117) || DEF_f_read_addr_first_EQ_0x3E___d119) || DEF_f_read_addr_first_EQ_0x3F___d121));
  INST_f_read_addr.METH_deq();
  if (DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27)
    DEF_AVMeth_dm_run_control_av_read = INST_dm_run_control.METH_av_read(DEF_dm_addr__h701);
  else
    DEF_AVMeth_dm_run_control_av_read = 2863311530u;
  DEF_v__h793 = DEF_AVMeth_dm_run_control_av_read;
  if (DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d78)
    DEF_AVMeth_dm_abstract_commands_av_read = INST_dm_abstract_commands.METH_av_read(DEF_dm_addr__h701);
  else
    DEF_AVMeth_dm_abstract_commands_av_read = 2863311530u;
  DEF_v__h899 = DEF_AVMeth_dm_abstract_commands_av_read;
  if (DEF_NOT_f_read_addr_first_EQ_0x10_8_AND_NOT_f_read_ETC___d124)
    DEF_AVMeth_dm_system_bus_av_read = INST_dm_system_bus.METH_av_read(DEF_dm_addr__h701);
  else
    DEF_AVMeth_dm_system_bus_av_read = 2863311530u;
  DEF_v__h965 = DEF_AVMeth_dm_system_bus_av_read;
  switch (DEF_dm_addr__h701) {
  case (tUInt8)16u:
  case (tUInt8)17u:
  case (tUInt8)18u:
  case (tUInt8)19u:
  case (tUInt8)20u:
  case (tUInt8)21u:
  case (tUInt8)25u:
  case (tUInt8)48u:
  case (tUInt8)64u:
  case (tUInt8)95u:
  case (tUInt8)96u:
    PORT_dmi_read_data = DEF_v__h793;
    break;
  case (tUInt8)4u:
  case (tUInt8)5u:
  case (tUInt8)6u:
  case (tUInt8)7u:
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)10u:
  case (tUInt8)11u:
  case (tUInt8)12u:
  case (tUInt8)13u:
  case (tUInt8)15u:
  case (tUInt8)22u:
  case (tUInt8)23u:
  case (tUInt8)24u:
  case (tUInt8)32u:
    PORT_dmi_read_data = DEF_v__h899;
    break;
  case (tUInt8)56u:
  case (tUInt8)57u:
  case (tUInt8)58u:
  case (tUInt8)59u:
  case (tUInt8)60u:
  case (tUInt8)61u:
  case (tUInt8)62u:
  case (tUInt8)63u:
    PORT_dmi_read_data = DEF_v__h965;
    break;
  default:
    PORT_dmi_read_data = 0u;
  }
  return PORT_dmi_read_data;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_dmi_read_data()
{
  tUInt8 DEF_CAN_FIRE_dmi_read_data;
  tUInt8 PORT_RDY_dmi_read_data;
  DEF_dm_addr__h701 = INST_f_read_addr.METH_first();
  DEF_f_read_addr_first_EQ_0x60___d26 = DEF_dm_addr__h701 == (tUInt8)96u;
  DEF_f_read_addr_first_EQ_0x5F___d24 = DEF_dm_addr__h701 == (tUInt8)95u;
  DEF_f_read_addr_first_EQ_0x40___d22 = DEF_dm_addr__h701 == (tUInt8)64u;
  DEF_f_read_addr_first_EQ_0x3F___d121 = DEF_dm_addr__h701 == (tUInt8)63u;
  DEF_f_read_addr_first_EQ_0x3E___d119 = DEF_dm_addr__h701 == (tUInt8)62u;
  DEF_f_read_addr_first_EQ_0x3D___d117 = DEF_dm_addr__h701 == (tUInt8)61u;
  DEF_f_read_addr_first_EQ_0x3C___d115 = DEF_dm_addr__h701 == (tUInt8)60u;
  DEF_f_read_addr_first_EQ_0x3B___d113 = DEF_dm_addr__h701 == (tUInt8)59u;
  DEF_f_read_addr_first_EQ_0x3A___d111 = DEF_dm_addr__h701 == (tUInt8)58u;
  DEF_f_read_addr_first_EQ_0x39___d109 = DEF_dm_addr__h701 == (tUInt8)57u;
  DEF_f_read_addr_first_EQ_0x38___d108 = DEF_dm_addr__h701 == (tUInt8)56u;
  DEF_f_read_addr_first_EQ_0x30___d20 = DEF_dm_addr__h701 == (tUInt8)48u;
  DEF_f_read_addr_first_EQ_0x20___d76 = DEF_dm_addr__h701 == (tUInt8)32u;
  DEF_f_read_addr_first_EQ_0x19___d18 = DEF_dm_addr__h701 == (tUInt8)25u;
  DEF_f_read_addr_first_EQ_0x18___d74 = DEF_dm_addr__h701 == (tUInt8)24u;
  DEF_f_read_addr_first_EQ_0x17___d50 = DEF_dm_addr__h701 == (tUInt8)23u;
  DEF_f_read_addr_first_EQ_0x16___d49 = DEF_dm_addr__h701 == (tUInt8)22u;
  DEF_f_read_addr_first_EQ_0x15___d16 = DEF_dm_addr__h701 == (tUInt8)21u;
  DEF_f_read_addr_first_EQ_0x14___d14 = DEF_dm_addr__h701 == (tUInt8)20u;
  DEF_f_read_addr_first_EQ_0x13___d12 = DEF_dm_addr__h701 == (tUInt8)19u;
  DEF_f_read_addr_first_EQ_0x12___d10 = DEF_dm_addr__h701 == (tUInt8)18u;
  DEF_f_read_addr_first_EQ_0x11___d8 = DEF_dm_addr__h701 == (tUInt8)17u;
  DEF_f_read_addr_first_EQ_0x10___d7 = DEF_dm_addr__h701 == (tUInt8)16u;
  DEF_f_read_addr_first_EQ_0xF___d72 = DEF_dm_addr__h701 == (tUInt8)15u;
  DEF_f_read_addr_first_EQ_0xD___d70 = DEF_dm_addr__h701 == (tUInt8)13u;
  DEF_f_read_addr_first_EQ_0xC___d68 = DEF_dm_addr__h701 == (tUInt8)12u;
  DEF_f_read_addr_first_EQ_0xB___d66 = DEF_dm_addr__h701 == (tUInt8)11u;
  DEF_f_read_addr_first_EQ_0xA___d64 = DEF_dm_addr__h701 == (tUInt8)10u;
  DEF_f_read_addr_first_EQ_0x9___d62 = DEF_dm_addr__h701 == (tUInt8)9u;
  DEF_f_read_addr_first_EQ_0x8___d60 = DEF_dm_addr__h701 == (tUInt8)8u;
  DEF_f_read_addr_first_EQ_0x7___d58 = DEF_dm_addr__h701 == (tUInt8)7u;
  DEF_f_read_addr_first_EQ_0x6___d56 = DEF_dm_addr__h701 == (tUInt8)6u;
  DEF_f_read_addr_first_EQ_0x5___d54 = DEF_dm_addr__h701 == (tUInt8)5u;
  DEF_f_read_addr_first_EQ_0x4___d52 = DEF_dm_addr__h701 == (tUInt8)4u;
  DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77 = (((((((((((((DEF_f_read_addr_first_EQ_0x16___d49 || DEF_f_read_addr_first_EQ_0x17___d50) || DEF_f_read_addr_first_EQ_0x4___d52) || DEF_f_read_addr_first_EQ_0x5___d54) || DEF_f_read_addr_first_EQ_0x6___d56) || DEF_f_read_addr_first_EQ_0x7___d58) || DEF_f_read_addr_first_EQ_0x8___d60) || DEF_f_read_addr_first_EQ_0x9___d62) || DEF_f_read_addr_first_EQ_0xA___d64) || DEF_f_read_addr_first_EQ_0xB___d66) || DEF_f_read_addr_first_EQ_0xC___d68) || DEF_f_read_addr_first_EQ_0xD___d70) || DEF_f_read_addr_first_EQ_0xF___d72) || DEF_f_read_addr_first_EQ_0x18___d74) || DEF_f_read_addr_first_EQ_0x20___d76;
  DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27 = (((((((((DEF_f_read_addr_first_EQ_0x10___d7 || DEF_f_read_addr_first_EQ_0x11___d8) || DEF_f_read_addr_first_EQ_0x12___d10) || DEF_f_read_addr_first_EQ_0x13___d12) || DEF_f_read_addr_first_EQ_0x14___d14) || DEF_f_read_addr_first_EQ_0x15___d16) || DEF_f_read_addr_first_EQ_0x19___d18) || DEF_f_read_addr_first_EQ_0x30___d20) || DEF_f_read_addr_first_EQ_0x40___d22) || DEF_f_read_addr_first_EQ_0x5F___d24) || DEF_f_read_addr_first_EQ_0x60___d26;
  DEF_CAN_FIRE_dmi_read_data = INST_f_read_addr.METH_i_notEmpty() && (DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27 || (DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77 || ((((((((!DEF_f_read_addr_first_EQ_0x38___d108 && !DEF_f_read_addr_first_EQ_0x39___d109) && !DEF_f_read_addr_first_EQ_0x3A___d111) && !DEF_f_read_addr_first_EQ_0x3B___d113) && !DEF_f_read_addr_first_EQ_0x3C___d115) && !DEF_f_read_addr_first_EQ_0x3D___d117) && !DEF_f_read_addr_first_EQ_0x3E___d119) && !DEF_f_read_addr_first_EQ_0x3F___d121) || INST_dm_system_bus.METH_RDY_av_read())));
  PORT_RDY_dmi_read_data = DEF_CAN_FIRE_dmi_read_data;
  return PORT_RDY_dmi_read_data;
}

void MOD_mkDebug_Module::METH_dmi_write(tUInt8 ARG_dmi_write_dm_addr, tUInt32 ARG_dmi_write_dm_word)
{
  tUInt8 DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d267;
  tUInt8 DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d191;
  tUInt8 DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d221;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x10_50_OR_dmi_write_dm_a_ETC___d170;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x4___d195;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x5___d197;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x6___d199;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x7___d201;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x8___d203;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x9___d205;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0xA___d207;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0xB___d209;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0xC___d211;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0xD___d213;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0xF___d215;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x10___d150;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x11___d151;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x12___d153;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x13___d155;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x14___d157;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x15___d159;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x16___d192;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x17___d193;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x18___d217;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x19___d161;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x20___d219;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x30___d163;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x40___d165;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x5F___d167;
  tUInt8 DEF_dmi_write_dm_addr_EQ_0x60___d169;
  DEF_dmi_write_dm_addr_EQ_0x60___d169 = ARG_dmi_write_dm_addr == (tUInt8)96u;
  DEF_dmi_write_dm_addr_EQ_0x5F___d167 = ARG_dmi_write_dm_addr == (tUInt8)95u;
  DEF_dmi_write_dm_addr_EQ_0x40___d165 = ARG_dmi_write_dm_addr == (tUInt8)64u;
  DEF_dmi_write_dm_addr_EQ_0x30___d163 = ARG_dmi_write_dm_addr == (tUInt8)48u;
  DEF_dmi_write_dm_addr_EQ_0x20___d219 = ARG_dmi_write_dm_addr == (tUInt8)32u;
  DEF_dmi_write_dm_addr_EQ_0x19___d161 = ARG_dmi_write_dm_addr == (tUInt8)25u;
  DEF_dmi_write_dm_addr_EQ_0x18___d217 = ARG_dmi_write_dm_addr == (tUInt8)24u;
  DEF_dmi_write_dm_addr_EQ_0x17___d193 = ARG_dmi_write_dm_addr == (tUInt8)23u;
  DEF_dmi_write_dm_addr_EQ_0x16___d192 = ARG_dmi_write_dm_addr == (tUInt8)22u;
  DEF_dmi_write_dm_addr_EQ_0x15___d159 = ARG_dmi_write_dm_addr == (tUInt8)21u;
  DEF_dmi_write_dm_addr_EQ_0x14___d157 = ARG_dmi_write_dm_addr == (tUInt8)20u;
  DEF_dmi_write_dm_addr_EQ_0x13___d155 = ARG_dmi_write_dm_addr == (tUInt8)19u;
  DEF_dmi_write_dm_addr_EQ_0x12___d153 = ARG_dmi_write_dm_addr == (tUInt8)18u;
  DEF_dmi_write_dm_addr_EQ_0x11___d151 = ARG_dmi_write_dm_addr == (tUInt8)17u;
  DEF_dmi_write_dm_addr_EQ_0x10___d150 = ARG_dmi_write_dm_addr == (tUInt8)16u;
  DEF_dmi_write_dm_addr_EQ_0xF___d215 = ARG_dmi_write_dm_addr == (tUInt8)15u;
  DEF_dmi_write_dm_addr_EQ_0xD___d213 = ARG_dmi_write_dm_addr == (tUInt8)13u;
  DEF_dmi_write_dm_addr_EQ_0xC___d211 = ARG_dmi_write_dm_addr == (tUInt8)12u;
  DEF_dmi_write_dm_addr_EQ_0xB___d209 = ARG_dmi_write_dm_addr == (tUInt8)11u;
  DEF_dmi_write_dm_addr_EQ_0xA___d207 = ARG_dmi_write_dm_addr == (tUInt8)10u;
  DEF_dmi_write_dm_addr_EQ_0x9___d205 = ARG_dmi_write_dm_addr == (tUInt8)9u;
  DEF_dmi_write_dm_addr_EQ_0x8___d203 = ARG_dmi_write_dm_addr == (tUInt8)8u;
  DEF_dmi_write_dm_addr_EQ_0x6___d199 = ARG_dmi_write_dm_addr == (tUInt8)6u;
  DEF_dmi_write_dm_addr_EQ_0x7___d201 = ARG_dmi_write_dm_addr == (tUInt8)7u;
  DEF_dmi_write_dm_addr_EQ_0x5___d197 = ARG_dmi_write_dm_addr == (tUInt8)5u;
  DEF_dmi_write_dm_addr_EQ_0x4___d195 = ARG_dmi_write_dm_addr == (tUInt8)4u;
  DEF_dmi_write_dm_addr_EQ_0x10_50_OR_dmi_write_dm_a_ETC___d170 = (((((((((DEF_dmi_write_dm_addr_EQ_0x10___d150 || DEF_dmi_write_dm_addr_EQ_0x11___d151) || DEF_dmi_write_dm_addr_EQ_0x12___d153) || DEF_dmi_write_dm_addr_EQ_0x13___d155) || DEF_dmi_write_dm_addr_EQ_0x14___d157) || DEF_dmi_write_dm_addr_EQ_0x15___d159) || DEF_dmi_write_dm_addr_EQ_0x19___d161) || DEF_dmi_write_dm_addr_EQ_0x30___d163) || DEF_dmi_write_dm_addr_EQ_0x40___d165) || DEF_dmi_write_dm_addr_EQ_0x5F___d167) || DEF_dmi_write_dm_addr_EQ_0x60___d169;
  DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d191 = (((((((((!DEF_dmi_write_dm_addr_EQ_0x10___d150 && !DEF_dmi_write_dm_addr_EQ_0x11___d151) && !DEF_dmi_write_dm_addr_EQ_0x12___d153) && !DEF_dmi_write_dm_addr_EQ_0x13___d155) && !DEF_dmi_write_dm_addr_EQ_0x14___d157) && !DEF_dmi_write_dm_addr_EQ_0x15___d159) && !DEF_dmi_write_dm_addr_EQ_0x19___d161) && !DEF_dmi_write_dm_addr_EQ_0x30___d163) && !DEF_dmi_write_dm_addr_EQ_0x40___d165) && !DEF_dmi_write_dm_addr_EQ_0x5F___d167) && !DEF_dmi_write_dm_addr_EQ_0x60___d169;
  DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d221 = DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d191 && ((((((((((((((DEF_dmi_write_dm_addr_EQ_0x16___d192 || DEF_dmi_write_dm_addr_EQ_0x17___d193) || DEF_dmi_write_dm_addr_EQ_0x4___d195) || DEF_dmi_write_dm_addr_EQ_0x5___d197) || DEF_dmi_write_dm_addr_EQ_0x6___d199) || DEF_dmi_write_dm_addr_EQ_0x7___d201) || DEF_dmi_write_dm_addr_EQ_0x8___d203) || DEF_dmi_write_dm_addr_EQ_0x9___d205) || DEF_dmi_write_dm_addr_EQ_0xA___d207) || DEF_dmi_write_dm_addr_EQ_0xB___d209) || DEF_dmi_write_dm_addr_EQ_0xC___d211) || DEF_dmi_write_dm_addr_EQ_0xD___d213) || DEF_dmi_write_dm_addr_EQ_0xF___d215) || DEF_dmi_write_dm_addr_EQ_0x18___d217) || DEF_dmi_write_dm_addr_EQ_0x20___d219);
  DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d267 = DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d191 && (((((((((((((((!DEF_dmi_write_dm_addr_EQ_0x16___d192 && !DEF_dmi_write_dm_addr_EQ_0x17___d193) && !DEF_dmi_write_dm_addr_EQ_0x4___d195) && !DEF_dmi_write_dm_addr_EQ_0x5___d197) && !DEF_dmi_write_dm_addr_EQ_0x6___d199) && !DEF_dmi_write_dm_addr_EQ_0x7___d201) && !DEF_dmi_write_dm_addr_EQ_0x8___d203) && !DEF_dmi_write_dm_addr_EQ_0x9___d205) && !DEF_dmi_write_dm_addr_EQ_0xA___d207) && !DEF_dmi_write_dm_addr_EQ_0xB___d209) && !DEF_dmi_write_dm_addr_EQ_0xC___d211) && !DEF_dmi_write_dm_addr_EQ_0xD___d213) && !DEF_dmi_write_dm_addr_EQ_0xF___d215) && !DEF_dmi_write_dm_addr_EQ_0x18___d217) && !DEF_dmi_write_dm_addr_EQ_0x20___d219) && (((((((ARG_dmi_write_dm_addr == (tUInt8)56u || ARG_dmi_write_dm_addr == (tUInt8)57u) || ARG_dmi_write_dm_addr == (tUInt8)58u) || ARG_dmi_write_dm_addr == (tUInt8)59u) || ARG_dmi_write_dm_addr == (tUInt8)60u) || ARG_dmi_write_dm_addr == (tUInt8)61u) || ARG_dmi_write_dm_addr == (tUInt8)62u) || ARG_dmi_write_dm_addr == (tUInt8)63u));
  if (DEF_dmi_write_dm_addr_EQ_0x10_50_OR_dmi_write_dm_a_ETC___d170)
    INST_dm_run_control.METH_write(ARG_dmi_write_dm_addr, ARG_dmi_write_dm_word);
  if (DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d221)
    INST_dm_abstract_commands.METH_write(ARG_dmi_write_dm_addr, ARG_dmi_write_dm_word);
  if (DEF_NOT_dmi_write_dm_addr_EQ_0x10_50_71_AND_NOT_dm_ETC___d267)
    INST_dm_system_bus.METH_write(ARG_dmi_write_dm_addr, ARG_dmi_write_dm_word);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_dmi_write()
{
  tUInt8 DEF_CAN_FIRE_dmi_write;
  tUInt8 PORT_RDY_dmi_write;
  DEF_dm_run_control_dmactive____d1 = INST_dm_run_control.METH_dmactive();
  DEF_CAN_FIRE_dmi_write = DEF_dm_run_control_dmactive____d1 && (INST_dm_run_control.METH_RDY_write() && INST_dm_system_bus.METH_RDY_write());
  PORT_RDY_dmi_write = DEF_CAN_FIRE_dmi_write;
  return PORT_RDY_dmi_write;
}

tUInt8 MOD_mkDebug_Module::METH_hart0_reset_client_request_get()
{
  tUInt8 PORT_hart0_reset_client_request_get;
  tUInt8 DEF_AVMeth_dm_run_control_hart0_reset_client_request_get;
  DEF_AVMeth_dm_run_control_hart0_reset_client_request_get = INST_dm_run_control.METH_hart0_reset_client_request_get();
  PORT_hart0_reset_client_request_get = DEF_AVMeth_dm_run_control_hart0_reset_client_request_get;
  return PORT_hart0_reset_client_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_reset_client_request_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_reset_client_request_get;
  tUInt8 PORT_RDY_hart0_reset_client_request_get;
  DEF_CAN_FIRE_hart0_reset_client_request_get = INST_dm_run_control.METH_RDY_hart0_reset_client_request_get();
  PORT_RDY_hart0_reset_client_request_get = DEF_CAN_FIRE_hart0_reset_client_request_get;
  return PORT_RDY_hart0_reset_client_request_get;
}

void MOD_mkDebug_Module::METH_hart0_reset_client_response_put(tUInt8 ARG_hart0_reset_client_response_put)
{
  INST_dm_run_control.METH_hart0_reset_client_response_put(ARG_hart0_reset_client_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_reset_client_response_put()
{
  tUInt8 DEF_CAN_FIRE_hart0_reset_client_response_put;
  tUInt8 PORT_RDY_hart0_reset_client_response_put;
  DEF_CAN_FIRE_hart0_reset_client_response_put = INST_dm_run_control.METH_RDY_hart0_reset_client_response_put();
  PORT_RDY_hart0_reset_client_response_put = DEF_CAN_FIRE_hart0_reset_client_response_put;
  return PORT_RDY_hart0_reset_client_response_put;
}

tUInt8 MOD_mkDebug_Module::METH_hart0_client_run_halt_request_get()
{
  tUInt8 PORT_hart0_client_run_halt_request_get;
  tUInt8 DEF_AVMeth_dm_run_control_hart0_client_run_halt_request_get;
  DEF_AVMeth_dm_run_control_hart0_client_run_halt_request_get = INST_dm_run_control.METH_hart0_client_run_halt_request_get();
  PORT_hart0_client_run_halt_request_get = DEF_AVMeth_dm_run_control_hart0_client_run_halt_request_get;
  return PORT_hart0_client_run_halt_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_client_run_halt_request_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_client_run_halt_request_get;
  tUInt8 PORT_RDY_hart0_client_run_halt_request_get;
  DEF_CAN_FIRE_hart0_client_run_halt_request_get = INST_dm_run_control.METH_RDY_hart0_client_run_halt_request_get();
  PORT_RDY_hart0_client_run_halt_request_get = DEF_CAN_FIRE_hart0_client_run_halt_request_get;
  return PORT_RDY_hart0_client_run_halt_request_get;
}

void MOD_mkDebug_Module::METH_hart0_client_run_halt_response_put(tUInt8 ARG_hart0_client_run_halt_response_put)
{
  INST_dm_run_control.METH_hart0_client_run_halt_response_put(ARG_hart0_client_run_halt_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_client_run_halt_response_put()
{
  tUInt8 DEF_CAN_FIRE_hart0_client_run_halt_response_put;
  tUInt8 PORT_RDY_hart0_client_run_halt_response_put;
  DEF_CAN_FIRE_hart0_client_run_halt_response_put = INST_dm_run_control.METH_RDY_hart0_client_run_halt_response_put();
  PORT_RDY_hart0_client_run_halt_response_put = DEF_CAN_FIRE_hart0_client_run_halt_response_put;
  return PORT_RDY_hart0_client_run_halt_response_put;
}

tUInt8 MOD_mkDebug_Module::METH_hart0_get_other_req_get()
{
  tUInt8 PORT_hart0_get_other_req_get;
  tUInt8 DEF_AVMeth_dm_run_control_hart0_get_other_req_get;
  DEF_AVMeth_dm_run_control_hart0_get_other_req_get = INST_dm_run_control.METH_hart0_get_other_req_get();
  PORT_hart0_get_other_req_get = DEF_AVMeth_dm_run_control_hart0_get_other_req_get;
  return PORT_hart0_get_other_req_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_get_other_req_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_get_other_req_get;
  tUInt8 PORT_RDY_hart0_get_other_req_get;
  DEF_CAN_FIRE_hart0_get_other_req_get = INST_dm_run_control.METH_RDY_hart0_get_other_req_get();
  PORT_RDY_hart0_get_other_req_get = DEF_CAN_FIRE_hart0_get_other_req_get;
  return PORT_RDY_hart0_get_other_req_get;
}

tUWide MOD_mkDebug_Module::METH_hart0_gpr_mem_client_request_get()
{
  tUWide DEF_AVMeth_dm_abstract_commands_hart0_gpr_mem_client_request_get(70u, false);
  DEF_AVMeth_dm_abstract_commands_hart0_gpr_mem_client_request_get = INST_dm_abstract_commands.METH_hart0_gpr_mem_client_request_get();
  PORT_hart0_gpr_mem_client_request_get = DEF_AVMeth_dm_abstract_commands_hart0_gpr_mem_client_request_get;
  return PORT_hart0_gpr_mem_client_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_gpr_mem_client_request_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_gpr_mem_client_request_get;
  tUInt8 PORT_RDY_hart0_gpr_mem_client_request_get;
  DEF_CAN_FIRE_hart0_gpr_mem_client_request_get = INST_dm_abstract_commands.METH_RDY_hart0_gpr_mem_client_request_get();
  PORT_RDY_hart0_gpr_mem_client_request_get = DEF_CAN_FIRE_hart0_gpr_mem_client_request_get;
  return PORT_RDY_hart0_gpr_mem_client_request_get;
}

void MOD_mkDebug_Module::METH_hart0_gpr_mem_client_response_put(tUWide ARG_hart0_gpr_mem_client_response_put)
{
  PORT_hart0_gpr_mem_client_response_put = ARG_hart0_gpr_mem_client_response_put;
  INST_dm_abstract_commands.METH_hart0_gpr_mem_client_response_put(ARG_hart0_gpr_mem_client_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_gpr_mem_client_response_put()
{
  tUInt8 DEF_CAN_FIRE_hart0_gpr_mem_client_response_put;
  tUInt8 PORT_RDY_hart0_gpr_mem_client_response_put;
  DEF_CAN_FIRE_hart0_gpr_mem_client_response_put = INST_dm_abstract_commands.METH_RDY_hart0_gpr_mem_client_response_put();
  PORT_RDY_hart0_gpr_mem_client_response_put = DEF_CAN_FIRE_hart0_gpr_mem_client_response_put;
  return PORT_RDY_hart0_gpr_mem_client_response_put;
}

tUWide MOD_mkDebug_Module::METH_hart0_fpr_mem_client_request_get()
{
  tUWide DEF_AVMeth_dm_abstract_commands_hart0_fpr_mem_client_request_get(70u, false);
  DEF_AVMeth_dm_abstract_commands_hart0_fpr_mem_client_request_get = INST_dm_abstract_commands.METH_hart0_fpr_mem_client_request_get();
  PORT_hart0_fpr_mem_client_request_get = DEF_AVMeth_dm_abstract_commands_hart0_fpr_mem_client_request_get;
  return PORT_hart0_fpr_mem_client_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_fpr_mem_client_request_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_fpr_mem_client_request_get;
  tUInt8 PORT_RDY_hart0_fpr_mem_client_request_get;
  DEF_CAN_FIRE_hart0_fpr_mem_client_request_get = INST_dm_abstract_commands.METH_RDY_hart0_fpr_mem_client_request_get();
  PORT_RDY_hart0_fpr_mem_client_request_get = DEF_CAN_FIRE_hart0_fpr_mem_client_request_get;
  return PORT_RDY_hart0_fpr_mem_client_request_get;
}

void MOD_mkDebug_Module::METH_hart0_fpr_mem_client_response_put(tUWide ARG_hart0_fpr_mem_client_response_put)
{
  PORT_hart0_fpr_mem_client_response_put = ARG_hart0_fpr_mem_client_response_put;
  INST_dm_abstract_commands.METH_hart0_fpr_mem_client_response_put(ARG_hart0_fpr_mem_client_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_fpr_mem_client_response_put()
{
  tUInt8 DEF_CAN_FIRE_hart0_fpr_mem_client_response_put;
  tUInt8 PORT_RDY_hart0_fpr_mem_client_response_put;
  DEF_CAN_FIRE_hart0_fpr_mem_client_response_put = INST_dm_abstract_commands.METH_RDY_hart0_fpr_mem_client_response_put();
  PORT_RDY_hart0_fpr_mem_client_response_put = DEF_CAN_FIRE_hart0_fpr_mem_client_response_put;
  return PORT_RDY_hart0_fpr_mem_client_response_put;
}

tUWide MOD_mkDebug_Module::METH_hart0_csr_mem_client_request_get()
{
  tUWide DEF_AVMeth_dm_abstract_commands_hart0_csr_mem_client_request_get(77u, false);
  DEF_AVMeth_dm_abstract_commands_hart0_csr_mem_client_request_get = INST_dm_abstract_commands.METH_hart0_csr_mem_client_request_get();
  PORT_hart0_csr_mem_client_request_get = DEF_AVMeth_dm_abstract_commands_hart0_csr_mem_client_request_get;
  return PORT_hart0_csr_mem_client_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_csr_mem_client_request_get()
{
  tUInt8 DEF_CAN_FIRE_hart0_csr_mem_client_request_get;
  tUInt8 PORT_RDY_hart0_csr_mem_client_request_get;
  DEF_CAN_FIRE_hart0_csr_mem_client_request_get = INST_dm_abstract_commands.METH_RDY_hart0_csr_mem_client_request_get();
  PORT_RDY_hart0_csr_mem_client_request_get = DEF_CAN_FIRE_hart0_csr_mem_client_request_get;
  return PORT_RDY_hart0_csr_mem_client_request_get;
}

void MOD_mkDebug_Module::METH_hart0_csr_mem_client_response_put(tUWide ARG_hart0_csr_mem_client_response_put)
{
  PORT_hart0_csr_mem_client_response_put = ARG_hart0_csr_mem_client_response_put;
  INST_dm_abstract_commands.METH_hart0_csr_mem_client_response_put(ARG_hart0_csr_mem_client_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_hart0_csr_mem_client_response_put()
{
  tUInt8 DEF_CAN_FIRE_hart0_csr_mem_client_response_put;
  tUInt8 PORT_RDY_hart0_csr_mem_client_response_put;
  DEF_CAN_FIRE_hart0_csr_mem_client_response_put = INST_dm_abstract_commands.METH_RDY_hart0_csr_mem_client_response_put();
  PORT_RDY_hart0_csr_mem_client_response_put = DEF_CAN_FIRE_hart0_csr_mem_client_response_put;
  return PORT_RDY_hart0_csr_mem_client_response_put;
}

tUInt8 MOD_mkDebug_Module::METH_ndm_reset_client_request_get()
{
  tUInt8 PORT_ndm_reset_client_request_get;
  tUInt8 DEF_AVMeth_dm_run_control_ndm_reset_client_request_get;
  DEF_AVMeth_dm_run_control_ndm_reset_client_request_get = INST_dm_run_control.METH_ndm_reset_client_request_get();
  PORT_ndm_reset_client_request_get = DEF_AVMeth_dm_run_control_ndm_reset_client_request_get;
  return PORT_ndm_reset_client_request_get;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_ndm_reset_client_request_get()
{
  tUInt8 DEF_CAN_FIRE_ndm_reset_client_request_get;
  tUInt8 PORT_RDY_ndm_reset_client_request_get;
  DEF_CAN_FIRE_ndm_reset_client_request_get = INST_dm_run_control.METH_RDY_ndm_reset_client_request_get();
  PORT_RDY_ndm_reset_client_request_get = DEF_CAN_FIRE_ndm_reset_client_request_get;
  return PORT_RDY_ndm_reset_client_request_get;
}

void MOD_mkDebug_Module::METH_ndm_reset_client_response_put(tUInt8 ARG_ndm_reset_client_response_put)
{
  INST_dm_run_control.METH_ndm_reset_client_response_put(ARG_ndm_reset_client_response_put);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_ndm_reset_client_response_put()
{
  tUInt8 DEF_CAN_FIRE_ndm_reset_client_response_put;
  tUInt8 PORT_RDY_ndm_reset_client_response_put;
  DEF_CAN_FIRE_ndm_reset_client_response_put = INST_dm_run_control.METH_RDY_ndm_reset_client_response_put();
  PORT_RDY_ndm_reset_client_response_put = DEF_CAN_FIRE_ndm_reset_client_response_put;
  return PORT_RDY_ndm_reset_client_response_put;
}

tUInt8 MOD_mkDebug_Module::METH_master_aw_canPeek()
{
  tUInt8 PORT_master_aw_canPeek;
  PORT_master_aw_canPeek = INST_dm_system_bus.METH_master_aw_canPeek();
  return PORT_master_aw_canPeek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_aw_canPeek()
{
  tUInt8 PORT_RDY_master_aw_canPeek;
  tUInt8 DEF_CAN_FIRE_master_aw_canPeek;
  DEF_CAN_FIRE_master_aw_canPeek = (tUInt8)1u;
  PORT_RDY_master_aw_canPeek = DEF_CAN_FIRE_master_aw_canPeek;
  return PORT_RDY_master_aw_canPeek;
}

tUWide MOD_mkDebug_Module::METH_master_aw_peek()
{
  PORT_master_aw_peek = INST_dm_system_bus.METH_master_aw_peek();
  return PORT_master_aw_peek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_aw_peek()
{
  tUInt8 DEF_CAN_FIRE_master_aw_peek;
  tUInt8 PORT_RDY_master_aw_peek;
  DEF_CAN_FIRE_master_aw_peek = INST_dm_system_bus.METH_RDY_master_aw_peek();
  PORT_RDY_master_aw_peek = DEF_CAN_FIRE_master_aw_peek;
  return PORT_RDY_master_aw_peek;
}

void MOD_mkDebug_Module::METH_master_aw_drop()
{
  INST_dm_system_bus.METH_master_aw_drop();
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_aw_drop()
{
  tUInt8 DEF_CAN_FIRE_master_aw_drop;
  tUInt8 PORT_RDY_master_aw_drop;
  DEF_CAN_FIRE_master_aw_drop = INST_dm_system_bus.METH_RDY_master_aw_drop();
  PORT_RDY_master_aw_drop = DEF_CAN_FIRE_master_aw_drop;
  return PORT_RDY_master_aw_drop;
}

tUInt8 MOD_mkDebug_Module::METH_master_w_canPeek()
{
  tUInt8 PORT_master_w_canPeek;
  PORT_master_w_canPeek = INST_dm_system_bus.METH_master_w_canPeek();
  return PORT_master_w_canPeek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_w_canPeek()
{
  tUInt8 PORT_RDY_master_w_canPeek;
  tUInt8 DEF_CAN_FIRE_master_w_canPeek;
  DEF_CAN_FIRE_master_w_canPeek = (tUInt8)1u;
  PORT_RDY_master_w_canPeek = DEF_CAN_FIRE_master_w_canPeek;
  return PORT_RDY_master_w_canPeek;
}

tUWide MOD_mkDebug_Module::METH_master_w_peek()
{
  PORT_master_w_peek = INST_dm_system_bus.METH_master_w_peek();
  return PORT_master_w_peek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_w_peek()
{
  tUInt8 DEF_CAN_FIRE_master_w_peek;
  tUInt8 PORT_RDY_master_w_peek;
  DEF_CAN_FIRE_master_w_peek = INST_dm_system_bus.METH_RDY_master_w_peek();
  PORT_RDY_master_w_peek = DEF_CAN_FIRE_master_w_peek;
  return PORT_RDY_master_w_peek;
}

void MOD_mkDebug_Module::METH_master_w_drop()
{
  INST_dm_system_bus.METH_master_w_drop();
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_w_drop()
{
  tUInt8 DEF_CAN_FIRE_master_w_drop;
  tUInt8 PORT_RDY_master_w_drop;
  DEF_CAN_FIRE_master_w_drop = INST_dm_system_bus.METH_RDY_master_w_drop();
  PORT_RDY_master_w_drop = DEF_CAN_FIRE_master_w_drop;
  return PORT_RDY_master_w_drop;
}

tUInt8 MOD_mkDebug_Module::METH_master_b_canPut()
{
  tUInt8 PORT_master_b_canPut;
  PORT_master_b_canPut = INST_dm_system_bus.METH_master_b_canPut();
  return PORT_master_b_canPut;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_b_canPut()
{
  tUInt8 PORT_RDY_master_b_canPut;
  tUInt8 DEF_CAN_FIRE_master_b_canPut;
  DEF_CAN_FIRE_master_b_canPut = (tUInt8)1u;
  PORT_RDY_master_b_canPut = DEF_CAN_FIRE_master_b_canPut;
  return PORT_RDY_master_b_canPut;
}

void MOD_mkDebug_Module::METH_master_b_put(tUInt8 ARG_master_b_put_val)
{
  INST_dm_system_bus.METH_master_b_put(ARG_master_b_put_val);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_b_put()
{
  tUInt8 DEF_CAN_FIRE_master_b_put;
  tUInt8 PORT_RDY_master_b_put;
  DEF_CAN_FIRE_master_b_put = INST_dm_system_bus.METH_RDY_master_b_put();
  PORT_RDY_master_b_put = DEF_CAN_FIRE_master_b_put;
  return PORT_RDY_master_b_put;
}

tUInt8 MOD_mkDebug_Module::METH_master_ar_canPeek()
{
  tUInt8 PORT_master_ar_canPeek;
  PORT_master_ar_canPeek = INST_dm_system_bus.METH_master_ar_canPeek();
  return PORT_master_ar_canPeek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_ar_canPeek()
{
  tUInt8 PORT_RDY_master_ar_canPeek;
  tUInt8 DEF_CAN_FIRE_master_ar_canPeek;
  DEF_CAN_FIRE_master_ar_canPeek = (tUInt8)1u;
  PORT_RDY_master_ar_canPeek = DEF_CAN_FIRE_master_ar_canPeek;
  return PORT_RDY_master_ar_canPeek;
}

tUWide MOD_mkDebug_Module::METH_master_ar_peek()
{
  PORT_master_ar_peek = INST_dm_system_bus.METH_master_ar_peek();
  return PORT_master_ar_peek;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_ar_peek()
{
  tUInt8 DEF_CAN_FIRE_master_ar_peek;
  tUInt8 PORT_RDY_master_ar_peek;
  DEF_CAN_FIRE_master_ar_peek = INST_dm_system_bus.METH_RDY_master_ar_peek();
  PORT_RDY_master_ar_peek = DEF_CAN_FIRE_master_ar_peek;
  return PORT_RDY_master_ar_peek;
}

void MOD_mkDebug_Module::METH_master_ar_drop()
{
  INST_dm_system_bus.METH_master_ar_drop();
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_ar_drop()
{
  tUInt8 DEF_CAN_FIRE_master_ar_drop;
  tUInt8 PORT_RDY_master_ar_drop;
  DEF_CAN_FIRE_master_ar_drop = INST_dm_system_bus.METH_RDY_master_ar_drop();
  PORT_RDY_master_ar_drop = DEF_CAN_FIRE_master_ar_drop;
  return PORT_RDY_master_ar_drop;
}

tUInt8 MOD_mkDebug_Module::METH_master_r_canPut()
{
  tUInt8 PORT_master_r_canPut;
  PORT_master_r_canPut = INST_dm_system_bus.METH_master_r_canPut();
  return PORT_master_r_canPut;
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_r_canPut()
{
  tUInt8 PORT_RDY_master_r_canPut;
  tUInt8 DEF_CAN_FIRE_master_r_canPut;
  DEF_CAN_FIRE_master_r_canPut = (tUInt8)1u;
  PORT_RDY_master_r_canPut = DEF_CAN_FIRE_master_r_canPut;
  return PORT_RDY_master_r_canPut;
}

void MOD_mkDebug_Module::METH_master_r_put(tUWide ARG_master_r_put_val)
{
  PORT_master_r_put_val = ARG_master_r_put_val;
  INST_dm_system_bus.METH_master_r_put(ARG_master_r_put_val);
}

tUInt8 MOD_mkDebug_Module::METH_RDY_master_r_put()
{
  tUInt8 DEF_CAN_FIRE_master_r_put;
  tUInt8 PORT_RDY_master_r_put;
  DEF_CAN_FIRE_master_r_put = INST_dm_system_bus.METH_RDY_master_r_put();
  PORT_RDY_master_r_put = DEF_CAN_FIRE_master_r_put;
  return PORT_RDY_master_r_put;
}


/* Reset routines */

void MOD_mkDebug_Module::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_f_read_addr.reset_RST(ARG_rst_in);
  INST_dm_system_bus.reset_RST_N(ARG_rst_in);
  INST_dm_run_control.reset_RST_N(ARG_rst_in);
  INST_dm_abstract_commands.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkDebug_Module::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkDebug_Module::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_dm_abstract_commands.dump_state(indent + 2u);
  INST_dm_run_control.dump_state(indent + 2u);
  INST_dm_system_bus.dump_state(indent + 2u);
  INST_f_read_addr.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkDebug_Module::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 51u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dm_addr__h701", 7u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "dm_run_control_dmactive____d1", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x10___d7", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x11___d8", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x12___d10", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x13___d12", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x14___d14", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x15___d16", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x16___d49", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x17___d50", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x18___d74", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x19___d18", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x20___d76", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x30___d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x38___d108", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x39___d109", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3A___d111", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3B___d113", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3C___d115", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3D___d117", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3E___d119", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x3F___d121", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x40___d22", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x4___d52", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x5F___d24", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x5___d54", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x60___d26", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x6___d56", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x7___d58", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x8___d60", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0x9___d62", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0xA___d64", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0xB___d66", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0xC___d68", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0xD___d70", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "f_read_addr_first_EQ_0xF___d72", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h502", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_csr_mem_client_request_get", 77u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_csr_mem_client_response_put", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_fpr_mem_client_request_get", 70u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_fpr_mem_client_response_put", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_gpr_mem_client_request_get", 70u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hart0_gpr_mem_client_response_put", 65u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "master_ar_peek", 97u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "master_aw_peek", 97u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "master_r_put_val", 72u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "master_w_peek", 74u);
  num = INST_f_read_addr.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_dm_abstract_commands.dump_VCD_defs(l);
    num = INST_dm_run_control.dump_VCD_defs(l);
    num = INST_dm_system_bus.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkDebug_Module::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDebug_Module &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkDebug_Module::vcd_defs(tVCDDumpType dt, MOD_mkDebug_Module &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 7u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 77u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 70u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 70u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 97u);
    vcd_write_x(sim_hdl, num++, 97u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 74u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_dm_addr__h701) != DEF_dm_addr__h701)
      {
	vcd_write_val(sim_hdl, num, DEF_dm_addr__h701, 7u);
	backing.DEF_dm_addr__h701 = DEF_dm_addr__h701;
      }
      ++num;
      if ((backing.DEF_dm_run_control_dmactive____d1) != DEF_dm_run_control_dmactive____d1)
      {
	vcd_write_val(sim_hdl, num, DEF_dm_run_control_dmactive____d1, 1u);
	backing.DEF_dm_run_control_dmactive____d1 = DEF_dm_run_control_dmactive____d1;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27) != DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27, 1u);
	backing.DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27 = DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x10___d7) != DEF_f_read_addr_first_EQ_0x10___d7)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x10___d7, 1u);
	backing.DEF_f_read_addr_first_EQ_0x10___d7 = DEF_f_read_addr_first_EQ_0x10___d7;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x11___d8) != DEF_f_read_addr_first_EQ_0x11___d8)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x11___d8, 1u);
	backing.DEF_f_read_addr_first_EQ_0x11___d8 = DEF_f_read_addr_first_EQ_0x11___d8;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x12___d10) != DEF_f_read_addr_first_EQ_0x12___d10)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x12___d10, 1u);
	backing.DEF_f_read_addr_first_EQ_0x12___d10 = DEF_f_read_addr_first_EQ_0x12___d10;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x13___d12) != DEF_f_read_addr_first_EQ_0x13___d12)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x13___d12, 1u);
	backing.DEF_f_read_addr_first_EQ_0x13___d12 = DEF_f_read_addr_first_EQ_0x13___d12;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x14___d14) != DEF_f_read_addr_first_EQ_0x14___d14)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x14___d14, 1u);
	backing.DEF_f_read_addr_first_EQ_0x14___d14 = DEF_f_read_addr_first_EQ_0x14___d14;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x15___d16) != DEF_f_read_addr_first_EQ_0x15___d16)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x15___d16, 1u);
	backing.DEF_f_read_addr_first_EQ_0x15___d16 = DEF_f_read_addr_first_EQ_0x15___d16;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77) != DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77, 1u);
	backing.DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77 = DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x16___d49) != DEF_f_read_addr_first_EQ_0x16___d49)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x16___d49, 1u);
	backing.DEF_f_read_addr_first_EQ_0x16___d49 = DEF_f_read_addr_first_EQ_0x16___d49;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x17___d50) != DEF_f_read_addr_first_EQ_0x17___d50)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x17___d50, 1u);
	backing.DEF_f_read_addr_first_EQ_0x17___d50 = DEF_f_read_addr_first_EQ_0x17___d50;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x18___d74) != DEF_f_read_addr_first_EQ_0x18___d74)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x18___d74, 1u);
	backing.DEF_f_read_addr_first_EQ_0x18___d74 = DEF_f_read_addr_first_EQ_0x18___d74;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x19___d18) != DEF_f_read_addr_first_EQ_0x19___d18)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x19___d18, 1u);
	backing.DEF_f_read_addr_first_EQ_0x19___d18 = DEF_f_read_addr_first_EQ_0x19___d18;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x20___d76) != DEF_f_read_addr_first_EQ_0x20___d76)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x20___d76, 1u);
	backing.DEF_f_read_addr_first_EQ_0x20___d76 = DEF_f_read_addr_first_EQ_0x20___d76;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x30___d20) != DEF_f_read_addr_first_EQ_0x30___d20)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x30___d20, 1u);
	backing.DEF_f_read_addr_first_EQ_0x30___d20 = DEF_f_read_addr_first_EQ_0x30___d20;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x38___d108) != DEF_f_read_addr_first_EQ_0x38___d108)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x38___d108, 1u);
	backing.DEF_f_read_addr_first_EQ_0x38___d108 = DEF_f_read_addr_first_EQ_0x38___d108;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x39___d109) != DEF_f_read_addr_first_EQ_0x39___d109)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x39___d109, 1u);
	backing.DEF_f_read_addr_first_EQ_0x39___d109 = DEF_f_read_addr_first_EQ_0x39___d109;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3A___d111) != DEF_f_read_addr_first_EQ_0x3A___d111)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3A___d111, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3A___d111 = DEF_f_read_addr_first_EQ_0x3A___d111;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3B___d113) != DEF_f_read_addr_first_EQ_0x3B___d113)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3B___d113, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3B___d113 = DEF_f_read_addr_first_EQ_0x3B___d113;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3C___d115) != DEF_f_read_addr_first_EQ_0x3C___d115)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3C___d115, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3C___d115 = DEF_f_read_addr_first_EQ_0x3C___d115;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3D___d117) != DEF_f_read_addr_first_EQ_0x3D___d117)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3D___d117, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3D___d117 = DEF_f_read_addr_first_EQ_0x3D___d117;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3E___d119) != DEF_f_read_addr_first_EQ_0x3E___d119)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3E___d119, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3E___d119 = DEF_f_read_addr_first_EQ_0x3E___d119;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x3F___d121) != DEF_f_read_addr_first_EQ_0x3F___d121)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x3F___d121, 1u);
	backing.DEF_f_read_addr_first_EQ_0x3F___d121 = DEF_f_read_addr_first_EQ_0x3F___d121;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x40___d22) != DEF_f_read_addr_first_EQ_0x40___d22)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x40___d22, 1u);
	backing.DEF_f_read_addr_first_EQ_0x40___d22 = DEF_f_read_addr_first_EQ_0x40___d22;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x4___d52) != DEF_f_read_addr_first_EQ_0x4___d52)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x4___d52, 1u);
	backing.DEF_f_read_addr_first_EQ_0x4___d52 = DEF_f_read_addr_first_EQ_0x4___d52;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x5F___d24) != DEF_f_read_addr_first_EQ_0x5F___d24)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x5F___d24, 1u);
	backing.DEF_f_read_addr_first_EQ_0x5F___d24 = DEF_f_read_addr_first_EQ_0x5F___d24;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x5___d54) != DEF_f_read_addr_first_EQ_0x5___d54)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x5___d54, 1u);
	backing.DEF_f_read_addr_first_EQ_0x5___d54 = DEF_f_read_addr_first_EQ_0x5___d54;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x60___d26) != DEF_f_read_addr_first_EQ_0x60___d26)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x60___d26, 1u);
	backing.DEF_f_read_addr_first_EQ_0x60___d26 = DEF_f_read_addr_first_EQ_0x60___d26;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x6___d56) != DEF_f_read_addr_first_EQ_0x6___d56)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x6___d56, 1u);
	backing.DEF_f_read_addr_first_EQ_0x6___d56 = DEF_f_read_addr_first_EQ_0x6___d56;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x7___d58) != DEF_f_read_addr_first_EQ_0x7___d58)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x7___d58, 1u);
	backing.DEF_f_read_addr_first_EQ_0x7___d58 = DEF_f_read_addr_first_EQ_0x7___d58;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x8___d60) != DEF_f_read_addr_first_EQ_0x8___d60)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x8___d60, 1u);
	backing.DEF_f_read_addr_first_EQ_0x8___d60 = DEF_f_read_addr_first_EQ_0x8___d60;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0x9___d62) != DEF_f_read_addr_first_EQ_0x9___d62)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0x9___d62, 1u);
	backing.DEF_f_read_addr_first_EQ_0x9___d62 = DEF_f_read_addr_first_EQ_0x9___d62;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0xA___d64) != DEF_f_read_addr_first_EQ_0xA___d64)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0xA___d64, 1u);
	backing.DEF_f_read_addr_first_EQ_0xA___d64 = DEF_f_read_addr_first_EQ_0xA___d64;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0xB___d66) != DEF_f_read_addr_first_EQ_0xB___d66)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0xB___d66, 1u);
	backing.DEF_f_read_addr_first_EQ_0xB___d66 = DEF_f_read_addr_first_EQ_0xB___d66;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0xC___d68) != DEF_f_read_addr_first_EQ_0xC___d68)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0xC___d68, 1u);
	backing.DEF_f_read_addr_first_EQ_0xC___d68 = DEF_f_read_addr_first_EQ_0xC___d68;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0xD___d70) != DEF_f_read_addr_first_EQ_0xD___d70)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0xD___d70, 1u);
	backing.DEF_f_read_addr_first_EQ_0xD___d70 = DEF_f_read_addr_first_EQ_0xD___d70;
      }
      ++num;
      if ((backing.DEF_f_read_addr_first_EQ_0xF___d72) != DEF_f_read_addr_first_EQ_0xF___d72)
      {
	vcd_write_val(sim_hdl, num, DEF_f_read_addr_first_EQ_0xF___d72, 1u);
	backing.DEF_f_read_addr_first_EQ_0xF___d72 = DEF_f_read_addr_first_EQ_0xF___d72;
      }
      ++num;
      if ((backing.DEF_v__h502) != DEF_v__h502)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h502, 32u);
	backing.DEF_v__h502 = DEF_v__h502;
      }
      ++num;
      if ((backing.PORT_hart0_csr_mem_client_request_get) != PORT_hart0_csr_mem_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_csr_mem_client_request_get, 77u);
	backing.PORT_hart0_csr_mem_client_request_get = PORT_hart0_csr_mem_client_request_get;
      }
      ++num;
      if ((backing.PORT_hart0_csr_mem_client_response_put) != PORT_hart0_csr_mem_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_csr_mem_client_response_put, 65u);
	backing.PORT_hart0_csr_mem_client_response_put = PORT_hart0_csr_mem_client_response_put;
      }
      ++num;
      if ((backing.PORT_hart0_fpr_mem_client_request_get) != PORT_hart0_fpr_mem_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_fpr_mem_client_request_get, 70u);
	backing.PORT_hart0_fpr_mem_client_request_get = PORT_hart0_fpr_mem_client_request_get;
      }
      ++num;
      if ((backing.PORT_hart0_fpr_mem_client_response_put) != PORT_hart0_fpr_mem_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_fpr_mem_client_response_put, 65u);
	backing.PORT_hart0_fpr_mem_client_response_put = PORT_hart0_fpr_mem_client_response_put;
      }
      ++num;
      if ((backing.PORT_hart0_gpr_mem_client_request_get) != PORT_hart0_gpr_mem_client_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_gpr_mem_client_request_get, 70u);
	backing.PORT_hart0_gpr_mem_client_request_get = PORT_hart0_gpr_mem_client_request_get;
      }
      ++num;
      if ((backing.PORT_hart0_gpr_mem_client_response_put) != PORT_hart0_gpr_mem_client_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_hart0_gpr_mem_client_response_put, 65u);
	backing.PORT_hart0_gpr_mem_client_response_put = PORT_hart0_gpr_mem_client_response_put;
      }
      ++num;
      if ((backing.PORT_master_ar_peek) != PORT_master_ar_peek)
      {
	vcd_write_val(sim_hdl, num, PORT_master_ar_peek, 97u);
	backing.PORT_master_ar_peek = PORT_master_ar_peek;
      }
      ++num;
      if ((backing.PORT_master_aw_peek) != PORT_master_aw_peek)
      {
	vcd_write_val(sim_hdl, num, PORT_master_aw_peek, 97u);
	backing.PORT_master_aw_peek = PORT_master_aw_peek;
      }
      ++num;
      if ((backing.PORT_master_r_put_val) != PORT_master_r_put_val)
      {
	vcd_write_val(sim_hdl, num, PORT_master_r_put_val, 72u);
	backing.PORT_master_r_put_val = PORT_master_r_put_val;
      }
      ++num;
      if ((backing.PORT_master_w_peek) != PORT_master_w_peek)
      {
	vcd_write_val(sim_hdl, num, PORT_master_w_peek, 74u);
	backing.PORT_master_w_peek = PORT_master_w_peek;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_dm_addr__h701, 7u);
      backing.DEF_dm_addr__h701 = DEF_dm_addr__h701;
      vcd_write_val(sim_hdl, num++, DEF_dm_run_control_dmactive____d1, 1u);
      backing.DEF_dm_run_control_dmactive____d1 = DEF_dm_run_control_dmactive____d1;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27, 1u);
      backing.DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27 = DEF_f_read_addr_first_EQ_0x10_OR_f_read_addr_first_ETC___d27;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x10___d7, 1u);
      backing.DEF_f_read_addr_first_EQ_0x10___d7 = DEF_f_read_addr_first_EQ_0x10___d7;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x11___d8, 1u);
      backing.DEF_f_read_addr_first_EQ_0x11___d8 = DEF_f_read_addr_first_EQ_0x11___d8;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x12___d10, 1u);
      backing.DEF_f_read_addr_first_EQ_0x12___d10 = DEF_f_read_addr_first_EQ_0x12___d10;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x13___d12, 1u);
      backing.DEF_f_read_addr_first_EQ_0x13___d12 = DEF_f_read_addr_first_EQ_0x13___d12;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x14___d14, 1u);
      backing.DEF_f_read_addr_first_EQ_0x14___d14 = DEF_f_read_addr_first_EQ_0x14___d14;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x15___d16, 1u);
      backing.DEF_f_read_addr_first_EQ_0x15___d16 = DEF_f_read_addr_first_EQ_0x15___d16;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77, 1u);
      backing.DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77 = DEF_f_read_addr_first_EQ_0x16_9_OR_f_read_addr_fir_ETC___d77;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x16___d49, 1u);
      backing.DEF_f_read_addr_first_EQ_0x16___d49 = DEF_f_read_addr_first_EQ_0x16___d49;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x17___d50, 1u);
      backing.DEF_f_read_addr_first_EQ_0x17___d50 = DEF_f_read_addr_first_EQ_0x17___d50;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x18___d74, 1u);
      backing.DEF_f_read_addr_first_EQ_0x18___d74 = DEF_f_read_addr_first_EQ_0x18___d74;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x19___d18, 1u);
      backing.DEF_f_read_addr_first_EQ_0x19___d18 = DEF_f_read_addr_first_EQ_0x19___d18;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x20___d76, 1u);
      backing.DEF_f_read_addr_first_EQ_0x20___d76 = DEF_f_read_addr_first_EQ_0x20___d76;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x30___d20, 1u);
      backing.DEF_f_read_addr_first_EQ_0x30___d20 = DEF_f_read_addr_first_EQ_0x30___d20;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x38___d108, 1u);
      backing.DEF_f_read_addr_first_EQ_0x38___d108 = DEF_f_read_addr_first_EQ_0x38___d108;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x39___d109, 1u);
      backing.DEF_f_read_addr_first_EQ_0x39___d109 = DEF_f_read_addr_first_EQ_0x39___d109;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3A___d111, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3A___d111 = DEF_f_read_addr_first_EQ_0x3A___d111;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3B___d113, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3B___d113 = DEF_f_read_addr_first_EQ_0x3B___d113;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3C___d115, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3C___d115 = DEF_f_read_addr_first_EQ_0x3C___d115;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3D___d117, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3D___d117 = DEF_f_read_addr_first_EQ_0x3D___d117;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3E___d119, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3E___d119 = DEF_f_read_addr_first_EQ_0x3E___d119;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x3F___d121, 1u);
      backing.DEF_f_read_addr_first_EQ_0x3F___d121 = DEF_f_read_addr_first_EQ_0x3F___d121;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x40___d22, 1u);
      backing.DEF_f_read_addr_first_EQ_0x40___d22 = DEF_f_read_addr_first_EQ_0x40___d22;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x4___d52, 1u);
      backing.DEF_f_read_addr_first_EQ_0x4___d52 = DEF_f_read_addr_first_EQ_0x4___d52;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x5F___d24, 1u);
      backing.DEF_f_read_addr_first_EQ_0x5F___d24 = DEF_f_read_addr_first_EQ_0x5F___d24;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x5___d54, 1u);
      backing.DEF_f_read_addr_first_EQ_0x5___d54 = DEF_f_read_addr_first_EQ_0x5___d54;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x60___d26, 1u);
      backing.DEF_f_read_addr_first_EQ_0x60___d26 = DEF_f_read_addr_first_EQ_0x60___d26;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x6___d56, 1u);
      backing.DEF_f_read_addr_first_EQ_0x6___d56 = DEF_f_read_addr_first_EQ_0x6___d56;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x7___d58, 1u);
      backing.DEF_f_read_addr_first_EQ_0x7___d58 = DEF_f_read_addr_first_EQ_0x7___d58;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x8___d60, 1u);
      backing.DEF_f_read_addr_first_EQ_0x8___d60 = DEF_f_read_addr_first_EQ_0x8___d60;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0x9___d62, 1u);
      backing.DEF_f_read_addr_first_EQ_0x9___d62 = DEF_f_read_addr_first_EQ_0x9___d62;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0xA___d64, 1u);
      backing.DEF_f_read_addr_first_EQ_0xA___d64 = DEF_f_read_addr_first_EQ_0xA___d64;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0xB___d66, 1u);
      backing.DEF_f_read_addr_first_EQ_0xB___d66 = DEF_f_read_addr_first_EQ_0xB___d66;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0xC___d68, 1u);
      backing.DEF_f_read_addr_first_EQ_0xC___d68 = DEF_f_read_addr_first_EQ_0xC___d68;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0xD___d70, 1u);
      backing.DEF_f_read_addr_first_EQ_0xD___d70 = DEF_f_read_addr_first_EQ_0xD___d70;
      vcd_write_val(sim_hdl, num++, DEF_f_read_addr_first_EQ_0xF___d72, 1u);
      backing.DEF_f_read_addr_first_EQ_0xF___d72 = DEF_f_read_addr_first_EQ_0xF___d72;
      vcd_write_val(sim_hdl, num++, DEF_v__h502, 32u);
      backing.DEF_v__h502 = DEF_v__h502;
      vcd_write_val(sim_hdl, num++, PORT_hart0_csr_mem_client_request_get, 77u);
      backing.PORT_hart0_csr_mem_client_request_get = PORT_hart0_csr_mem_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_hart0_csr_mem_client_response_put, 65u);
      backing.PORT_hart0_csr_mem_client_response_put = PORT_hart0_csr_mem_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_hart0_fpr_mem_client_request_get, 70u);
      backing.PORT_hart0_fpr_mem_client_request_get = PORT_hart0_fpr_mem_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_hart0_fpr_mem_client_response_put, 65u);
      backing.PORT_hart0_fpr_mem_client_response_put = PORT_hart0_fpr_mem_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_hart0_gpr_mem_client_request_get, 70u);
      backing.PORT_hart0_gpr_mem_client_request_get = PORT_hart0_gpr_mem_client_request_get;
      vcd_write_val(sim_hdl, num++, PORT_hart0_gpr_mem_client_response_put, 65u);
      backing.PORT_hart0_gpr_mem_client_response_put = PORT_hart0_gpr_mem_client_response_put;
      vcd_write_val(sim_hdl, num++, PORT_master_ar_peek, 97u);
      backing.PORT_master_ar_peek = PORT_master_ar_peek;
      vcd_write_val(sim_hdl, num++, PORT_master_aw_peek, 97u);
      backing.PORT_master_aw_peek = PORT_master_aw_peek;
      vcd_write_val(sim_hdl, num++, PORT_master_r_put_val, 72u);
      backing.PORT_master_r_put_val = PORT_master_r_put_val;
      vcd_write_val(sim_hdl, num++, PORT_master_w_peek, 74u);
      backing.PORT_master_w_peek = PORT_master_w_peek;
    }
}

void MOD_mkDebug_Module::vcd_prims(tVCDDumpType dt, MOD_mkDebug_Module &backing)
{
  INST_f_read_addr.dump_VCD(dt, backing.INST_f_read_addr);
}

void MOD_mkDebug_Module::vcd_submodules(tVCDDumpType dt,
					unsigned int levels,
					MOD_mkDebug_Module &backing)
{
  INST_dm_abstract_commands.dump_VCD(dt, levels, backing.INST_dm_abstract_commands);
  INST_dm_run_control.dump_VCD(dt, levels, backing.INST_dm_run_control);
  INST_dm_system_bus.dump_VCD(dt, levels, backing.INST_dm_system_bus);
}
