/*
 * Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
 * 
 * On Fri Mar 25 15:59:20 CET 2022
 * 
 */

/* Generation options: */
#ifndef __mkFBox_Core_h__
#define __mkFBox_Core_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkFPU.h"


/* Class declaration for the mkFBox_Core module */
class MOD_mkFBox_Core : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUWide> INST_dw_result;
  MOD_Wire<tUInt8> INST_dw_valid;
  MOD_mkFPU INST_fpu;
  MOD_Fifo<tUInt8> INST_frmFpuF;
  MOD_Reg<tUWide> INST_requestR;
  MOD_Reg<tUInt8> INST_requestR_valid;
  MOD_Fifo<tUInt8> INST_resetReqsF;
  MOD_Fifo<tUInt8> INST_resetRspsF;
  MOD_Reg<tUWide> INST_resultR;
  MOD_Reg<tUInt8> INST_stateR;
 
 /* Constructor */
 public:
  MOD_mkFBox_Core(tSimStateHdl simHdl, char const *name, Module *parent, tUInt8 ARG_verbosity);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_verbosity;
 
 /* Publicly accessible definitions */
 public:
  tUWide DEF_requestR___d15;
  tUInt8 DEF_rm__h603;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x1___d45;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x2___d46;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x0___d44;
 
 /* Local definitions */
 private:
  tUInt32 DEF_v__h229385;
  tUInt32 DEF_v__h229228;
  tUInt32 DEF_v__h229076;
  tUInt32 DEF_v__h227139;
  tUInt32 DEF_v__h225222;
  tUInt32 DEF_v__h222487;
  tUInt32 DEF_v__h217999;
  tUInt32 DEF_v__h213411;
  tUInt32 DEF_v__h167421;
  tUInt32 DEF_v__h112555;
  tUInt32 DEF_v__h111771;
  tUInt32 DEF_v__h109712;
  tUInt32 DEF_v__h97279;
  tUInt32 DEF_v__h84278;
  tUInt32 DEF_v__h83491;
  tUInt32 DEF_v__h81877;
  tUInt32 DEF_v__h70958;
  tUInt32 DEF_v__h59759;
  tUInt32 DEF_v__h59591;
  tUInt32 DEF_v__h59428;
  tUInt32 DEF_v__h59267;
  tUInt32 DEF_v__h59069;
  tUInt32 DEF_v__h58880;
  tUInt32 DEF_v__h58698;
  tUInt32 DEF_v__h58523;
  tUInt32 DEF_v__h58348;
  tUInt32 DEF_v__h58160;
  tUInt32 DEF_v__h57978;
  tUInt32 DEF_v__h57789;
  tUInt32 DEF_v__h57574;
  tUInt32 DEF_v__h57093;
  tUInt32 DEF_v__h55966;
  tUInt32 DEF_v__h54857;
  tUInt32 DEF_v__h53334;
  tUInt32 DEF_v__h53159;
  tUInt32 DEF_v__h52999;
  tUInt32 DEF_v__h50428;
  tUInt32 DEF_v__h47754;
  tUInt32 DEF_v__h46967;
  tUInt32 DEF_v__h45353;
  tUInt32 DEF_v__h44569;
  tUInt32 DEF_v__h42493;
  tUInt32 DEF_v__h35605;
  tUInt32 DEF_v__h28405;
  tUInt32 DEF_v__h16368;
  tUInt32 DEF_v__h3611;
  tUInt32 DEF_v__h3427;
  tUInt32 DEF_v__h3254;
  tUInt32 DEF_v__h3071;
  tUInt32 DEF_v__h2873;
  tUInt32 DEF_v__h2684;
  tUInt32 DEF_v__h2502;
  tUInt32 DEF_v__h2327;
  tUInt32 DEF_v__h2152;
  tUInt32 DEF_v__h1908;
  tUInt32 DEF_v__h1707;
  tUInt32 DEF_v__h1518;
  tUInt32 DEF_v__h1062;
  tUWide DEF_fpu_server_core_response_get___d5425;
  tUWide DEF_resultR___d5448;
  tUWide DEF_dw_result_wget____d5458;
  tUWide DEF_resultR_448_BITS_68_TO_0___d5450;
  tUWide DEF_out1__h109971;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d3216;
  tUWide DEF_out1__h42752;
  tUWide DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1747;
  tUInt64 DEF_sfd__h16473;
  tUInt64 DEF_requestR_5_BITS_127_TO_64___d2207;
  tUWide DEF_x__h112280;
  tUWide DEF_x__h110941;
  tUWide DEF_x__h45078;
  tUWide DEF_x__h43722;
  tUWide DEF__theResult_____2__h109976;
  tUWide DEF__theResult_____2__h42757;
  tUInt64 DEF_requestR_5_BITS_190_TO_128___d2276;
  tUWide DEF_x__h84003;
  tUWide DEF_x__h82885;
  tUInt64 DEF_dV1_sfd__h57659;
  tUInt64 DEF_dV2_sfd__h57688;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d2723;
  tUInt64 DEF_sfd___3__h26950;
  tUInt64 DEF_sfd___3__h14733;
  tUInt32 DEF_requestR_5_BITS_159_TO_128___d1177;
  tUInt32 DEF_sV1_sfd__h1246;
  tUInt32 DEF_dV1_exp__h57658;
  tUInt32 DEF_dV2_exp__h57687;
  tUInt8 DEF_requestR_5_BIT_191___d174;
  tUInt8 DEF_requestR_5_BIT_190___d704;
  tUInt8 DEF_requestR_5_BIT_189___d706;
  tUInt8 DEF_requestR_5_BIT_188___d708;
  tUInt8 DEF_requestR_5_BIT_187___d710;
  tUInt8 DEF_requestR_5_BIT_186___d712;
  tUInt8 DEF_requestR_5_BIT_185___d714;
  tUInt8 DEF_requestR_5_BIT_184___d716;
  tUInt8 DEF_requestR_5_BIT_183___d718;
  tUInt8 DEF_requestR_5_BIT_182___d720;
  tUInt8 DEF_requestR_5_BIT_181___d722;
  tUInt8 DEF_requestR_5_BIT_180___d724;
  tUInt8 DEF_requestR_5_BIT_179___d726;
  tUInt8 DEF_requestR_5_BIT_178___d728;
  tUInt8 DEF_requestR_5_BIT_177___d730;
  tUInt8 DEF_requestR_5_BIT_176___d732;
  tUInt8 DEF_requestR_5_BIT_175___d734;
  tUInt8 DEF_requestR_5_BIT_174___d736;
  tUInt8 DEF_requestR_5_BIT_173___d738;
  tUInt8 DEF_requestR_5_BIT_172___d740;
  tUInt8 DEF_requestR_5_BIT_171___d742;
  tUInt8 DEF_requestR_5_BIT_170___d744;
  tUInt8 DEF_requestR_5_BIT_169___d746;
  tUInt8 DEF_requestR_5_BIT_168___d748;
  tUInt8 DEF_requestR_5_BIT_167___d750;
  tUInt8 DEF_requestR_5_BIT_166___d752;
  tUInt8 DEF_requestR_5_BIT_165___d754;
  tUInt8 DEF_requestR_5_BIT_164___d756;
  tUInt8 DEF_requestR_5_BIT_163___d758;
  tUInt8 DEF_requestR_5_BIT_162___d760;
  tUInt8 DEF_requestR_5_BIT_161___d762;
  tUInt8 DEF_requestR_5_BIT_160___d764;
  tUInt8 DEF_requestR_5_BIT_159___d29;
  tUInt8 DEF_requestR_5_BIT_158___d767;
  tUInt8 DEF_requestR_5_BIT_157___d769;
  tUInt8 DEF_requestR_5_BIT_156___d771;
  tUInt8 DEF_requestR_5_BIT_155___d773;
  tUInt8 DEF_requestR_5_BIT_154___d775;
  tUInt8 DEF_requestR_5_BIT_153___d777;
  tUInt8 DEF_requestR_5_BIT_152___d779;
  tUInt8 DEF_requestR_5_BIT_151___d781;
  tUInt8 DEF_requestR_5_BIT_150___d783;
  tUInt8 DEF_requestR_5_BIT_149___d785;
  tUInt8 DEF_requestR_5_BIT_148___d787;
  tUInt8 DEF_requestR_5_BIT_147___d789;
  tUInt8 DEF_requestR_5_BIT_146___d791;
  tUInt8 DEF_requestR_5_BIT_145___d793;
  tUInt8 DEF_requestR_5_BIT_144___d795;
  tUInt8 DEF_requestR_5_BIT_143___d797;
  tUInt8 DEF_requestR_5_BIT_142___d799;
  tUInt8 DEF_requestR_5_BIT_141___d801;
  tUInt8 DEF_requestR_5_BIT_140___d803;
  tUInt8 DEF_requestR_5_BIT_139___d805;
  tUInt8 DEF_requestR_5_BIT_138___d807;
  tUInt8 DEF_requestR_5_BIT_137___d809;
  tUInt8 DEF_requestR_5_BIT_136___d811;
  tUInt8 DEF_requestR_5_BIT_135___d813;
  tUInt8 DEF_requestR_5_BIT_134___d815;
  tUInt8 DEF_requestR_5_BIT_133___d817;
  tUInt8 DEF_requestR_5_BIT_132___d819;
  tUInt8 DEF_requestR_5_BIT_131___d821;
  tUInt8 DEF_requestR_5_BIT_130___d823;
  tUInt8 DEF_requestR_5_BIT_129___d825;
  tUInt8 DEF_requestR_5_BIT_128___d827;
  tUInt8 DEF_requestR_5_BIT_127___d2275;
  tUInt8 DEF_requestR_5_BIT_115___d5283;
  tUInt8 DEF_requestR_5_BIT_95___d37;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d177;
  tUInt64 DEF_sfd__h3719;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d179;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d181;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d183;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d185;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d187;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d189;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d191;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d193;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d195;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d197;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d199;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d201;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d203;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d205;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d207;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d209;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d211;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d213;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d215;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d217;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d219;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d221;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d223;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d225;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d227;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d229;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d231;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d233;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d235;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d237;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d239;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d241;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d243;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d245;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d247;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d249;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d251;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d253;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d255;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d257;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d259;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d261;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d263;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d265;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d267;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d269;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d271;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d273;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d275;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d277;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d279;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d281;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d283;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d285;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d287;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d289;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d291;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d293;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d295;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d297;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d299;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d301;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d303;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1182;
  tUInt32 DEF_sfd__h28513;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1184;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1186;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1188;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1190;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1192;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1194;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1196;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1198;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1200;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1202;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1204;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1206;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1208;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1210;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1212;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1214;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1216;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1218;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1220;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1222;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1224;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1226;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1228;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1230;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1232;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1234;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1236;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1238;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1240;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1242;
  tUInt8 DEF_IF_requestR_5_BIT_159_9_THEN_NEG_requestR_5_BI_ETC___d1244;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2054;
  tUInt32 DEF_sV2_sfd__h1345;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2043;
  tUWide DEF_NEG_0b0_CONCAT_NOT_requestR_5_BITS_190_TO_180__ETC___d3215;
  tUWide DEF_b__h110041;
  tUInt8 DEF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF_8_A_ETC___d30;
  tUWide DEF_NEG_0b0_CONCAT_NOT_IF_requestR_5_BITS_191_TO_1_ETC___d1746;
  tUWide DEF_b__h42822;
  tUWide DEF_NEG_0b0_CONCAT_NOT_requestR_5_BITS_190_TO_180__ETC___d2722;
  tUWide DEF_b__h82209;
  tUWide DEF_IF_resultR_448_BIT_69_449_THEN_resultR_448_BIT_ETC___d5451;
  tUWide DEF_out1___1__h110692;
  tUWide DEF_out1___1__h43473;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d5355;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d5286;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_2047_278_AND_ETC___d5285;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d5289;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_0_712_AND_re_ETC___d5294;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_0_291_AND_re_ETC___d5298;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_2047_703_ETC___d5322;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_2047_278_AND_ETC___d5288;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d5287;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d4233;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d2710;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_0_712_AND_re_ETC___d2713;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_0___d2712;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d2707;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d2708;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2146;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2057;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2056;
  tUInt64 DEF_res__h48760;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2062;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d2095;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2060;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2045;
  tUInt64 DEF_res__h48523;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1734;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1732;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1737;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1736;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1729;
  tUInt64 DEF_b__h45685;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_OR_NOT_r_ETC___d3835;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_OR_NOT_r_ETC___d448;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x4___d48;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x3___d47;
  tUInt32 DEF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF_8_A_ETC___d33;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2067;
  tUInt32 DEF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_AN_ETC___d41;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2071;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2061;
  tUInt8 DEF_requestR_5_BITS_63_TO_32_0_EQ_0xFFFFFFFF___d81;
  tUInt8 DEF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF___d36;
  tUInt32 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d32;
  tUInt8 DEF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF___d28;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1724;
  tUInt8 DEF_requestR_5_BITS_159_TO_128_177_EQ_0___d1178;
  tUInt8 DEF_requestR_5_BITS_191_TO_128_71_EQ_0_72_OR_NOT_r_ETC___d892;
  tUInt8 DEF_requestR_5_BITS_191_TO_128_71_EQ_0_72_OR_NOT_I_ETC___d504;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047___d2703;
  tUInt8 DEF_sV2_exp__h1344;
  tUInt8 DEF_sV1_exp__h1245;
  tUInt8 DEF_IF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR__ETC___d431;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_0_ELSE_IF_reques_ETC___d956;
  tUInt8 DEF_IF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_THEN__ETC___d53;
  tUInt8 DEF_NOT_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF_ETC___d1731;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x1_5_AND_requ_ETC___d471;
  tUInt8 DEF_requestR_5_BITS_194_TO_192_3_EQ_0x1_5_AND_requ_ETC___d1339;
  tUWide DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d3310;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d3251;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d3219;
  tUWide DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1847;
  tUWide DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1782;
  tUWide DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1750;
  tUWide DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d2824;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d2758;
  tUWide DEF_IF_requestR_5_BIT_191_74_THEN_NEG_0b0_CONCAT_N_ETC___d2726;
  tUInt8 DEF_requestR_5_BITS_191_TO_128_71_EQ_0___d172;
  tUInt64 DEF_value__h82211;
  tUInt8 DEF_requestR_5_BITS_115_TO_64_279_EQ_0___d5280;
  tUInt8 DEF_requestR_5_BITS_179_TO_128_704_EQ_0___d2705;
  tUInt32 DEF_value__h42824;
  tUInt32 DEF_NEG_SEXT_requestR_5_BITS_190_TO_180_702_MINUS__ETC___d2716;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2051;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1727;
  tUInt32 DEF_NEG_SEXT_IF_requestR_5_BITS_191_TO_160_7_EQ_0x_ETC___d1740;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_2047___d5278;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_0___d5291;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_requestR_5_B_ETC___d5309;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2048;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2064;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2081;
  tUInt8 DEF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_AN_ETC___d38;
  tUInt8 DEF_NOT_requestR_5_BITS_115_TO_64_279_EQ_0_280___d5281;
  tUInt8 DEF_NOT_requestR_5_BITS_179_TO_128_704_EQ_0_705___d2706;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFF_ETC___d2052;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1728;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_0_712_AND_re_ETC___d5370;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_requestR_ETC___d5358;
  tUInt8 DEF_requestR_5_BITS_179_TO_128_704_ULE_requestR_5__ETC___d5310;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d5331;
  tUInt8 DEF_requestR_5_BIT_191_74_AND_NOT_requestR_5_BIT_1_ETC___d5320;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_ULT_requestR_5__ETC___d5314;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_2047_703_ETC___d2798;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_2047_703___d2796;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_2047_703_ETC___d2797;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_EQ_2047_703_AND_ETC___d2786;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d2787;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712___d2718;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2161;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d2150;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2087;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2105;
  tUInt8 DEF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF_8_A_ETC___d2093;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2080;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1821;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1819;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1820;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1809;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1810;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1742;
  tUInt8 DEF_NOT_requestR_5_BIT_159_9___d766;
  tUInt8 DEF_NOT_requestR_5_BIT_159_9_66_AND_NOT_requestR_5_ETC___d859;
  tUInt8 DEF_NOT_requestR_5_BIT_191_74_03_AND_NOT_requestR__ETC___d891;
  tUInt8 DEF_NOT_requestR_5_BIT_191_74___d703;
  tUInt8 DEF_requestR_5_BIT_159_9_OR_requestR_5_BIT_158_67__ETC___d1114;
  tUInt8 DEF_NOT_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_ETC___d367;
  tUInt8 DEF_IF_requestR_5_BIT_191_74_THEN_NEG_requestR_5_B_ETC___d665;
  tUInt8 DEF_requestR_5_BIT_191_74_OR_NOT_requestR_5_BIT_12_ETC___d5306;
  tUInt8 DEF_NOT_requestR_5_BIT_127_275___d2283;
  tUInt8 DEF_requestR_5_BIT_191_74_OR_requestR_5_BIT_190_04_ETC___d1146;
  tUInt8 DEF_NOT_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF__ETC___d150;
  tUInt8 DEF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF_8_A_ETC___d2079;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_ULT_request_ETC___d5364;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_ULE_requestR_5__ETC___d5360;
  tUInt8 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_2047_703_ETC___d5301;
  tUInt8 DEF_requestR_5_BITS_179_TO_128_704_ULT_requestR_5__ETC___d5315;
  tUInt8 DEF_requestR_5_BITS_190_TO_180_702_ULE_requestR_5__ETC___d5307;
  tUInt8 DEF_requestR_5_BITS_126_TO_116_277_EQ_0_291_AND_re_ETC___d5292;
  tUInt8 DEF_NOT_requestR_5_BIT_179_26_27_AND_NOT_requestR__ETC___d879;
  tUInt8 DEF_NOT_requestR_5_BIT_179_26___d727;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2155;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d2153;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d2074;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2085;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d2082;
  tUInt8 DEF_IF_requestR_5_BITS_127_TO_96_5_EQ_0xFFFFFFFF_6_ETC___d2065;
  tUInt8 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d2044;
  tUInt8 DEF_NOT_requestR_5_BITS_159_TO_128_177_EQ_0_178___d1179;
  tUInt8 DEF_NOT_requestR_5_BITS_191_TO_128_71_EQ_0_72___d173;
  tUInt8 DEF_NOT_requestR_5_BITS_194_TO_192_3_EQ_0x1_5___d441;
  tUInt8 DEF_NOT_requestR_5_BITS_194_TO_192_3_EQ_0x2_6___d442;
  tUInt8 DEF_NOT_requestR_5_BITS_194_TO_192_3_EQ_0x3_7___d443;
  tUInt8 DEF_NOT_verbosity_ULE_1_3___d24;
  tUInt32 DEF_requestR_5_BITS_190_TO_180_702_MINUS_1023___d2714;
  tUInt8 DEF_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFFFFF__ETC___d1738;
  tUWide DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d3303;
  tUWide DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1840;
  tUWide DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d2817;
  tUInt32 DEF_NEG_SEXT_requestR_5_BITS_190_TO_180_702_MINUS__ETC___d3241;
  tUInt32 DEF_NEG_SEXT_requestR_5_BITS_190_TO_180_702_MINUS__ETC___d2748;
  tUInt32 DEF_NEG_SEXT_IF_requestR_5_BITS_191_TO_160_7_EQ_0x_ETC___d1923;
  tUInt32 DEF_NEG_SEXT_IF_requestR_5_BITS_191_TO_160_7_EQ_0x_ETC___d1772;
  tUWide DEF_req_opcode_CONCAT_req_f7_CONCAT_req_rs2_CONCAT_ETC___d5454;
  tUWide DEF_req_rs2_CONCAT_req_rm_CONCAT_req_v1_CONCAT_req_ETC___d5453;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2268;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71___d2206;
  tUWide DEF_DONTCARE_CONCAT_DONTCARE_CONCAT_IF_requestR_5__ETC___d133;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2254;
  tUWide DEF__0_CONCAT_requestR_5_BITS_127_TO_64_207___d2208;
  tUWide DEF__0_CONCAT_requestR_5_BITS_63_TO_0_230_231_CONCA_ETC___d2253;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2247;
  tUWide DEF__0_CONCAT_requestR_5_BITS_63_TO_0_230_231_CONCA_ETC___d2246;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2240;
  tUWide DEF__0_CONCAT_requestR_5_BITS_63_TO_0_230_231_CONCA_ETC___d2239;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2233;
  tUWide DEF__0_CONCAT_requestR_5_BITS_63_TO_0_230_231_CONCA_ETC___d2232;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2261;
  tUWide DEF_DONTCARE_CONCAT_IF_requestR_5_BITS_194_TO_192__ETC___d124;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2223;
  tUWide DEF_DONTCARE_CONCAT_IF_requestR_5_BITS_194_TO_192__ETC___d70;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2209;
  tUWide DEF_DONTCARE_CONCAT_IF_requestR_5_BITS_194_TO_192__ETC___d54;
  tUWide DEF__0_CONCAT_requestR_5_BITS_191_TO_128_71_206_CON_ETC___d2216;
  tUWide DEF_DONTCARE_CONCAT_IF_requestR_5_BITS_194_TO_192__ETC___d62;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d134;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d34;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d125;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_127_T_ETC___d42;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d117;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_63_TO_ETC___d116;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d108;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_63_TO_ETC___d107;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d99;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_63_TO_ETC___d98;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d90;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_63_TO_ETC___d89;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d71;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d55;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_191_T_ETC___d63;
  tUWide DEF_req_v1_CONCAT_req_v2_CONCAT_req_v3___d5452;
  tUInt64 DEF_NOT_requestR_5_BITS_190_TO_180_702_EQ_0_712_71_ETC___d2719;
  tUInt32 DEF_NOT_IF_requestR_5_BITS_191_TO_160_7_EQ_0xFFFFF_ETC___d1743;
  tUWide DEF__0_CONCAT_requestR_5_BITS_63_TO_0_230___d2231;
  tUInt8 DEF_IF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_THEN__ETC___d115;
  tUInt8 DEF_IF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_THEN__ETC___d106;
  tUInt8 DEF_IF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_THEN__ETC___d97;
  tUInt8 DEF_IF_requestR_5_BITS_194_TO_192_3_EQ_0x0_4_THEN__ETC___d88;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_requestR_5_BITS_63_TO_ETC___d87;
  tUWide DEF__1_CONCAT_IF_fpu_server_core_response_get_425_B_ETC___d5446;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5421;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5394;
  tUInt8 DEF_x__h227005;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5385;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5374;
  tUInt8 DEF_x__h217051;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5347;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d5333;
  tUWide DEF__1_CONCAT_IF_IF_IF_requestR_5_BITS_191_TO_160_7_ETC___d5270;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_190_TO_180_702__ETC___d4480;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d3352;
  tUWide DEF__1_CONCAT_IF_requestR_5_BITS_190_TO_180_702_EQ__ETC___d3295;
  tUWide DEF__1_CONCAT_0_CONCAT_IF_requestR_5_BITS_191_TO_12_ETC___d3207;
  tUWide DEF__1_CONCAT_NOT_requestR_5_BITS_191_TO_128_71_EQ__ETC___d3053;
  tUWide DEF__1_CONCAT_SEXT_IF_requestR_5_BITS_190_TO_180_70_ETC___d2867;
  tUWide DEF__1_CONCAT_SEXT_IF_requestR_5_BITS_190_TO_180_70_ETC___d2809;
  tUWide DEF__1_CONCAT_0_CONCAT_IF_requestR_5_BITS_159_TO_12_ETC___d2695;
  tUWide DEF__1_CONCAT_NOT_requestR_5_BITS_159_TO_128_177_EQ_ETC___d2511;
  tUWide DEF__1_CONCAT_NOT_requestR_5_BIT_191_74_EQ_requestR_ETC___d2293;
  tUWide DEF__1_CONCAT_NOT_requestR_5_BIT_127_275_283_CONCAT_ETC___d2285;
  tUWide DEF__1_CONCAT_requestR_5_BIT_127_275_CONCAT_request_ETC___d2278;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2199;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2185;
  tUInt8 DEF_x__h55832;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2176;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2165;
  tUInt8 DEF_x__h49884;
  tUWide DEF__1_CONCAT_SEXT_requestR_5_BITS_159_TO_128_177_1_ETC___d2138;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_requestR_5_BITS_159_ETC___d2130;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2122;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d2107;
  tUWide DEF__1_CONCAT_SEXT_IF_IF_requestR_5_BITS_191_TO_160_ETC___d2036;
  tUWide DEF__1_CONCAT_SEXT_IF_IF_requestR_5_BITS_191_TO_160_ETC___d1978;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d1889;
  tUWide DEF__1_CONCAT_IF_IF_requestR_5_BITS_191_TO_160_7_EQ_ETC___d1832;
  tUWide DEF__1_CONCAT_8589934590_CONCAT_IF_requestR_5_BITS__ETC___d1715;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_NOT_requestR_5_BITS_ETC___d1526;
  tUWide DEF__1_CONCAT_8589934590_CONCAT_IF_requestR_5_BITS__ETC___d1171;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_NOT_requestR_5_BITS_ETC___d690;
  tUWide DEF__1_CONCAT_requestR_5_BITS_191_TO_128_71_CONCAT_0___d5401;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_NOT_requestR_5_BITS_ETC___d162;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_requestR_5_BITS_127_ETC___d143;
  tUWide DEF__1_CONCAT_4294967295_CONCAT_NOT_requestR_5_BITS_ETC___d153;
  tUWide DEF__0_CONCAT_DONTCARE___d4;
 
 /* Rules */
 public:
  void RL_rl_reset_begin();
  void RL_rl_reset_end();
  void RL_doFADD_S();
  void RL_doFSUB_S();
  void RL_doFMUL_S();
  void RL_doFMADD_S();
  void RL_doFMSUB_S();
  void RL_doFNMADD_S();
  void RL_doFNMSUB_S();
  void RL_doFDIV_S();
  void RL_doFSQRT_S();
  void RL_doFSGNJ_S();
  void RL_doFSGNJN_S();
  void RL_doFSGNJX_S();
  void RL_doFCVT_S_L();
  void RL_doFCVT_S_LU();
  void RL_doFCVT_S_W();
  void RL_doFCVT_S_WU();
  void RL_doFCVT_L_S();
  void RL_doFCVT_LU_S();
  void RL_doFCVT_W_S();
  void RL_doFCVT_WU_S();
  void RL_doFMIN_S();
  void RL_doFMAX_S();
  void RL_doFMV_W_X();
  void RL_doFMV_X_W();
  void RL_doFEQ_S();
  void RL_doFLT_S();
  void RL_doFLE_S();
  void RL_doFCLASS_S();
  void RL_doFADD_D();
  void RL_doFSUB_D();
  void RL_doFMUL_D();
  void RL_doFMADD_D();
  void RL_doFMSUB_D();
  void RL_doFNMADD_D();
  void RL_doFNMSUB_D();
  void RL_doFDIV_D();
  void RL_doFSQRT_D();
  void RL_doFSGNJ_D();
  void RL_doFSGNJN_D();
  void RL_doFSGNJX_D();
  void RL_doFCVT_D_W();
  void RL_doFCVT_D_WU();
  void RL_doFCVT_W_D();
  void RL_doFCVT_WU_D();
  void RL_doFCVT_D_L();
  void RL_doFCVT_D_LU();
  void RL_doFCVT_L_D();
  void RL_doFCVT_LU_D();
  void RL_doFCVT_S_D();
  void RL_doFCVT_D_S();
  void RL_doFMIN_D();
  void RL_doFMAX_D();
  void RL_doFEQ_D();
  void RL_doFLT_D();
  void RL_doFLE_D();
  void RL_doFMV_D_X();
  void RL_doFMV_X_D();
  void RL_doFCLASS_D();
  void RL_rl_get_fpu_result();
  void RL_rl_drive_fpu_result();
 
 /* Methods */
 public:
  void METH_server_reset_request_put(tUInt8 ARG_server_reset_request_put);
  tUInt8 METH_RDY_server_reset_request_put();
  void METH_server_reset_response_get();
  tUInt8 METH_RDY_server_reset_response_get();
  void METH_req(tUInt8 ARG_req_opcode,
		tUInt8 ARG_req_f7,
		tUInt8 ARG_req_rm,
		tUInt8 ARG_req_rs2,
		tUInt64 ARG_req_v1,
		tUInt64 ARG_req_v2,
		tUInt64 ARG_req_v3,
		tUInt8 ARG_req_valid);
  tUInt8 METH_RDY_req();
  tUInt8 METH_valid();
  tUInt8 METH_RDY_valid();
  tUInt64 METH_word_fst();
  tUInt8 METH_RDY_word_fst();
  tUInt8 METH_word_snd();
  tUInt8 METH_RDY_word_snd();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFBox_Core &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFBox_Core &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFBox_Core &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFBox_Core &backing);
};

#endif /* ifndef __mkFBox_Core_h__ */
