/*
 * Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
 * 
 * On Tue Mar  8 15:41:57 GMT 2022
 * 
 */

/* Generation options: */
#ifndef __mkFBox_Top_h__
#define __mkFBox_Top_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkFBox_Core.h"


/* Class declaration for the mkFBox_Top module */
class MOD_mkFBox_Top : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkFBox_Core INST_fbox_core;
 
 /* Constructor */
 public:
  MOD_mkFBox_Top(tSimStateHdl simHdl, char const *name, Module *parent, tUInt8 ARG_verbosity);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_verbosity;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_server_reset_request_put(tUInt8 ARG_server_reset_request_put);
  tUInt8 METH_RDY_server_reset_request_put();
  void METH_server_reset_response_get();
  tUInt8 METH_RDY_server_reset_response_get();
  void METH_req(tUInt8 ARG_req_opcode,
		tUInt8 ARG_req_f7,
		tUInt8 ARG_req_rm,
		tUInt8 ARG_req_rs2,
		tUInt64 ARG_req_v1,
		tUInt64 ARG_req_v2,
		tUInt64 ARG_req_v3,
		tUInt8 ARG_req_valid);
  tUInt8 METH_RDY_req();
  tUInt8 METH_valid();
  tUInt8 METH_RDY_valid();
  tUInt64 METH_word_fst();
  tUInt8 METH_RDY_word_fst();
  tUInt8 METH_word_snd();
  tUInt8 METH_RDY_word_snd();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFBox_Top &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFBox_Top &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFBox_Top &backing);
};

#endif /* ifndef __mkFBox_Top_h__ */
