/*
 * Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
 * 
 * On Thu Apr 21 16:37:40 CEST 2022
 * 
 */
#include "bluesim_primitives.h"
#include "model_top.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_top::MODEL_top()
{
  top_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_top()
{
  MODEL_top *model = new MODEL_top();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_top &INST_top = *((MOD_top *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_ug_src_canPeekWire_whas__1_AND_ug_src_canPeekW_ETC___d67;
	 tUInt8 DEF_INST_top_DEF_ug_src_1_canPeekWire_whas__9_AND_ug_src_1_canP_ETC___d95;
	 tUInt8 DEF_INST_top_DEF_ug_src_2_canPeekWire_whas__17_AND_ug_src_2_can_ETC___d123;
	 tUInt8 DEF_INST_top_DEF_ug_src_3_canPeekWire_whas__46_AND_ug_src_3_can_ETC___d152;
	 tUInt8 DEF_INST_top_DEF_ug_src_4_canPeekWire_whas__74_AND_ug_src_4_can_ETC___d180;
	 tUInt8 DEF_INST_top_DEF_m_awSent__h1234;
	 tUInt8 DEF_INST_top_DEF_m_reqSent__h1697;
	 tUInt8 DEF_INST_top_DEF_ug_src_canPeekWire_wget____d63;
	 tUInt8 DEF_INST_top_DEF_ug_src_canPeekWire_whas____d61;
	 tUInt8 DEF_INST_top_DEF_ug_src_dropWire_whas____d60;
	 tUInt8 DEF_INST_top_DEF_ug_snk_putWire_whas____d73;
	 tUInt8 DEF_INST_top_DEF_ug_src_1_canPeekWire_wget____d91;
	 tUInt8 DEF_INST_top_DEF_ug_src_1_canPeekWire_whas____d89;
	 tUInt8 DEF_INST_top_DEF_ug_src_1_dropWire_whas____d88;
	 tUInt8 DEF_INST_top_DEF_ug_snk_1_putWire_whas____d101;
	 tUInt8 DEF_INST_top_DEF_ug_src_2_canPeekWire_wget____d119;
	 tUInt8 DEF_INST_top_DEF_ug_src_2_canPeekWire_whas____d117;
	 tUInt8 DEF_INST_top_DEF_ug_src_2_dropWire_whas____d116;
	 tUInt8 DEF_INST_top_DEF_ug_snk_2_putWire_whas____d130;
	 tUInt8 DEF_INST_top_DEF_ug_src_3_canPeekWire_wget____d148;
	 tUInt8 DEF_INST_top_DEF_ug_src_3_canPeekWire_whas____d146;
	 tUInt8 DEF_INST_top_DEF_ug_src_3_dropWire_whas____d145;
	 tUInt8 DEF_INST_top_DEF_ug_snk_3_putWire_whas____d158;
	 tUInt8 DEF_INST_top_DEF_ug_src_4_canPeekWire_wget____d176;
	 tUInt8 DEF_INST_top_DEF_ug_src_4_canPeekWire_whas____d174;
	 tUInt8 DEF_INST_top_DEF_ug_src_4_dropWire_whas____d173;
	 tUInt8 DEF_INST_top_DEF_ug_snk_4_putWire_whas____d187;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connect;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connect;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connect_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connect_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connect_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connect_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connect_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connect_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connect_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connect_4;
	 DEF_INST_top_DEF_m_awSent__h1234 = INST_top.INST_m_awSent.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_AWFlit = !((tUInt8)(INST_top.INST_m_shim_shim_awff_rv.METH_port0__read() >> 42u)) && !DEF_INST_top_DEF_m_awSent__h1234;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_AWFlit = DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_AWFlit;
	 INST_top.DEF_m_shim_shim_wff_rv_port0__read____d13 = INST_top.INST_m_shim_shim_wff_rv.METH_port0__read();
	 DEF_INST_top_DEF_m_reqSent__h1697 = INST_top.INST_m_reqSent.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_WFlit = !INST_top.DEF_m_shim_shim_wff_rv_port0__read____d13.get_bits_in_word8(4u,
															      17u,
															      1u) && !DEF_INST_top_DEF_m_reqSent__h1697;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_WFlit = DEF_INST_top_DEF_CAN_FIRE_RL_m_putAXI4_WFlit;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setCanPeek;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setCanPeek;
	 INST_top.DEF_s_shim_shim_bff_rv_port1__read____d113 = INST_top.INST_s_shim_shim_bff_rv.METH_port1__read();
	 INST_top.DEF_s_shim_shim_bff_rv_port1__read__13_BIT_2___d114 = (tUInt8)((INST_top.DEF_s_shim_shim_bff_rv_port1__read____d113) >> 2u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setPeek = INST_top.DEF_s_shim_shim_bff_rv_port1__read__13_BIT_2___d114;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_setPeek;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setCanPeek;
	 INST_top.DEF_m_shim_shim_arff_rv_port1__read____d142 = INST_top.INST_m_shim_shim_arff_rv.METH_port1__read();
	 INST_top.DEF_m_shim_shim_arff_rv_port1__read__42_BIT_42___d143 = (tUInt8)((INST_top.DEF_m_shim_shim_arff_rv_port1__read____d142) >> 42u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setPeek = INST_top.DEF_m_shim_shim_arff_rv_port1__read__42_BIT_42___d143;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_setPeek;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setCanPeek;
	 INST_top.DEF_s_shim_shim_rff_rv_port1__read____d170 = INST_top.INST_s_shim_shim_rff_rv.METH_port1__read();
	 INST_top.DEF_s_shim_shim_rff_rv_port1__read__70_BIT_131___d171 = INST_top.DEF_s_shim_shim_rff_rv_port1__read____d170.get_bits_in_word8(4u,
																		3u,
																		1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setPeek = INST_top.DEF_s_shim_shim_rff_rv_port1__read__70_BIT_131___d171;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_setPeek;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setCanPeek;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_AWFlit)
	   INST_top.RL_m_putAXI4_AWFlit();
	 INST_top.DEF_m_shim_shim_awff_rv_port1__read____d57 = INST_top.INST_m_shim_shim_awff_rv.METH_port1__read();
	 INST_top.DEF_m_shim_shim_awff_rv_port1__read__7_BIT_42___d58 = (tUInt8)((INST_top.DEF_m_shim_shim_awff_rv_port1__read____d57) >> 42u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setPeek = INST_top.DEF_m_shim_shim_awff_rv_port1__read__7_BIT_42___d58;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_setPeek;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m_putAXI4_WFlit)
	   INST_top.RL_m_putAXI4_WFlit();
	 INST_top.DEF_m_shim_shim_wff_rv_port1__read____d85 = INST_top.INST_m_shim_shim_wff_rv.METH_port1__read();
	 INST_top.DEF_m_shim_shim_wff_rv_port1__read__5_BIT_145___d86 = INST_top.DEF_m_shim_shim_wff_rv_port1__read____d85.get_bits_in_word8(4u,
																	     17u,
																	     1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setPeek = INST_top.DEF_m_shim_shim_wff_rv_port1__read__5_BIT_145___d86;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_setPeek;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_setCanPut)
	   INST_top.RL_ug_snk_1_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_setCanPut)
	   INST_top.RL_ug_snk_2_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_setCanPut)
	   INST_top.RL_ug_snk_3_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_setCanPut)
	   INST_top.RL_ug_snk_4_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_setCanPut)
	   INST_top.RL_ug_snk_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setCanPeek)
	   INST_top.RL_ug_src_1_setCanPeek();
	 DEF_INST_top_DEF_ug_src_1_canPeekWire_whas____d89 = INST_top.INST_ug_src_1_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_ug_src_1_canPeekWire_wget____d91 = INST_top.INST_ug_src_1_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_ug_src_1_canPeekWire_whas__9_AND_ug_src_1_canP_ETC___d95 = DEF_INST_top_DEF_ug_src_1_canPeekWire_whas____d89 && DEF_INST_top_DEF_ug_src_1_canPeekWire_wget____d91;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connect_1 = DEF_INST_top_DEF_ug_src_1_canPeekWire_whas__9_AND_ug_src_1_canP_ETC___d95 && (INST_top.INST_ug_snk_1_canPutWire.METH_whas() && INST_top.INST_ug_snk_1_canPutWire.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_connect_1 = DEF_INST_top_DEF_CAN_FIRE_RL_connect_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_setPeek)
	   INST_top.RL_ug_src_1_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connect_1)
	   INST_top.RL_connect_1();
	 INST_top.DEF_s_shim_shim_wff_rv_port0__read____d98 = INST_top.INST_s_shim_shim_wff_rv.METH_port0__read();
	 DEF_INST_top_DEF_ug_snk_1_putWire_whas____d101 = INST_top.INST_ug_snk_1_putWire.METH_whas();
	 INST_top.DEF_s_shim_shim_wff_rv_port0__read__8_BIT_145___d99 = INST_top.DEF_s_shim_shim_wff_rv_port0__read____d98.get_bits_in_word8(4u,
																	     17u,
																	     1u);
	 INST_top.DEF_NOT_s_shim_shim_wff_rv_port0__read__8_BIT_145_9___d100 = !(INST_top.DEF_s_shim_shim_wff_rv_port0__read__8_BIT_145___d99);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_doPut = INST_top.DEF_NOT_s_shim_shim_wff_rv_port0__read__8_BIT_145_9___d100 && DEF_INST_top_DEF_ug_snk_1_putWire_whas____d101;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_warnDoPut = DEF_INST_top_DEF_ug_snk_1_putWire_whas____d101 && INST_top.DEF_s_shim_shim_wff_rv_port0__read__8_BIT_145___d99;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_1_warnDoPut;
	 DEF_INST_top_DEF_ug_src_1_dropWire_whas____d88 = INST_top.INST_ug_src_1_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_doDrop = INST_top.DEF_m_shim_shim_wff_rv_port1__read__5_BIT_145___d86 && (DEF_INST_top_DEF_ug_src_1_dropWire_whas____d88 && DEF_INST_top_DEF_ug_src_1_canPeekWire_whas__9_AND_ug_src_1_canP_ETC___d95);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_warnDoDrop = (DEF_INST_top_DEF_ug_src_1_dropWire_whas____d88 && (!DEF_INST_top_DEF_ug_src_1_canPeekWire_whas____d89 || !DEF_INST_top_DEF_ug_src_1_canPeekWire_wget____d91)) && !DEF_INST_top_DEF_CAN_FIRE_RL_connect_1;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_1_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_doPut)
	   INST_top.RL_ug_snk_1_doPut();
	 INST_top.DEF_s_shim_shim_wff_rv_port1__read____d50 = INST_top.INST_s_shim_shim_wff_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_WFlit = INST_top.DEF_s_shim_shim_wff_rv_port1__read____d50.get_bits_in_word8(4u,
															     17u,
															     1u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_WFlit = DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_WFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_doDrop)
	   INST_top.RL_ug_src_1_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setCanPeek)
	   INST_top.RL_ug_src_2_setCanPeek();
	 DEF_INST_top_DEF_ug_src_2_canPeekWire_whas____d117 = INST_top.INST_ug_src_2_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_ug_src_2_canPeekWire_wget____d119 = INST_top.INST_ug_src_2_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_ug_src_2_canPeekWire_whas__17_AND_ug_src_2_can_ETC___d123 = DEF_INST_top_DEF_ug_src_2_canPeekWire_whas____d117 && DEF_INST_top_DEF_ug_src_2_canPeekWire_wget____d119;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connect_2 = DEF_INST_top_DEF_ug_src_2_canPeekWire_whas__17_AND_ug_src_2_can_ETC___d123 && (INST_top.INST_ug_snk_2_canPutWire.METH_whas() && INST_top.INST_ug_snk_2_canPutWire.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_connect_2 = DEF_INST_top_DEF_CAN_FIRE_RL_connect_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_setPeek)
	   INST_top.RL_ug_src_2_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connect_2)
	   INST_top.RL_connect_2();
	 DEF_INST_top_DEF_ug_snk_2_putWire_whas____d130 = INST_top.INST_ug_snk_2_putWire.METH_whas();
	 INST_top.DEF_m_shim_shim_bff_rv_port0__read__27_BIT_2___d128 = (tUInt8)(INST_top.INST_m_shim_shim_bff_rv.METH_port0__read() >> 2u);
	 INST_top.DEF_NOT_m_shim_shim_bff_rv_port0__read__27_BIT_2_28___d129 = !(INST_top.DEF_m_shim_shim_bff_rv_port0__read__27_BIT_2___d128);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_doPut = INST_top.DEF_NOT_m_shim_shim_bff_rv_port0__read__27_BIT_2_28___d129 && DEF_INST_top_DEF_ug_snk_2_putWire_whas____d130;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_warnDoPut = DEF_INST_top_DEF_ug_snk_2_putWire_whas____d130 && INST_top.DEF_m_shim_shim_bff_rv_port0__read__27_BIT_2___d128;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_2_warnDoPut;
	 DEF_INST_top_DEF_ug_src_2_dropWire_whas____d116 = INST_top.INST_ug_src_2_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_doDrop = INST_top.DEF_s_shim_shim_bff_rv_port1__read__13_BIT_2___d114 && (DEF_INST_top_DEF_ug_src_2_dropWire_whas____d116 && DEF_INST_top_DEF_ug_src_2_canPeekWire_whas__17_AND_ug_src_2_can_ETC___d123);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_warnDoDrop = (DEF_INST_top_DEF_ug_src_2_dropWire_whas____d116 && (!DEF_INST_top_DEF_ug_src_2_canPeekWire_whas____d117 || !DEF_INST_top_DEF_ug_src_2_canPeekWire_wget____d119)) && !DEF_INST_top_DEF_CAN_FIRE_RL_connect_2;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_2_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_doPut)
	   INST_top.RL_ug_snk_2_doPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_doDrop)
	   INST_top.RL_ug_src_2_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setCanPeek)
	   INST_top.RL_ug_src_3_setCanPeek();
	 DEF_INST_top_DEF_ug_src_3_canPeekWire_whas____d146 = INST_top.INST_ug_src_3_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_ug_src_3_canPeekWire_wget____d148 = INST_top.INST_ug_src_3_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_ug_src_3_canPeekWire_whas__46_AND_ug_src_3_can_ETC___d152 = DEF_INST_top_DEF_ug_src_3_canPeekWire_whas____d146 && DEF_INST_top_DEF_ug_src_3_canPeekWire_wget____d148;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connect_3 = DEF_INST_top_DEF_ug_src_3_canPeekWire_whas__46_AND_ug_src_3_can_ETC___d152 && (INST_top.INST_ug_snk_3_canPutWire.METH_whas() && INST_top.INST_ug_snk_3_canPutWire.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_connect_3 = DEF_INST_top_DEF_CAN_FIRE_RL_connect_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_setPeek)
	   INST_top.RL_ug_src_3_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connect_3)
	   INST_top.RL_connect_3();
	 DEF_INST_top_DEF_ug_snk_3_putWire_whas____d158 = INST_top.INST_ug_snk_3_putWire.METH_whas();
	 INST_top.DEF_s_shim_shim_arff_rv_port0__read__55_BIT_42___d156 = (tUInt8)(INST_top.INST_s_shim_shim_arff_rv.METH_port0__read() >> 42u);
	 INST_top.DEF_NOT_s_shim_shim_arff_rv_port0__read__55_BIT_42_56___d157 = !(INST_top.DEF_s_shim_shim_arff_rv_port0__read__55_BIT_42___d156);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_doPut = INST_top.DEF_NOT_s_shim_shim_arff_rv_port0__read__55_BIT_42_56___d157 && DEF_INST_top_DEF_ug_snk_3_putWire_whas____d158;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_warnDoPut = DEF_INST_top_DEF_ug_snk_3_putWire_whas____d158 && INST_top.DEF_s_shim_shim_arff_rv_port0__read__55_BIT_42___d156;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_3_warnDoPut;
	 DEF_INST_top_DEF_ug_src_3_dropWire_whas____d145 = INST_top.INST_ug_src_3_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_doDrop = INST_top.DEF_m_shim_shim_arff_rv_port1__read__42_BIT_42___d143 && (DEF_INST_top_DEF_ug_src_3_dropWire_whas____d145 && DEF_INST_top_DEF_ug_src_3_canPeekWire_whas__46_AND_ug_src_3_can_ETC___d152);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_warnDoDrop = (DEF_INST_top_DEF_ug_src_3_dropWire_whas____d145 && (!DEF_INST_top_DEF_ug_src_3_canPeekWire_whas____d146 || !DEF_INST_top_DEF_ug_src_3_canPeekWire_wget____d148)) && !DEF_INST_top_DEF_CAN_FIRE_RL_connect_3;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_3_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_doPut)
	   INST_top.RL_ug_snk_3_doPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_doDrop)
	   INST_top.RL_ug_src_3_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setCanPeek)
	   INST_top.RL_ug_src_setCanPeek();
	 DEF_INST_top_DEF_ug_src_canPeekWire_whas____d61 = INST_top.INST_ug_src_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_ug_src_canPeekWire_wget____d63 = INST_top.INST_ug_src_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_ug_src_canPeekWire_whas__1_AND_ug_src_canPeekW_ETC___d67 = DEF_INST_top_DEF_ug_src_canPeekWire_whas____d61 && DEF_INST_top_DEF_ug_src_canPeekWire_wget____d63;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connect = DEF_INST_top_DEF_ug_src_canPeekWire_whas__1_AND_ug_src_canPeekW_ETC___d67 && (INST_top.INST_ug_snk_canPutWire.METH_whas() && INST_top.INST_ug_snk_canPutWire.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_connect = DEF_INST_top_DEF_CAN_FIRE_RL_connect;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setCanPeek)
	   INST_top.RL_ug_src_4_setCanPeek();
	 DEF_INST_top_DEF_ug_src_4_canPeekWire_whas____d174 = INST_top.INST_ug_src_4_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_ug_src_4_canPeekWire_wget____d176 = INST_top.INST_ug_src_4_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_ug_src_4_canPeekWire_whas__74_AND_ug_src_4_can_ETC___d180 = DEF_INST_top_DEF_ug_src_4_canPeekWire_whas____d174 && DEF_INST_top_DEF_ug_src_4_canPeekWire_wget____d176;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connect_4 = DEF_INST_top_DEF_ug_src_4_canPeekWire_whas__74_AND_ug_src_4_can_ETC___d180 && (INST_top.INST_ug_snk_4_canPutWire.METH_whas() && INST_top.INST_ug_snk_4_canPutWire.METH_wget());
	 DEF_INST_top_DEF_WILL_FIRE_RL_connect_4 = DEF_INST_top_DEF_CAN_FIRE_RL_connect_4;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_setPeek)
	   INST_top.RL_ug_src_4_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connect_4)
	   INST_top.RL_connect_4();
	 INST_top.DEF_m_shim_shim_rff_rv_port0__read____d184 = INST_top.INST_m_shim_shim_rff_rv.METH_port0__read();
	 DEF_INST_top_DEF_ug_snk_4_putWire_whas____d187 = INST_top.INST_ug_snk_4_putWire.METH_whas();
	 INST_top.DEF_m_shim_shim_rff_rv_port0__read__84_BIT_131___d185 = INST_top.DEF_m_shim_shim_rff_rv_port0__read____d184.get_bits_in_word8(4u,
																		3u,
																		1u);
	 INST_top.DEF_NOT_m_shim_shim_rff_rv_port0__read__84_BIT_131_85___d186 = !(INST_top.DEF_m_shim_shim_rff_rv_port0__read__84_BIT_131___d185);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_doPut = INST_top.DEF_NOT_m_shim_shim_rff_rv_port0__read__84_BIT_131_85___d186 && DEF_INST_top_DEF_ug_snk_4_putWire_whas____d187;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_warnDoPut = DEF_INST_top_DEF_ug_snk_4_putWire_whas____d187 && INST_top.DEF_m_shim_shim_rff_rv_port0__read__84_BIT_131___d185;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_4_warnDoPut;
	 DEF_INST_top_DEF_ug_src_4_dropWire_whas____d173 = INST_top.INST_ug_src_4_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_doDrop = INST_top.DEF_s_shim_shim_rff_rv_port1__read__70_BIT_131___d171 && (DEF_INST_top_DEF_ug_src_4_dropWire_whas____d173 && DEF_INST_top_DEF_ug_src_4_canPeekWire_whas__74_AND_ug_src_4_can_ETC___d180);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_warnDoDrop = (DEF_INST_top_DEF_ug_src_4_dropWire_whas____d173 && (!DEF_INST_top_DEF_ug_src_4_canPeekWire_whas____d174 || !DEF_INST_top_DEF_ug_src_4_canPeekWire_wget____d176)) && !DEF_INST_top_DEF_CAN_FIRE_RL_connect_4;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_4_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_doPut)
	   INST_top.RL_ug_snk_4_doPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_doDrop)
	   INST_top.RL_ug_src_4_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_setPeek)
	   INST_top.RL_ug_src_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connect)
	   INST_top.RL_connect();
	 DEF_INST_top_DEF_ug_snk_putWire_whas____d73 = INST_top.INST_ug_snk_putWire.METH_whas();
	 INST_top.DEF_s_shim_shim_awff_rv_port0__read__0_BIT_42___d71 = (tUInt8)(INST_top.INST_s_shim_shim_awff_rv.METH_port0__read() >> 42u);
	 INST_top.DEF_NOT_s_shim_shim_awff_rv_port0__read__0_BIT_42_1___d72 = !(INST_top.DEF_s_shim_shim_awff_rv_port0__read__0_BIT_42___d71);
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_doPut = INST_top.DEF_NOT_s_shim_shim_awff_rv_port0__read__0_BIT_42_1___d72 && DEF_INST_top_DEF_ug_snk_putWire_whas____d73;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_warnDoPut = DEF_INST_top_DEF_ug_snk_putWire_whas____d73 && INST_top.DEF_s_shim_shim_awff_rv_port0__read__0_BIT_42___d71;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_ug_snk_warnDoPut;
	 DEF_INST_top_DEF_ug_src_dropWire_whas____d60 = INST_top.INST_ug_src_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_doDrop = INST_top.DEF_m_shim_shim_awff_rv_port1__read__7_BIT_42___d58 && (DEF_INST_top_DEF_ug_src_dropWire_whas____d60 && DEF_INST_top_DEF_ug_src_canPeekWire_whas__1_AND_ug_src_canPeekW_ETC___d67);
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_warnDoDrop = (DEF_INST_top_DEF_ug_src_dropWire_whas____d60 && (!DEF_INST_top_DEF_ug_src_canPeekWire_whas____d61 || !DEF_INST_top_DEF_ug_src_canPeekWire_wget____d63)) && !DEF_INST_top_DEF_CAN_FIRE_RL_connect;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_ug_src_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_doPut)
	   INST_top.RL_ug_snk_doPut();
	 INST_top.DEF_s_shim_shim_awff_rv_port1__read____d28 = INST_top.INST_s_shim_shim_awff_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_AWFlit = (tUInt8)((INST_top.DEF_s_shim_shim_awff_rv_port1__read____d28) >> 42u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_AWFlit = DEF_INST_top_DEF_CAN_FIRE_RL_s_getAXI4_AWFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_doDrop)
	   INST_top.RL_ug_src_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_warnDoDrop)
	   INST_top.RL_ug_src_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_warnDoPut)
	   INST_top.RL_ug_snk_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_AWFlit)
	   INST_top.RL_s_getAXI4_AWFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_1_warnDoDrop)
	   INST_top.RL_ug_src_1_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_1_warnDoPut)
	   INST_top.RL_ug_snk_1_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_s_getAXI4_WFlit)
	   INST_top.RL_s_getAXI4_WFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_2_warnDoDrop)
	   INST_top.RL_ug_src_2_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_2_warnDoPut)
	   INST_top.RL_ug_snk_2_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_3_warnDoDrop)
	   INST_top.RL_ug_src_3_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_3_warnDoPut)
	   INST_top.RL_ug_snk_3_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_src_4_warnDoDrop)
	   INST_top.RL_ug_src_4_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ug_snk_4_warnDoPut)
	   INST_top.RL_ug_snk_4_warnDoPut();
	 INST_top.INST_ug_snk_4_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_4_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_4_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_4_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_4_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_3_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_3_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_3_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_3_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_3_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_2_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_2_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_2_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_2_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_2_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_1_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_1_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_1_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_1_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_1_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_snk_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_ug_src_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_shim_shim_rff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_shim_shim_arff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_shim_shim_bff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_shim_shim_wff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s_shim_shim_awff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_shim_shim_rff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_shim_shim_arff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_shim_shim_bff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_shim_shim_wff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m_shim_shim_awff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_m_shim_shim_awff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_shim_shim_wff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_shim_shim_bff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_shim_shim_arff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_shim_shim_rff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m_nextWriteAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_awSent.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_reqSent.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_rspCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s_shim_shim_awff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_shim_shim_wff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_shim_shim_bff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_shim_shim_arff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s_shim_shim_rff_rv.rst_tick_clk((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_top::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  top_instance = new MOD_top(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (top_instance->INST_m_shim_shim_awff_rv.set_clk_0)("CLK");
  (top_instance->INST_m_shim_shim_wff_rv.set_clk_0)("CLK");
  (top_instance->INST_m_shim_shim_bff_rv.set_clk_0)("CLK");
  (top_instance->INST_m_shim_shim_arff_rv.set_clk_0)("CLK");
  (top_instance->INST_m_shim_shim_rff_rv.set_clk_0)("CLK");
  (top_instance->INST_s_shim_shim_awff_rv.set_clk_0)("CLK");
  (top_instance->INST_s_shim_shim_wff_rv.set_clk_0)("CLK");
  (top_instance->INST_s_shim_shim_bff_rv.set_clk_0)("CLK");
  (top_instance->INST_s_shim_shim_arff_rv.set_clk_0)("CLK");
  (top_instance->INST_s_shim_shim_rff_rv.set_clk_0)("CLK");
  (top_instance->INST_ug_src_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_peekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_dropWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_putWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_1_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_1_peekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_1_dropWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_1_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_1_putWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_2_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_2_peekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_2_dropWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_2_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_2_putWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_3_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_3_peekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_3_dropWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_3_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_3_putWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_4_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_4_peekWire.set_clk_0)("CLK");
  (top_instance->INST_ug_src_4_dropWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_4_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_ug_snk_4_putWire.set_clk_0)("CLK");
  (top_instance->set_clk_0)("CLK");
}
void MODEL_top::destroy_model()
{
  delete top_instance;
  top_instance = NULL;
}
void MODEL_top::reset_model(bool asserted)
{
  (top_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_top::get_instance()
{
  return top_instance;
}

/* Fill in version numbers */
void MODEL_top::get_version(char const **name, char const **build)
{
  *name = "2021.07";
  *build = "4cac6eb";
}

/* Get the model creation time */
time_t MODEL_top::get_creation_time()
{
  
  /* Thu Apr 21 14:37:40 UTC 2022 */
  return 1650551860llu;
}

/* State dumping function */
void MODEL_top::dump_state()
{
  (top_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_top & top_backing(tSimStateHdl simHdl)
{
  static MOD_top *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_top(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_top::dump_VCD_defs()
{
  (top_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_top::dump_VCD(tVCDDumpType dt)
{
  (top_instance->dump_VCD)(dt, vcd_depth(sim_hdl), top_backing(sim_hdl));
}
