/*
 * Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
 * 
 * On Mon Dec 20 17:57:18 CET 2021
 * 
 */
#include "bluesim_primitives.h"
#include "model_top.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_top::MODEL_top()
{
  top_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_top()
{
  MODEL_top *model = new MODEL_top();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_top &INST_top = *((MOD_top *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas__03_AND_merged__ETC___d109;
	 tUInt8 DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas__16_AND_merged_0_ETC___d122;
	 tUInt8 DEF_INST_top_DEF_merged_0_awff_i_notEmpty__35_AND_merged_0_wff__ETC___d137;
	 tUInt8 DEF_INST_top_DEF_selectInput_0_whas__54_AND_selectInput_0_wget__55___d256;
	 tUInt8 DEF_INST_top_DEF_NOT_moreFlits_48_BIT_2_49___d250;
	 tUInt8 DEF_INST_top_DEF_selectInput_0_1_whas__60_AND_selectInput_0_1_w_ETC___d362;
	 tUInt8 DEF_INST_top_DEF_selectInput_1_whas__71_AND_selectInput_1_wget__72___d373;
	 tUInt8 DEF_INST_top_DEF_NOT_moreFlits_1_24_BIT_3_25___d326;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_24_BIT_0_92_AND_outputCanPut_0_1_w_ETC___d393;
	 tUInt8 DEF_INST_top_DEF_selectInput_1_0_whas__47_AND_selectInput_1_0_w_ETC___d449;
	 tUInt8 DEF_INST_top_DEF_NOT_moreFlits_1_1_41_BIT_2_42___d443;
	 tUInt8 DEF_INST_top_DEF_selectInput_1_0_1_whas__48_AND_selectInput_1_0_ETC___d550;
	 tUInt8 DEF_INST_top_DEF_selectInput_1_1_whas__59_AND_selectInput_1_1_w_ETC___d561;
	 tUInt8 DEF_INST_top_DEF_NOT_moreFlits_1_2_12_BIT_3_13___d514;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_2_12_BIT_0_84_AND_outputCanPut_1_0_ETC___d585;
	 tUInt8 DEF_INST_top_DEF_moreFlits_48_BIT_2___d249;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_1_41_BIT_2___d442;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_24_BIT_3___d325;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_2_12_BIT_3___d513;
	 tUInt8 DEF_INST_top_DEF_m1_awSent__h1237;
	 tUInt8 DEF_INST_top_DEF_m1_reqSent__h1699;
	 tUInt8 DEF_INST_top_DEF_merged_0_awug_canPeekWire_wget____d105;
	 tUInt8 DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas____d103;
	 tUInt8 DEF_INST_top_DEF_merged_0_awug_dropWire_whas____d102;
	 tUInt8 DEF_INST_top_DEF_merged_0_wug_canPeekWire_wget____d118;
	 tUInt8 DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas____d116;
	 tUInt8 DEF_INST_top_DEF_merged_0_wug_dropWire_whas____d115;
	 tUInt8 DEF_INST_top_DEF_merged_0_wff_i_notEmpty____d136;
	 tUInt8 DEF_INST_top_DEF_merged_0_doDrop_whas____d144;
	 tUInt8 DEF_INST_top_DEF_split_0_awug_putWire_whas____d162;
	 tUInt8 DEF_INST_top_DEF_split_0_wug_putWire_whas____d170;
	 tUInt8 DEF_INST_top_DEF_split_0_doPut_whas____d175;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1___d324;
	 tUInt8 DEF_INST_top_DEF_moreFlits_1_2___d512;
	 tUInt8 DEF_INST_top_DEF_noRouteSlv_rspFF_i_notEmpty____d296;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_m1_getAXI4_BFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_m1_getAXI4_BFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_AWFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_WFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_s1_putAXI4_BFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_s1_putAXI4_BFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setCanPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setPeek;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setPeek;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_warnDoDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_doDrop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_doDrop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_passFlit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_passFlit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genFirst;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genFirst;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genOther;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genOther;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_setCanPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_setCanPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_warnDoPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_doPut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_doPut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putFirst;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putFirst;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putOther;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putOther;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_33;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_33;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_35;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_35;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_47;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_47;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_49;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_49;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_58;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_58;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_60;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_60;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_72;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_72;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_74;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_74;
	 DEF_INST_top_DEF_m1_awSent__h1237 = INST_top.INST_m1_awSent.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_AWFlit = !((tUInt8)(INST_top.INST_m1_shim_shim_awff_rv.METH_port0__read() >> 42u)) && !DEF_INST_top_DEF_m1_awSent__h1237;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_AWFlit = DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_AWFlit;
	 INST_top.DEF_m1_shim_shim_wff_rv_port0__read____d13 = INST_top.INST_m1_shim_shim_wff_rv.METH_port0__read();
	 DEF_INST_top_DEF_m1_reqSent__h1699 = INST_top.INST_m1_reqSent.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_WFlit = !INST_top.DEF_m1_shim_shim_wff_rv_port0__read____d13.get_bits_in_word8(4u,
																17u,
																1u) && !DEF_INST_top_DEF_m1_reqSent__h1699;
	 DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_WFlit = DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_WFlit;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setCanPeek;
	 INST_top.DEF_x__h6715 = INST_top.INST_merged_0_flitLeft.METH_read();
	 DEF_INST_top_DEF_merged_0_wff_i_notEmpty____d136 = INST_top.INST_merged_0_wff.METH_i_notEmpty();
	 INST_top.DEF_merged_0_flitLeft_38_EQ_0___d139 = (INST_top.DEF_x__h6715) == (tUInt8)0u;
	 DEF_INST_top_DEF_merged_0_awff_i_notEmpty__35_AND_merged_0_wff__ETC___d137 = INST_top.INST_merged_0_awff.METH_i_notEmpty() && DEF_INST_top_DEF_merged_0_wff_i_notEmpty____d136;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_passFlit = DEF_INST_top_DEF_merged_0_awff_i_notEmpty__35_AND_merged_0_wff__ETC___d137 && INST_top.DEF_merged_0_flitLeft_38_EQ_0___d139;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_passFlit = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_passFlit;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setCanPeek = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setCanPeek = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setCanPeek;
	 DEF_INST_top_DEF_CAN_FIRE_RL_s1_putAXI4_BFlit = INST_top.INST_s1_awResp.METH_i_notEmpty() && (INST_top.INST_s1_wResp.METH_i_notEmpty() && !((tUInt8)(INST_top.INST_s1_shim_shim_bff_rv.METH_port0__read() >> 2u)));
	 DEF_INST_top_DEF_WILL_FIRE_RL_s1_putAXI4_BFlit = DEF_INST_top_DEF_CAN_FIRE_RL_s1_putAXI4_BFlit;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire = DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire_1 = DEF_INST_top_DEF_CAN_FIRE_RL_set_dflt_output_canPut_wire_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_1 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_2 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_2 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_3 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_3 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_4 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_4 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_4;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_5 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_5 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_canPeek_wire_5;
	 INST_top.DEF_merged_0_wff_notEmpty____d207 = INST_top.INST_merged_0_wff.METH_notEmpty();
	 INST_top.DEF_IF_merged_0_flitLeft_38_EQ_0_39_THEN_merged_0__ETC___d209 = INST_top.DEF_merged_0_flitLeft_38_EQ_0___d139 ? INST_top.INST_merged_0_awff.METH_notEmpty() && INST_top.DEF_merged_0_wff_notEmpty____d207 : INST_top.DEF_merged_0_wff_notEmpty____d207;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires = INST_top.DEF_IF_merged_0_flitLeft_38_EQ_0_39_THEN_merged_0__ETC___d209 && DEF_INST_top_DEF_merged_0_wff_i_notEmpty____d136;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires;
	 DEF_INST_top_DEF_noRouteSlv_rspFF_i_notEmpty____d296 = INST_top.INST_noRouteSlv_rspFF.METH_i_notEmpty();
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_1 = DEF_INST_top_DEF_noRouteSlv_rspFF_i_notEmpty____d296;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_1 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_1;
	 INST_top.DEF_m1_shim_shim_arff_rv_port1__read____d413 = INST_top.INST_m1_shim_shim_arff_rv.METH_port1__read();
	 INST_top.DEF_m1_shim_shim_arff_rv_port1__read__13_BIT_42___d414 = (tUInt8)((INST_top.DEF_m1_shim_shim_arff_rv_port1__read____d413) >> 42u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_3 = INST_top.DEF_m1_shim_shim_arff_rv_port1__read__13_BIT_42___d414;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_3 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_3;
	 INST_top.DEF_x__h40428 = INST_top.INST_noRouteSlv_1_flitCount.METH_read();
	 INST_top.DEF_noRouteSlv_1_flitCount_21_EQ_0___d422 = (INST_top.DEF_x__h40428) == 0u;
	 INST_top.DEF_NOT_noRouteSlv_1_flitCount_21_EQ_0_22___d483 = !(INST_top.DEF_noRouteSlv_1_flitCount_21_EQ_0___d422);
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_4 = INST_top.DEF_NOT_noRouteSlv_1_flitCount_21_EQ_0_22___d483;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_4 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_4;
	 INST_top.DEF_s1_shim_shim_rff_rv_port1__read____d486 = INST_top.INST_s1_shim_shim_rff_rv.METH_port1__read();
	 INST_top.DEF_s1_shim_shim_rff_rv_port1__read__86_BIT_131___d487 = INST_top.DEF_s1_shim_shim_rff_rv_port1__read____d486.get_bits_in_word8(4u,
																		  3u,
																		  1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_5 = INST_top.DEF_s1_shim_shim_rff_rv_port1__read__86_BIT_131___d487;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_5 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_5;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire = DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_1 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_1 = DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_2 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_2 = DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_3 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_3 = DEF_INST_top_DEF_CAN_FIRE_RL_set_output_canPut_wire_3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_setCanPut = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_setCanPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_setCanPut;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_33 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_33 = DEF_INST_top_DEF_CAN_FIRE___me_check_33;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_35 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_35 = DEF_INST_top_DEF_CAN_FIRE___me_check_35;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_47 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_47 = DEF_INST_top_DEF_CAN_FIRE___me_check_47;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_49 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_49 = DEF_INST_top_DEF_CAN_FIRE___me_check_49;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_58 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_58 = DEF_INST_top_DEF_CAN_FIRE___me_check_58;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_60 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_60 = DEF_INST_top_DEF_CAN_FIRE___me_check_60;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_72 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_72 = DEF_INST_top_DEF_CAN_FIRE___me_check_72;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_74 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_74 = DEF_INST_top_DEF_CAN_FIRE___me_check_74;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire)
	   INST_top.RL_set_dflt_output_canPut_wire();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_dflt_output_canPut_wire_1)
	   INST_top.RL_set_dflt_output_canPut_wire_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire)
	   INST_top.RL_set_input_canPeek_wire();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_1)
	   INST_top.RL_set_input_canPeek_wire_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_3)
	   INST_top.RL_set_input_canPeek_wire_3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_4)
	   INST_top.RL_set_input_canPeek_wire_4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_5)
	   INST_top.RL_set_input_canPeek_wire_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_1)
	   INST_top.RL_set_input_peek_wires_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_3)
	   INST_top.RL_set_input_peek_wires_3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_5)
	   INST_top.RL_set_input_peek_wires_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_1)
	   INST_top.RL_set_output_canPut_wire_1();
	 INST_top.DEF_outputCanPut_0_1_wget____d311 = INST_top.INST_outputCanPut_0_1.METH_wget();
	 INST_top.DEF_outputCanPut_0_1_whas____d310 = INST_top.INST_outputCanPut_0_1.METH_whas();
	 INST_top.DEF_inputCanPeek_0_1_wget____d305 = INST_top.INST_inputCanPeek_0_1.METH_wget();
	 INST_top.DEF_inputCanPeek_0_1_whas____d304 = INST_top.INST_inputCanPeek_0_1.METH_whas();
	 DEF_INST_top_DEF_moreFlits_1___d324 = INST_top.INST_moreFlits_1.METH_read();
	 DEF_INST_top_DEF_moreFlits_1_24_BIT_3___d325 = (tUInt8)(DEF_INST_top_DEF_moreFlits_1___d324 >> 3u);
	 INST_top.DEF_outputCanPut_0_1_whas__10_AND_outputCanPut_0_1_ETC___d312 = INST_top.DEF_outputCanPut_0_1_whas____d310 && INST_top.DEF_outputCanPut_0_1_wget____d311;
	 DEF_INST_top_DEF_moreFlits_1_24_BIT_0_92_AND_outputCanPut_0_1_w_ETC___d393 = (tUInt8)((tUInt8)1u & DEF_INST_top_DEF_moreFlits_1___d324) && INST_top.DEF_outputCanPut_0_1_whas__10_AND_outputCanPut_0_1_ETC___d312;
	 INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d306 = INST_top.DEF_inputCanPeek_0_1_whas____d304 && INST_top.DEF_inputCanPeek_0_1_wget____d305;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_1 = DEF_INST_top_DEF_noRouteSlv_rspFF_i_notEmpty____d296 && (((DEF_INST_top_DEF_moreFlits_1_24_BIT_3___d325 && (tUInt8)((tUInt8)1u & (DEF_INST_top_DEF_moreFlits_1___d324 >> 1u))) && INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d306) && DEF_INST_top_DEF_moreFlits_1_24_BIT_0_92_AND_outputCanPut_0_1_w_ETC___d393);
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit_1 = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_2)
	   INST_top.RL_set_output_canPut_wire_2();
	 INST_top.DEF_moreFlits_1_1___d441 = INST_top.INST_moreFlits_1_1.METH_read();
	 INST_top.DEF_inputDest_1_0_wget____d427 = INST_top.INST_inputDest_1_0.METH_wget();
	 INST_top.DEF_IF_inputDest_1_0_whas__26_THEN_inputDest_1_0_w_ETC___d434 = INST_top.DEF_inputDest_1_0_wget____d427;
	 INST_top.DEF_IF_inputDest_1_0_whas__26_THEN_NOT_inputDest_1_ETC___d429 = !(INST_top.DEF_inputDest_1_0_wget____d427);
	 INST_top.DEF_inputCanPeek_1_0_whas____d423 = INST_top.INST_inputCanPeek_1_0.METH_whas();
	 INST_top.DEF_inputCanPeek_1_0_wget____d424 = INST_top.INST_inputCanPeek_1_0.METH_wget();
	 DEF_INST_top_DEF_moreFlits_1_1_41_BIT_2___d442 = (tUInt8)((INST_top.DEF_moreFlits_1_1___d441) >> 2u);
	 INST_top.DEF_dfltOutputCanPut_1_1_whas__30_AND_dfltOutputCa_ETC___d432 = INST_top.INST_dfltOutputCanPut_1_1.METH_whas() && INST_top.INST_dfltOutputCanPut_1_1.METH_wget();
	 INST_top.DEF_outputCanPut_1_0_whas__35_AND_outputCanPut_1_0_ETC___d437 = INST_top.INST_outputCanPut_1_0.METH_whas() && INST_top.INST_outputCanPut_1_0.METH_wget();
	 INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d425 = INST_top.DEF_inputCanPeek_1_0_whas____d423 && INST_top.DEF_inputCanPeek_1_0_wget____d424;
	 INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d440 = INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d425 && ((INST_top.DEF_IF_inputDest_1_0_whas__26_THEN_NOT_inputDest_1_ETC___d429 && INST_top.DEF_dfltOutputCanPut_1_1_whas__30_AND_dfltOutputCa_ETC___d432) || (INST_top.DEF_IF_inputDest_1_0_whas__26_THEN_inputDest_1_0_w_ETC___d434 && INST_top.DEF_outputCanPut_1_0_whas__35_AND_outputCanPut_1_0_ETC___d437));
	 DEF_INST_top_DEF_NOT_moreFlits_1_1_41_BIT_2_42___d443 = !DEF_INST_top_DEF_moreFlits_1_1_41_BIT_2___d442;
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_2 = INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d440 && DEF_INST_top_DEF_NOT_moreFlits_1_1_41_BIT_2_42___d443;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_2 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_2;
	 INST_top.DEF_moreFlits_1_1_41_BIT_0___d464 = (tUInt8)((tUInt8)1u & (INST_top.DEF_moreFlits_1_1___d441));
	 INST_top.DEF_NOT_moreFlits_1_1_41_BIT_0_64___d465 = !(INST_top.DEF_moreFlits_1_1_41_BIT_0___d464);
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_3 = INST_top.DEF_m1_shim_shim_arff_rv_port1__read__13_BIT_42___d414 && (((DEF_INST_top_DEF_moreFlits_1_1_41_BIT_2___d442 && (tUInt8)((tUInt8)1u & ((INST_top.DEF_moreFlits_1_1___d441) >> 1u))) && INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d425) && ((INST_top.DEF_NOT_moreFlits_1_1_41_BIT_0_64___d465 && INST_top.DEF_dfltOutputCanPut_1_1_whas__30_AND_dfltOutputCa_ETC___d432) || (INST_top.DEF_moreFlits_1_1_41_BIT_0___d464 && INST_top.DEF_outputCanPut_1_0_whas__35_AND_outputCanPut_1_0_ETC___d437)));
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit_3 = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_2)
	   INST_top.RL_arbitrate_2();
	 DEF_INST_top_DEF_selectInput_1_0_whas__47_AND_selectInput_1_0_w_ETC___d449 = INST_top.INST_selectInput_1_0.METH_whas() && INST_top.INST_selectInput_1_0.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_3 = (DEF_INST_top_DEF_selectInput_1_0_whas__47_AND_selectInput_1_0_w_ETC___d449 && (!(INST_top.DEF_inputCanPeek_1_0_whas____d423) || !(INST_top.DEF_inputCanPeek_1_0_wget____d424))) && !DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_2;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_3 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_3 = INST_top.DEF_m1_shim_shim_arff_rv_port1__read__13_BIT_42___d414 && ((DEF_INST_top_DEF_NOT_moreFlits_1_1_41_BIT_2_42___d443 && DEF_INST_top_DEF_selectInput_1_0_whas__47_AND_selectInput_1_0_w_ETC___d449) && INST_top.DEF_inputCanPeek_1_0_whas__23_AND_inputCanPeek_1_0_ETC___d425);
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit_3 = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_3)
	   INST_top.RL_arbitration_fail_3();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit_3)
	   INST_top.RL_input_first_flit_3();
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit_3)
	   INST_top.RL_input_follow_flit_3();
	 DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected_1 = INST_top.DEF_noRouteSlv_1_flitCount_21_EQ_0___d422 && (INST_top.INST_toDfltOutput_1_1.METH_whas() && INST_top.DEF_dfltOutputCanPut_1_1_whas__30_AND_dfltOutputCa_ETC___d432);
	 INST_top.DEF_WILL_FIRE_RL_dflt_output_selected_1 = DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected_1;
	 INST_top.DEF_NOT_s1_shim_shim_arff_rv_port0__read__18_BIT_4_ETC___d420 = !((tUInt8)(INST_top.INST_s1_shim_shim_arff_rv.METH_port0__read() >> 42u));
	 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_2 = INST_top.DEF_NOT_s1_shim_shim_arff_rv_port0__read__18_BIT_4_ETC___d420 && (INST_top.INST_toOutput_1_0.METH_whas() && INST_top.DEF_outputCanPut_1_0_whas__35_AND_outputCanPut_1_0_ETC___d437);
	 INST_top.DEF_WILL_FIRE_RL_output_selected_2 = DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_2;
	 if (INST_top.DEF_WILL_FIRE_RL_dflt_output_selected_1)
	   INST_top.RL_dflt_output_selected_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire_3)
	   INST_top.RL_set_output_canPut_wire_3();
	 INST_top.DEF_outputCanPut_1_0_1_wget____d499 = INST_top.INST_outputCanPut_1_0_1.METH_wget();
	 INST_top.DEF_outputCanPut_1_0_1_whas____d498 = INST_top.INST_outputCanPut_1_0_1.METH_whas();
	 INST_top.DEF_inputCanPeek_1_0_1_wget____d493 = INST_top.INST_inputCanPeek_1_0_1.METH_wget();
	 INST_top.DEF_inputCanPeek_1_0_1_whas____d492 = INST_top.INST_inputCanPeek_1_0_1.METH_whas();
	 DEF_INST_top_DEF_moreFlits_1_2___d512 = INST_top.INST_moreFlits_1_2.METH_read();
	 DEF_INST_top_DEF_moreFlits_1_2_12_BIT_3___d513 = (tUInt8)(DEF_INST_top_DEF_moreFlits_1_2___d512 >> 3u);
	 INST_top.DEF_outputCanPut_1_0_1_whas__98_AND_outputCanPut_1_ETC___d500 = INST_top.DEF_outputCanPut_1_0_1_whas____d498 && INST_top.DEF_outputCanPut_1_0_1_wget____d499;
	 DEF_INST_top_DEF_moreFlits_1_2_12_BIT_0_84_AND_outputCanPut_1_0_ETC___d585 = (tUInt8)((tUInt8)1u & DEF_INST_top_DEF_moreFlits_1_2___d512) && INST_top.DEF_outputCanPut_1_0_1_whas__98_AND_outputCanPut_1_ETC___d500;
	 INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d494 = INST_top.DEF_inputCanPeek_1_0_1_whas____d492 && INST_top.DEF_inputCanPeek_1_0_1_wget____d493;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_4 = (INST_top.DEF_NOT_noRouteSlv_1_flitCount_21_EQ_0_22___d483 && (((DEF_INST_top_DEF_moreFlits_1_2_12_BIT_3___d513 && (tUInt8)((tUInt8)1u & (DEF_INST_top_DEF_moreFlits_1_2___d512 >> 1u))) && INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d494) && DEF_INST_top_DEF_moreFlits_1_2_12_BIT_0_84_AND_outputCanPut_1_0_ETC___d585)) && !DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected_1;
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit_4 = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_4;
	 INST_top.DEF_inputCanPeek_1_1_wget____d504 = INST_top.INST_inputCanPeek_1_1.METH_wget();
	 INST_top.DEF_inputCanPeek_1_1_whas____d503 = INST_top.INST_inputCanPeek_1_1.METH_whas();
	 INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d505 = INST_top.DEF_inputCanPeek_1_1_whas____d503 && INST_top.DEF_inputCanPeek_1_1_wget____d504;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5 = INST_top.DEF_s1_shim_shim_rff_rv_port1__read__86_BIT_131___d487 && (((DEF_INST_top_DEF_moreFlits_1_2_12_BIT_3___d513 && (tUInt8)((tUInt8)1u & (DEF_INST_top_DEF_moreFlits_1_2___d512 >> 2u))) && INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d505) && DEF_INST_top_DEF_moreFlits_1_2_12_BIT_0_84_AND_outputCanPut_1_0_ETC___d585);
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit_5 = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5;
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit_5)
	   INST_top.RL_input_follow_flit_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_setCanPut)
	   INST_top.RL_split_0_awug_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_setCanPut)
	   INST_top.RL_split_0_wug_setCanPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_output_canPut_wire)
	   INST_top.RL_set_output_canPut_wire();
	 INST_top.DEF_moreFlits___d248 = INST_top.INST_moreFlits.METH_read();
	 INST_top.DEF_moreFlits_48_BIT_0___d276 = (tUInt8)((tUInt8)1u & (INST_top.DEF_moreFlits___d248));
	 INST_top.DEF_inputCanPeek_0_whas____d230 = INST_top.INST_inputCanPeek_0.METH_whas();
	 INST_top.DEF_inputCanPeek_0_wget____d231 = INST_top.INST_inputCanPeek_0.METH_wget();
	 DEF_INST_top_DEF_moreFlits_48_BIT_2___d249 = (tUInt8)((INST_top.DEF_moreFlits___d248) >> 2u);
	 INST_top.DEF_dfltOutputCanPut_whas__37_AND_dfltOutputCanPut_ETC___d239 = INST_top.INST_dfltOutputCanPut.METH_whas() && INST_top.INST_dfltOutputCanPut.METH_wget();
	 INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d232 = INST_top.DEF_inputCanPeek_0_whas____d230 && INST_top.DEF_inputCanPeek_0_wget____d231;
	 INST_top.DEF_outputCanPut_0_whas__42_AND_outputCanPut_0_wge_ETC___d244 = INST_top.INST_outputCanPut_0.METH_whas() && INST_top.INST_outputCanPut_0.METH_wget();
	 INST_top.DEF_NOT_moreFlits_48_BIT_0_76___d277 = !(INST_top.DEF_moreFlits_48_BIT_0___d276);
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit = INST_top.DEF_IF_merged_0_flitLeft_38_EQ_0_39_THEN_merged_0__ETC___d209 && (((DEF_INST_top_DEF_moreFlits_48_BIT_2___d249 && (tUInt8)((tUInt8)1u & ((INST_top.DEF_moreFlits___d248) >> 1u))) && INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d232) && ((INST_top.DEF_NOT_moreFlits_48_BIT_0_76___d277 && INST_top.DEF_dfltOutputCanPut_whas__37_AND_dfltOutputCanPut_ETC___d239) || (INST_top.DEF_moreFlits_48_BIT_0___d276 && INST_top.DEF_outputCanPut_0_whas__42_AND_outputCanPut_0_wge_ETC___d244)));
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit;
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_58)
	   INST_top.__me_check_58();
	 if (INST_top.DEF_WILL_FIRE_RL_output_selected_2)
	   INST_top.RL_output_selected_2();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_60)
	   INST_top.__me_check_60();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_4)
	   INST_top.RL_set_input_peek_wires_4();
	 INST_top.DEF_inputDest_1_1_wget____d507 = INST_top.INST_inputDest_1_1.METH_wget();
	 INST_top.DEF_IF_inputDest_1_1_whas__06_THEN_inputDest_1_1_w_ETC___d508 = INST_top.DEF_inputDest_1_1_wget____d507;
	 INST_top.DEF_inputDest_1_0_1_wget____d496 = INST_top.INST_inputDest_1_0_1.METH_wget();
	 INST_top.DEF_IF_inputDest_1_0_1_whas__95_THEN_inputDest_1_0_ETC___d497 = INST_top.DEF_inputDest_1_0_1_wget____d496;
	 INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d510 = INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d505 && (INST_top.DEF_IF_inputDest_1_1_whas__06_THEN_inputDest_1_1_w_ETC___d508 && INST_top.DEF_outputCanPut_1_0_1_whas__98_AND_outputCanPut_1_ETC___d500);
	 INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d502 = INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d494 && (INST_top.DEF_IF_inputDest_1_0_1_whas__95_THEN_inputDest_1_0_ETC___d497 && INST_top.DEF_outputCanPut_1_0_1_whas__98_AND_outputCanPut_1_ETC___d500);
	 DEF_INST_top_DEF_NOT_moreFlits_1_2_12_BIT_3_13___d514 = !DEF_INST_top_DEF_moreFlits_1_2_12_BIT_3___d513;
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_3 = ((INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d502 || INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d510) && DEF_INST_top_DEF_NOT_moreFlits_1_2_12_BIT_3_13___d514) && !DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_3 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_3)
	   INST_top.RL_arbitrate_3();
	 INST_top.DEF_NOT_inputCanPeek_1_0_1_whas__92_20_OR_NOT_inpu_ETC___d522 = !(INST_top.DEF_inputCanPeek_1_0_1_whas____d492) || !(INST_top.DEF_inputCanPeek_1_0_1_wget____d493);
	 DEF_INST_top_DEF_selectInput_1_0_1_whas__48_AND_selectInput_1_0_ETC___d550 = INST_top.INST_selectInput_1_0_1.METH_whas() && INST_top.INST_selectInput_1_0_1.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_4 = DEF_INST_top_DEF_selectInput_1_0_1_whas__48_AND_selectInput_1_0_ETC___d550 && INST_top.DEF_NOT_inputCanPeek_1_0_1_whas__92_20_OR_NOT_inpu_ETC___d522;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_4 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_4;
	 INST_top.DEF_NOT_inputCanPeek_1_1_whas__03_30_OR_NOT_inputC_ETC___d532 = !(INST_top.DEF_inputCanPeek_1_1_whas____d503) || !(INST_top.DEF_inputCanPeek_1_1_wget____d504);
	 DEF_INST_top_DEF_selectInput_1_1_whas__59_AND_selectInput_1_1_w_ETC___d561 = INST_top.INST_selectInput_1_1.METH_whas() && INST_top.INST_selectInput_1_1.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_5 = (DEF_INST_top_DEF_selectInput_1_1_whas__59_AND_selectInput_1_1_w_ETC___d561 && INST_top.DEF_NOT_inputCanPeek_1_1_whas__03_30_OR_NOT_inputC_ETC___d532) && !DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_5 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_5;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_4 = (INST_top.DEF_NOT_noRouteSlv_1_flitCount_21_EQ_0_22___d483 && ((DEF_INST_top_DEF_NOT_moreFlits_1_2_12_BIT_3_13___d514 && DEF_INST_top_DEF_selectInput_1_0_1_whas__48_AND_selectInput_1_0_ETC___d550) && INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d494)) && !(DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5 || DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected_1);
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit_4 = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_4;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_5 = (INST_top.DEF_s1_shim_shim_rff_rv_port1__read__86_BIT_131___d487 && ((DEF_INST_top_DEF_NOT_moreFlits_1_2_12_BIT_3_13___d514 && DEF_INST_top_DEF_selectInput_1_1_whas__59_AND_selectInput_1_1_w_ETC___d561) && INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d505)) && !DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_5;
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit_5 = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_5;
	 INST_top.DEF_NOT_inputDest_1_0_1_wget__96___d523 = !(INST_top.DEF_inputDest_1_0_1_wget____d496);
	 INST_top.DEF_IF_inputDest_1_0_1_whas__95_THEN_NOT_inputDest_ETC___d524 = INST_top.DEF_NOT_inputDest_1_0_1_wget__96___d523;
	 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_4 = (DEF_INST_top_DEF_selectInput_1_0_1_whas__48_AND_selectInput_1_0_ETC___d550 && INST_top.DEF_inputCanPeek_1_0_1_whas__92_AND_inputCanPeek_1_ETC___d494) && INST_top.DEF_IF_inputDest_1_0_1_whas__95_THEN_NOT_inputDest_ETC___d524;
	 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_4 = DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_4;
	 INST_top.DEF_NOT_inputDest_1_1_wget__07___d533 = !(INST_top.DEF_inputDest_1_1_wget____d507);
	 INST_top.DEF_IF_inputDest_1_1_whas__06_THEN_NOT_inputDest_1_ETC___d534 = INST_top.DEF_NOT_inputDest_1_1_wget__07___d533;
	 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_5 = (DEF_INST_top_DEF_selectInput_1_1_whas__59_AND_selectInput_1_1_w_ETC___d561 && INST_top.DEF_inputCanPeek_1_1_whas__03_AND_inputCanPeek_1_1_ETC___d505) && INST_top.DEF_IF_inputDest_1_1_whas__06_THEN_NOT_inputDest_1_ETC___d534;
	 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_5 = DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_5;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_4)
	   INST_top.RL_arbitration_fail_4();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit_4)
	   INST_top.RL_input_first_flit_4();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit_5)
	   INST_top.RL_input_first_flit_5();
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit_4)
	   INST_top.RL_input_follow_flit_4();
	 INST_top.DEF_m1_shim_shim_rff_rv_port0__read____d489 = INST_top.INST_m1_shim_shim_rff_rv.METH_port0__read();
	 INST_top.DEF_NOT_m1_shim_shim_rff_rv_port0__read__89_BIT_13_ETC___d491 = !INST_top.DEF_m1_shim_shim_rff_rv_port0__read____d489.get_bits_in_word8(4u,
																			  3u,
																			  1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_3 = INST_top.DEF_NOT_m1_shim_shim_rff_rv_port0__read__89_BIT_13_ETC___d491 && (INST_top.INST_toOutput_1_0_1.METH_whas() && INST_top.DEF_outputCanPut_1_0_1_whas__98_AND_outputCanPut_1_ETC___d500);
	 DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_3 = DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_3;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_4)
	   INST_top.RL_legal_destination_fail_4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_5)
	   INST_top.RL_arbitration_fail_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_5)
	   INST_top.RL_legal_destination_fail_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_AWFlit)
	   INST_top.RL_m1_putAXI4_AWFlit();
	 INST_top.DEF_m1_shim_shim_awff_rv_port1__read____d99 = INST_top.INST_m1_shim_shim_awff_rv.METH_port1__read();
	 INST_top.DEF_m1_shim_shim_awff_rv_port1__read__9_BIT_42___d100 = (tUInt8)((INST_top.DEF_m1_shim_shim_awff_rv_port1__read____d99) >> 42u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setPeek = INST_top.DEF_m1_shim_shim_awff_rv_port1__read__9_BIT_42___d100;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_setPeek;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m1_putAXI4_WFlit)
	   INST_top.RL_m1_putAXI4_WFlit();
	 INST_top.DEF_m1_shim_shim_wff_rv_port1__read____d112 = INST_top.INST_m1_shim_shim_wff_rv.METH_port1__read();
	 INST_top.DEF_m1_shim_shim_wff_rv_port1__read__12_BIT_145___d113 = INST_top.DEF_m1_shim_shim_wff_rv_port1__read____d112.get_bits_in_word8(4u,
																		  17u,
																		  1u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setPeek = INST_top.DEF_m1_shim_shim_wff_rv_port1__read__12_BIT_145___d113;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setPeek = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_setPeek;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setCanPeek)
	   INST_top.RL_merged_0_awug_setCanPeek();
	 DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas____d103 = INST_top.INST_merged_0_awug_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_merged_0_awug_canPeekWire_wget____d105 = INST_top.INST_merged_0_awug_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas__03_AND_merged__ETC___d109 = DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas____d103 && DEF_INST_top_DEF_merged_0_awug_canPeekWire_wget____d105;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awFlit = INST_top.INST_merged_0_awff.METH_i_notFull() && DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas__03_AND_merged__ETC___d109;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awFlit = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_setPeek)
	   INST_top.RL_merged_0_awug_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setCanPeek)
	   INST_top.RL_merged_0_wug_setCanPeek();
	 DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas____d116 = INST_top.INST_merged_0_wug_canPeekWire.METH_whas();
	 DEF_INST_top_DEF_merged_0_wug_canPeekWire_wget____d118 = INST_top.INST_merged_0_wug_canPeekWire.METH_wget();
	 DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas__16_AND_merged_0_ETC___d122 = DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas____d116 && DEF_INST_top_DEF_merged_0_wug_canPeekWire_wget____d118;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wFlit = INST_top.INST_merged_0_wff.METH_i_notFull() && DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas__16_AND_merged_0_ETC___d122;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wFlit = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_setPeek)
	   INST_top.RL_merged_0_wug_setPeek();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_s1_putAXI4_BFlit)
	   INST_top.RL_s1_putAXI4_BFlit();
	 INST_top.DEF_s1_shim_shim_bff_rv_port1__read____d298 = INST_top.INST_s1_shim_shim_bff_rv.METH_port1__read();
	 INST_top.DEF_s1_shim_shim_bff_rv_port1__read__98_BIT_2___d299 = (tUInt8)((INST_top.DEF_s1_shim_shim_bff_rv_port1__read____d298) >> 2u);
	 DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_2 = INST_top.DEF_s1_shim_shim_bff_rv_port1__read__98_BIT_2___d299;
	 DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_2 = DEF_INST_top_DEF_CAN_FIRE_RL_set_input_peek_wires_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_canPeek_wire_2)
	   INST_top.RL_set_input_canPeek_wire_2();
	 INST_top.DEF_inputCanPeek_1_wget____d316 = INST_top.INST_inputCanPeek_1.METH_wget();
	 INST_top.DEF_inputCanPeek_1_whas____d315 = INST_top.INST_inputCanPeek_1.METH_whas();
	 INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d317 = INST_top.DEF_inputCanPeek_1_whas____d315 && INST_top.DEF_inputCanPeek_1_wget____d316;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_2 = INST_top.DEF_s1_shim_shim_bff_rv_port1__read__98_BIT_2___d299 && (((DEF_INST_top_DEF_moreFlits_1_24_BIT_3___d325 && (tUInt8)((tUInt8)1u & (DEF_INST_top_DEF_moreFlits_1___d324 >> 2u))) && INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d317) && DEF_INST_top_DEF_moreFlits_1_24_BIT_0_92_AND_outputCanPut_0_1_w_ETC___d393);
	 INST_top.DEF_WILL_FIRE_RL_input_follow_flit_2 = DEF_INST_top_DEF_CAN_FIRE_RL_input_follow_flit_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires_2)
	   INST_top.RL_set_input_peek_wires_2();
	 INST_top.DEF_inputDest_1_wget____d319 = INST_top.INST_inputDest_1.METH_wget();
	 INST_top.DEF_IF_inputDest_1_whas__18_THEN_inputDest_1_wget__ETC___d320 = INST_top.DEF_inputDest_1_wget____d319;
	 INST_top.DEF_inputDest_0_1_wget____d308 = INST_top.INST_inputDest_0_1.METH_wget();
	 INST_top.DEF_IF_inputDest_0_1_whas__07_THEN_inputDest_0_1_w_ETC___d309 = INST_top.DEF_inputDest_0_1_wget____d308;
	 INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d322 = INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d317 && (INST_top.DEF_IF_inputDest_1_whas__18_THEN_inputDest_1_wget__ETC___d320 && INST_top.DEF_outputCanPut_0_1_whas__10_AND_outputCanPut_0_1_ETC___d312);
	 INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d314 = INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d306 && (INST_top.DEF_IF_inputDest_0_1_whas__07_THEN_inputDest_0_1_w_ETC___d309 && INST_top.DEF_outputCanPut_0_1_whas__10_AND_outputCanPut_0_1_ETC___d312);
	 DEF_INST_top_DEF_NOT_moreFlits_1_24_BIT_3_25___d326 = !DEF_INST_top_DEF_moreFlits_1_24_BIT_3___d325;
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_1 = (INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d314 || INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d322) && DEF_INST_top_DEF_NOT_moreFlits_1_24_BIT_3_25___d326;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_1 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate_1;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate_1)
	   INST_top.RL_arbitrate_1();
	 INST_top.DEF_NOT_inputCanPeek_0_1_whas__04_32_OR_NOT_inputC_ETC___d334 = !(INST_top.DEF_inputCanPeek_0_1_whas____d304) || !(INST_top.DEF_inputCanPeek_0_1_wget____d305);
	 DEF_INST_top_DEF_selectInput_0_1_whas__60_AND_selectInput_0_1_w_ETC___d362 = INST_top.INST_selectInput_0_1.METH_whas() && INST_top.INST_selectInput_0_1.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_1 = DEF_INST_top_DEF_selectInput_0_1_whas__60_AND_selectInput_0_1_w_ETC___d362 && INST_top.DEF_NOT_inputCanPeek_0_1_whas__04_32_OR_NOT_inputC_ETC___d334;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_1 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_1;
	 INST_top.DEF_NOT_inputCanPeek_1_whas__15_42_OR_NOT_inputCan_ETC___d344 = !(INST_top.DEF_inputCanPeek_1_whas____d315) || !(INST_top.DEF_inputCanPeek_1_wget____d316);
	 DEF_INST_top_DEF_selectInput_1_whas__71_AND_selectInput_1_wget__72___d373 = INST_top.INST_selectInput_1.METH_whas() && INST_top.INST_selectInput_1.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_2 = DEF_INST_top_DEF_selectInput_1_whas__71_AND_selectInput_1_wget__72___d373 && INST_top.DEF_NOT_inputCanPeek_1_whas__15_42_OR_NOT_inputCan_ETC___d344;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_2 = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail_2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_1 = DEF_INST_top_DEF_noRouteSlv_rspFF_i_notEmpty____d296 && ((DEF_INST_top_DEF_NOT_moreFlits_1_24_BIT_3_25___d326 && DEF_INST_top_DEF_selectInput_0_1_whas__60_AND_selectInput_0_1_w_ETC___d362) && INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d306);
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit_1 = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_2 = INST_top.DEF_s1_shim_shim_bff_rv_port1__read__98_BIT_2___d299 && ((DEF_INST_top_DEF_NOT_moreFlits_1_24_BIT_3_25___d326 && DEF_INST_top_DEF_selectInput_1_whas__71_AND_selectInput_1_wget__72___d373) && INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d317);
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit_2 = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit_2;
	 INST_top.DEF_NOT_inputDest_0_1_wget__08___d335 = !(INST_top.DEF_inputDest_0_1_wget____d308);
	 INST_top.DEF_IF_inputDest_0_1_whas__07_THEN_NOT_inputDest_0_ETC___d336 = INST_top.DEF_NOT_inputDest_0_1_wget__08___d335;
	 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_1 = (DEF_INST_top_DEF_selectInput_0_1_whas__60_AND_selectInput_0_1_w_ETC___d362 && INST_top.DEF_inputCanPeek_0_1_whas__04_AND_inputCanPeek_0_1_ETC___d306) && INST_top.DEF_IF_inputDest_0_1_whas__07_THEN_NOT_inputDest_0_ETC___d336;
	 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_1 = DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_1;
	 INST_top.DEF_NOT_inputDest_1_wget__19___d345 = !(INST_top.DEF_inputDest_1_wget____d319);
	 INST_top.DEF_IF_inputDest_1_whas__18_THEN_NOT_inputDest_1_w_ETC___d346 = INST_top.DEF_NOT_inputDest_1_wget__19___d345;
	 DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_2 = (DEF_INST_top_DEF_selectInput_1_whas__71_AND_selectInput_1_wget__72___d373 && INST_top.DEF_inputCanPeek_1_whas__15_AND_inputCanPeek_1_wge_ETC___d317) && INST_top.DEF_IF_inputDest_1_whas__18_THEN_NOT_inputDest_1_w_ETC___d346;
	 DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_2 = DEF_INST_top_DEF_CAN_FIRE_RL_legal_destination_fail_2;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_1)
	   INST_top.RL_arbitration_fail_1();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit_2)
	   INST_top.RL_input_first_flit_2();
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit_2)
	   INST_top.RL_input_follow_flit_2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_1)
	   INST_top.RL_legal_destination_fail_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail_2)
	   INST_top.RL_arbitration_fail_2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_legal_destination_fail_2)
	   INST_top.RL_legal_destination_fail_2();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_49)
	   INST_top.__me_check_49();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_passFlit)
	   INST_top.RL_merged_0_passFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_set_input_peek_wires)
	   INST_top.RL_set_input_peek_wires();
	 INST_top.DEF_inputDest_0_wget____d234 = INST_top.INST_inputDest_0.METH_wget();
	 INST_top.DEF_IF_inputDest_0_whas__33_THEN_inputDest_0_wget__ETC___d241 = INST_top.DEF_inputDest_0_wget____d234;
	 INST_top.DEF_IF_inputDest_0_whas__33_THEN_NOT_inputDest_0_w_ETC___d236 = !(INST_top.DEF_inputDest_0_wget____d234);
	 INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d247 = INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d232 && ((INST_top.DEF_IF_inputDest_0_whas__33_THEN_NOT_inputDest_0_w_ETC___d236 && INST_top.DEF_dfltOutputCanPut_whas__37_AND_dfltOutputCanPut_ETC___d239) || (INST_top.DEF_IF_inputDest_0_whas__33_THEN_inputDest_0_wget__ETC___d241 && INST_top.DEF_outputCanPut_0_whas__42_AND_outputCanPut_0_wge_ETC___d244));
	 DEF_INST_top_DEF_NOT_moreFlits_48_BIT_2_49___d250 = !DEF_INST_top_DEF_moreFlits_48_BIT_2___d249;
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate = INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d247 && DEF_INST_top_DEF_NOT_moreFlits_48_BIT_2_49___d250;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate = DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitrate)
	   INST_top.RL_arbitrate();
	 DEF_INST_top_DEF_selectInput_0_whas__54_AND_selectInput_0_wget__55___d256 = INST_top.INST_selectInput_0.METH_whas() && INST_top.INST_selectInput_0.METH_wget();
	 DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail = (DEF_INST_top_DEF_selectInput_0_whas__54_AND_selectInput_0_wget__55___d256 && (!(INST_top.DEF_inputCanPeek_0_whas____d230) || !(INST_top.DEF_inputCanPeek_0_wget____d231))) && !DEF_INST_top_DEF_CAN_FIRE_RL_arbitrate;
	 DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail = DEF_INST_top_DEF_CAN_FIRE_RL_arbitration_fail;
	 DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit = INST_top.DEF_IF_merged_0_flitLeft_38_EQ_0_39_THEN_merged_0__ETC___d209 && ((DEF_INST_top_DEF_NOT_moreFlits_48_BIT_2_49___d250 && DEF_INST_top_DEF_selectInput_0_whas__54_AND_selectInput_0_wget__55___d256) && INST_top.DEF_inputCanPeek_0_whas__30_AND_inputCanPeek_0_wge_ETC___d232);
	 INST_top.DEF_WILL_FIRE_RL_input_first_flit = DEF_INST_top_DEF_CAN_FIRE_RL_input_first_flit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_arbitration_fail)
	   INST_top.RL_arbitration_fail();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit)
	   INST_top.RL_input_first_flit();
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit)
	   INST_top.RL_input_follow_flit();
	 INST_top.DEF_noRouteSlv_rspFF_notFull____d229 = INST_top.INST_noRouteSlv_rspFF.METH_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected = (INST_top.DEF_noRouteSlv_rspFF_notFull____d229 && INST_top.INST_noRouteSlv_rspFF.METH_i_notFull()) && (INST_top.INST_toDfltOutput.METH_whas() && INST_top.DEF_dfltOutputCanPut_whas__37_AND_dfltOutputCanPut_ETC___d239);
	 INST_top.DEF_WILL_FIRE_RL_dflt_output_selected = DEF_INST_top_DEF_CAN_FIRE_RL_dflt_output_selected;
	 DEF_INST_top_DEF_merged_0_doDrop_whas____d144 = INST_top.INST_merged_0_doDrop.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genFirst = DEF_INST_top_DEF_merged_0_awff_i_notEmpty__35_AND_merged_0_wff__ETC___d137 && (DEF_INST_top_DEF_merged_0_doDrop_whas____d144 && INST_top.DEF_merged_0_flitLeft_38_EQ_0___d139);
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genFirst = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genFirst;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genOther = (DEF_INST_top_DEF_merged_0_wff_i_notEmpty____d136 && (DEF_INST_top_DEF_merged_0_doDrop_whas____d144 && !(INST_top.DEF_merged_0_flitLeft_38_EQ_0___d139))) && !DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_passFlit;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genOther = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_genOther;
	 INST_top.DEF_x__h9013 = INST_top.INST_split_0_flitLeft.METH_read();
	 INST_top.DEF_split_0_flitLeft_76_EQ_0___d177 = (INST_top.DEF_x__h9013) == (tUInt8)0u;
	 INST_top.DEF_split_0_wug_canPutWire_whas__82_AND_split_0_wu_ETC___d184 = INST_top.INST_split_0_wug_canPutWire.METH_whas() && INST_top.INST_split_0_wug_canPutWire.METH_wget();
	 INST_top.DEF_split_0_awug_canPutWire_whas__78_AND_split_0_a_ETC___d180 = INST_top.INST_split_0_awug_canPutWire.METH_whas() && INST_top.INST_split_0_awug_canPutWire.METH_wget();
	 INST_top.DEF_IF_split_0_flitLeft_76_EQ_0_77_THEN_split_0_aw_ETC___d228 = INST_top.DEF_split_0_flitLeft_76_EQ_0___d177 ? INST_top.DEF_split_0_awug_canPutWire_whas__78_AND_split_0_a_ETC___d180 && INST_top.DEF_split_0_wug_canPutWire_whas__82_AND_split_0_wu_ETC___d184 : INST_top.DEF_split_0_wug_canPutWire_whas__82_AND_split_0_wu_ETC___d184;
	 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected = INST_top.DEF_IF_split_0_flitLeft_76_EQ_0_77_THEN_split_0_aw_ETC___d228 && (INST_top.INST_toOutput_0.METH_whas() && INST_top.DEF_outputCanPut_0_whas__42_AND_outputCanPut_0_wge_ETC___d244);
	 INST_top.DEF_WILL_FIRE_RL_output_selected = DEF_INST_top_DEF_CAN_FIRE_RL_output_selected;
	 if (INST_top.DEF_WILL_FIRE_RL_dflt_output_selected)
	   INST_top.RL_dflt_output_selected();
	 if (INST_top.DEF_WILL_FIRE_RL_input_follow_flit_1)
	   INST_top.RL_input_follow_flit_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awFlit)
	   INST_top.RL_merged_0_awFlit();
	 DEF_INST_top_DEF_merged_0_awug_dropWire_whas____d102 = INST_top.INST_merged_0_awug_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_doDrop = INST_top.DEF_m1_shim_shim_awff_rv_port1__read__9_BIT_42___d100 && (DEF_INST_top_DEF_merged_0_awug_dropWire_whas____d102 && DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas__03_AND_merged__ETC___d109);
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_warnDoDrop = (DEF_INST_top_DEF_merged_0_awug_dropWire_whas____d102 && (!DEF_INST_top_DEF_merged_0_awug_canPeekWire_whas____d103 || !DEF_INST_top_DEF_merged_0_awug_canPeekWire_wget____d105)) && !DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awFlit;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_awug_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_doDrop)
	   INST_top.RL_merged_0_awug_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genFirst)
	   INST_top.RL_merged_0_genFirst();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wFlit)
	   INST_top.RL_merged_0_wFlit();
	 DEF_INST_top_DEF_merged_0_wug_dropWire_whas____d115 = INST_top.INST_merged_0_wug_dropWire.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_doDrop = INST_top.DEF_m1_shim_shim_wff_rv_port1__read__12_BIT_145___d113 && (DEF_INST_top_DEF_merged_0_wug_dropWire_whas____d115 && DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas__16_AND_merged_0_ETC___d122);
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_doDrop = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_doDrop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_warnDoDrop = (DEF_INST_top_DEF_merged_0_wug_dropWire_whas____d115 && (!DEF_INST_top_DEF_merged_0_wug_canPeekWire_whas____d116 || !DEF_INST_top_DEF_merged_0_wug_canPeekWire_wget____d118)) && !DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wFlit;
	 DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_warnDoDrop = DEF_INST_top_DEF_CAN_FIRE_RL_merged_0_wug_warnDoDrop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_doDrop)
	   INST_top.RL_merged_0_wug_doDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_33)
	   INST_top.__me_check_33();
	 if (INST_top.DEF_WILL_FIRE_RL_output_selected)
	   INST_top.RL_output_selected();
	 DEF_INST_top_DEF_split_0_doPut_whas____d175 = INST_top.INST_split_0_doPut.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putFirst = DEF_INST_top_DEF_split_0_doPut_whas____d175 && ((INST_top.DEF_split_0_flitLeft_76_EQ_0___d177 && INST_top.DEF_split_0_awug_canPutWire_whas__78_AND_split_0_a_ETC___d180) && INST_top.DEF_split_0_wug_canPutWire_whas__82_AND_split_0_wu_ETC___d184);
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putFirst = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putFirst;
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putOther = DEF_INST_top_DEF_split_0_doPut_whas____d175 && (!(INST_top.DEF_split_0_flitLeft_76_EQ_0___d177) && INST_top.DEF_split_0_wug_canPutWire_whas__82_AND_split_0_wu_ETC___d184);
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putOther = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_putOther;
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_35)
	   INST_top.__me_check_35();
	 if (INST_top.DEF_WILL_FIRE_RL_input_first_flit_1)
	   INST_top.RL_input_first_flit_1();
	 INST_top.DEF_NOT_m1_shim_shim_bff_rv_port0__read__01_BIT_2_02___d303 = !((tUInt8)(INST_top.INST_m1_shim_shim_bff_rv.METH_port0__read() >> 2u));
	 DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_1 = INST_top.DEF_NOT_m1_shim_shim_bff_rv_port0__read__01_BIT_2_02___d303 && (INST_top.INST_toOutput_0_1.METH_whas() && INST_top.DEF_outputCanPut_0_1_whas__10_AND_outputCanPut_0_1_ETC___d312);
	 DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_1 = DEF_INST_top_DEF_CAN_FIRE_RL_output_selected_1;
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_47)
	   INST_top.__me_check_47();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_1)
	   INST_top.RL_output_selected_1();
	 INST_top.DEF_m1_shim_shim_bff_rv_port1__read____d28 = INST_top.INST_m1_shim_shim_bff_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_m1_getAXI4_BFlit = ((tUInt8)((INST_top.DEF_m1_shim_shim_bff_rv_port1__read____d28) >> 2u) && (DEF_INST_top_DEF_m1_awSent__h1237 && DEF_INST_top_DEF_m1_reqSent__h1699)) && !(DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_WFlit || DEF_INST_top_DEF_CAN_FIRE_RL_m1_putAXI4_AWFlit);
	 DEF_INST_top_DEF_WILL_FIRE_RL_m1_getAXI4_BFlit = DEF_INST_top_DEF_CAN_FIRE_RL_m1_getAXI4_BFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_m1_getAXI4_BFlit)
	   INST_top.RL_m1_getAXI4_BFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_genOther)
	   INST_top.RL_merged_0_genOther();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_awug_warnDoDrop)
	   INST_top.RL_merged_0_awug_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_merged_0_wug_warnDoDrop)
	   INST_top.RL_merged_0_wug_warnDoDrop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putFirst)
	   INST_top.RL_split_0_putFirst();
	 DEF_INST_top_DEF_split_0_awug_putWire_whas____d162 = INST_top.INST_split_0_awug_putWire.METH_whas();
	 INST_top.DEF_s1_shim_shim_awff_rv_port0__read__59_BIT_42___d160 = (tUInt8)(INST_top.INST_s1_shim_shim_awff_rv.METH_port0__read() >> 42u);
	 INST_top.DEF_NOT_s1_shim_shim_awff_rv_port0__read__59_BIT_4_ETC___d161 = !(INST_top.DEF_s1_shim_shim_awff_rv_port0__read__59_BIT_42___d160);
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_doPut = INST_top.DEF_NOT_s1_shim_shim_awff_rv_port0__read__59_BIT_4_ETC___d161 && DEF_INST_top_DEF_split_0_awug_putWire_whas____d162;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_warnDoPut = DEF_INST_top_DEF_split_0_awug_putWire_whas____d162 && INST_top.DEF_s1_shim_shim_awff_rv_port0__read__59_BIT_42___d160;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_awug_warnDoPut;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_doPut)
	   INST_top.RL_split_0_awug_doPut();
	 INST_top.DEF_s1_shim_shim_awff_rv_port1__read____d47 = INST_top.INST_s1_shim_shim_awff_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_AWFlit = (tUInt8)((INST_top.DEF_s1_shim_shim_awff_rv_port1__read____d47) >> 42u) && INST_top.INST_s1_awResp.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_AWFlit = DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_AWFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_putOther)
	   INST_top.RL_split_0_putOther();
	 INST_top.DEF_s1_shim_shim_wff_rv_port0__read____d167 = INST_top.INST_s1_shim_shim_wff_rv.METH_port0__read();
	 DEF_INST_top_DEF_split_0_wug_putWire_whas____d170 = INST_top.INST_split_0_wug_putWire.METH_whas();
	 INST_top.DEF_s1_shim_shim_wff_rv_port0__read__67_BIT_145___d168 = INST_top.DEF_s1_shim_shim_wff_rv_port0__read____d167.get_bits_in_word8(4u,
																		  17u,
																		  1u);
	 INST_top.DEF_NOT_s1_shim_shim_wff_rv_port0__read__67_BIT_14_ETC___d169 = !(INST_top.DEF_s1_shim_shim_wff_rv_port0__read__67_BIT_145___d168);
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_doPut = INST_top.DEF_NOT_s1_shim_shim_wff_rv_port0__read__67_BIT_14_ETC___d169 && DEF_INST_top_DEF_split_0_wug_putWire_whas____d170;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_doPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_doPut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_warnDoPut = DEF_INST_top_DEF_split_0_wug_putWire_whas____d170 && INST_top.DEF_s1_shim_shim_wff_rv_port0__read__67_BIT_145___d168;
	 DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_warnDoPut = DEF_INST_top_DEF_CAN_FIRE_RL_split_0_wug_warnDoPut;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_awug_warnDoPut)
	   INST_top.RL_split_0_awug_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_AWFlit)
	   INST_top.RL_s1_getAXI4_AWFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_doPut)
	   INST_top.RL_split_0_wug_doPut();
	 INST_top.DEF_s1_shim_shim_wff_rv_port1__read____d71 = INST_top.INST_s1_shim_shim_wff_rv.METH_port1__read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_WFlit = INST_top.DEF_s1_shim_shim_wff_rv_port1__read____d71.get_bits_in_word8(4u,
															       17u,
															       1u) && INST_top.INST_s1_wResp.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_WFlit = DEF_INST_top_DEF_CAN_FIRE_RL_s1_getAXI4_WFlit;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_split_0_wug_warnDoPut)
	   INST_top.RL_split_0_wug_warnDoPut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_s1_getAXI4_WFlit)
	   INST_top.RL_s1_getAXI4_WFlit();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_72)
	   INST_top.__me_check_72();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_74)
	   INST_top.__me_check_74();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_output_selected_3)
	   INST_top.RL_output_selected_3();
	 INST_top.INST_selectInput_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_selectInput_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toDfltOutput_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toOutput_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_dfltOutputCanPut_1_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_outputCanPut_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_1_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_selectInput_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toDfltOutput_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toOutput_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_dfltOutputCanPut_1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_outputCanPut_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_1_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_selectInput_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_selectInput_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toDfltOutput_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toOutput_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_dfltOutputCanPut_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_outputCanPut_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_0_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_selectInput_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toDfltOutput.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_toOutput_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_dfltOutputCanPut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_outputCanPut_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputDest_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputPeek_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_inputCanPeek_0.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_split_0_doPut.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_split_0_wug_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_split_0_wug_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_split_0_awug_putWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_split_0_awug_canPutWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_outflit.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_doDrop.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_wug_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_wug_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_wug_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_awug_dropWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_awug_peekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_merged_0_awug_canPeekWire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s1_shim_shim_rff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s1_shim_shim_arff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s1_shim_shim_bff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s1_shim_shim_wff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_s1_shim_shim_awff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m1_shim_shim_rff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m1_shim_shim_arff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m1_shim_shim_bff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m1_shim_shim_wff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_m1_shim_shim_awff_rv.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_m1_shim_shim_awff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m1_shim_shim_wff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m1_shim_shim_bff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m1_shim_shim_arff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m1_shim_shim_rff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_m1_nextWriteAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m1_awSent.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m1_reqSent.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m1_rspCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_m1_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s1_shim_shim_awff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_shim_shim_wff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_shim_shim_bff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_shim_shim_arff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_shim_shim_rff_rv.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_awResp.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_s1_wResp.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_merged_0_awff.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_merged_0_wff.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_merged_0_flitLeft.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_split_0_flitLeft.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_noRouteSlv_rspFF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_moreFlits.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_firstHot.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_moreFlits_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_firstHot_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_lastSelect.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_noRouteSlv_1_flitCount.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_moreFlits_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_1_firstHot.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_moreFlits_1_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_1_firstHot_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_arbiter_1_lastSelect.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_top::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  top_instance = new MOD_top(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (top_instance->INST_m1_shim_shim_awff_rv.set_clk_0)("CLK");
  (top_instance->INST_m1_shim_shim_wff_rv.set_clk_0)("CLK");
  (top_instance->INST_m1_shim_shim_bff_rv.set_clk_0)("CLK");
  (top_instance->INST_m1_shim_shim_arff_rv.set_clk_0)("CLK");
  (top_instance->INST_m1_shim_shim_rff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_shim_shim_awff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_shim_shim_wff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_shim_shim_bff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_shim_shim_arff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_shim_shim_rff_rv.set_clk_0)("CLK");
  (top_instance->INST_s1_awResp.set_clk_0)("CLK");
  (top_instance->INST_s1_wResp.set_clk_0)("CLK");
  (top_instance->INST_merged_0_awug_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_awug_peekWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_awug_dropWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_wug_canPeekWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_wug_peekWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_wug_dropWire.set_clk_0)("CLK");
  (top_instance->INST_merged_0_awff.set_clk_0)("CLK");
  (top_instance->INST_merged_0_wff.set_clk_0)("CLK");
  (top_instance->INST_merged_0_doDrop.set_clk_0)("CLK");
  (top_instance->INST_merged_0_outflit.set_clk_0)("CLK");
  (top_instance->INST_split_0_awug_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_split_0_awug_putWire.set_clk_0)("CLK");
  (top_instance->INST_split_0_wug_canPutWire.set_clk_0)("CLK");
  (top_instance->INST_split_0_wug_putWire.set_clk_0)("CLK");
  (top_instance->INST_split_0_doPut.set_clk_0)("CLK");
  (top_instance->INST_noRouteSlv_rspFF.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_0.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_0.set_clk_0)("CLK");
  (top_instance->INST_inputDest_0.set_clk_0)("CLK");
  (top_instance->INST_outputCanPut_0.set_clk_0)("CLK");
  (top_instance->INST_dfltOutputCanPut.set_clk_0)("CLK");
  (top_instance->INST_toOutput_0.set_clk_0)("CLK");
  (top_instance->INST_toDfltOutput.set_clk_0)("CLK");
  (top_instance->INST_selectInput_0.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_1.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_1.set_clk_0)("CLK");
  (top_instance->INST_inputDest_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputDest_1.set_clk_0)("CLK");
  (top_instance->INST_outputCanPut_0_1.set_clk_0)("CLK");
  (top_instance->INST_dfltOutputCanPut_1.set_clk_0)("CLK");
  (top_instance->INST_toOutput_0_1.set_clk_0)("CLK");
  (top_instance->INST_toDfltOutput_1.set_clk_0)("CLK");
  (top_instance->INST_selectInput_0_1.set_clk_0)("CLK");
  (top_instance->INST_selectInput_1.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_1_0.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_1_0.set_clk_0)("CLK");
  (top_instance->INST_inputDest_1_0.set_clk_0)("CLK");
  (top_instance->INST_outputCanPut_1_0.set_clk_0)("CLK");
  (top_instance->INST_dfltOutputCanPut_1_1.set_clk_0)("CLK");
  (top_instance->INST_toOutput_1_0.set_clk_0)("CLK");
  (top_instance->INST_toDfltOutput_1_1.set_clk_0)("CLK");
  (top_instance->INST_selectInput_1_0.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputCanPeek_1_1.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputPeek_1_1.set_clk_0)("CLK");
  (top_instance->INST_inputDest_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_inputDest_1_1.set_clk_0)("CLK");
  (top_instance->INST_outputCanPut_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_dfltOutputCanPut_1_2.set_clk_0)("CLK");
  (top_instance->INST_toOutput_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_toDfltOutput_1_2.set_clk_0)("CLK");
  (top_instance->INST_selectInput_1_0_1.set_clk_0)("CLK");
  (top_instance->INST_selectInput_1_1.set_clk_0)("CLK");
  (top_instance->set_clk_0)("CLK");
}
void MODEL_top::destroy_model()
{
  delete top_instance;
  top_instance = NULL;
}
void MODEL_top::reset_model(bool asserted)
{
  (top_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_top::get_instance()
{
  return top_instance;
}

/* Fill in version numbers */
void MODEL_top::get_version(char const **name, char const **build)
{
  *name = "2021.07";
  *build = "4cac6eb";
}

/* Get the model creation time */
time_t MODEL_top::get_creation_time()
{
  
  /* Mon Dec 20 16:57:18 UTC 2021 */
  return 1640019438llu;
}

/* State dumping function */
void MODEL_top::dump_state()
{
  (top_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_top & top_backing(tSimStateHdl simHdl)
{
  static MOD_top *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_top(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_top::dump_VCD_defs()
{
  (top_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_top::dump_VCD(tVCDDumpType dt)
{
  (top_instance->dump_VCD)(dt, vcd_depth(sim_hdl), top_backing(sim_hdl));
}
