# TCL File Generated by Component Editor 21.1
# Fri May 06 12:52:01 BST 2022
# DO NOT MODIFY


# 
# simpleFifo "simpleFifo" v1.0
#  2022.05.06.12:52:01
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module simpleFifo
# 
set_module_property DESCRIPTION ""
set_module_property NAME simpleFifo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME simpleFifo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkSimpleFIFO
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkSimpleFIFO.v VERILOG PATH "C:/Users/nudy1/Desktop/Quartus Verilog/mkSimpleFIFO.v" TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point deq_en
# 
add_interface deq_en conduit end
set_interface_property deq_en associatedClock clock
set_interface_property deq_en associatedReset ""
set_interface_property deq_en ENABLED true
set_interface_property deq_en EXPORT_OF ""
set_interface_property deq_en PORT_NAME_MAP ""
set_interface_property deq_en CMSIS_SVD_VARIABLES ""
set_interface_property deq_en SVD_ADDRESS_GROUP ""

add_interface_port deq_en EN_deq wire Input 1


# 
# connection point deq_rdy
# 
add_interface deq_rdy conduit end
set_interface_property deq_rdy associatedClock clock
set_interface_property deq_rdy associatedReset ""
set_interface_property deq_rdy ENABLED true
set_interface_property deq_rdy EXPORT_OF ""
set_interface_property deq_rdy PORT_NAME_MAP ""
set_interface_property deq_rdy CMSIS_SVD_VARIABLES ""
set_interface_property deq_rdy SVD_ADDRESS_GROUP ""

add_interface_port deq_rdy RDY_deq wire Output 1


# 
# connection point enq_rdy
# 
add_interface enq_rdy conduit end
set_interface_property enq_rdy associatedClock clock
set_interface_property enq_rdy associatedReset ""
set_interface_property enq_rdy ENABLED true
set_interface_property enq_rdy EXPORT_OF ""
set_interface_property enq_rdy PORT_NAME_MAP ""
set_interface_property enq_rdy CMSIS_SVD_VARIABLES ""
set_interface_property enq_rdy SVD_ADDRESS_GROUP ""

add_interface_port enq_rdy RDY_enq wire Output 1


# 
# connection point enq_en
# 
add_interface enq_en conduit end
set_interface_property enq_en associatedClock clock
set_interface_property enq_en associatedReset ""
set_interface_property enq_en ENABLED true
set_interface_property enq_en EXPORT_OF ""
set_interface_property enq_en PORT_NAME_MAP ""
set_interface_property enq_en CMSIS_SVD_VARIABLES ""
set_interface_property enq_en SVD_ADDRESS_GROUP ""

add_interface_port enq_en EN_enq wire Input 1


# 
# connection point enq_value
# 
add_interface enq_value conduit end
set_interface_property enq_value associatedClock clock
set_interface_property enq_value associatedReset ""
set_interface_property enq_value ENABLED true
set_interface_property enq_value EXPORT_OF ""
set_interface_property enq_value PORT_NAME_MAP ""
set_interface_property enq_value CMSIS_SVD_VARIABLES ""
set_interface_property enq_value SVD_ADDRESS_GROUP ""

add_interface_port enq_value enq_value wire Input 32


# 
# connection point first
# 
add_interface first conduit end
set_interface_property first associatedClock clock
set_interface_property first associatedReset ""
set_interface_property first ENABLED true
set_interface_property first EXPORT_OF ""
set_interface_property first PORT_NAME_MAP ""
set_interface_property first CMSIS_SVD_VARIABLES ""
set_interface_property first SVD_ADDRESS_GROUP ""

add_interface_port first first wire Output 32


# 
# connection point first_rdy
# 
add_interface first_rdy conduit end
set_interface_property first_rdy associatedClock clock
set_interface_property first_rdy associatedReset ""
set_interface_property first_rdy ENABLED true
set_interface_property first_rdy EXPORT_OF ""
set_interface_property first_rdy PORT_NAME_MAP ""
set_interface_property first_rdy CMSIS_SVD_VARIABLES ""
set_interface_property first_rdy SVD_ADDRESS_GROUP ""

add_interface_port first_rdy RDY_first wire Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RST_N reset_n Input 1

